### ISSUE TITLE
Core Dump on db update from v35 to v38 DELETE CASCADE

### ISSUE THREAD

**Issue by Xian001** [ElementsProject/lightning#1030]
### Issue and Steps to Reproduce

Pull latest from github, try to launch vs old database, and see this error.

```
xian@xserver:/mnt/md0/lightning/lightningd$ ./lightningd
2018-02-19T06:08:29.840Z lightningd(11588): Updating database from version 35 to 38
db_migrate:SQL logic error or missing database:CREATE TABLE htlc_sigs (channelid INTEGER REFERENCES channels(id) ON DELETE CASCADE, signature BLOB);:table htlc_sigs already exists
Aborted (core dumped)
```

### `getinfo` output
Old db "version" : "v0.5.2-2016-11-21-1886-gb3d4e16"

**Comment by cdecker** [comment]
The migration seems to have failed, because the `version` counter in the DB got out of sync at some point. I assume you only used `master` and not some PRs somewhere that might have introduced or removed migrations?

We are not fully supporting DB backward compatibility, it'll be mandatory once we release 0.6 and only between releases, but it's rather annoying so I won't mark it as `wontfix` right now.

**Comment by Xian001** [comment]
Yes. Only used master.

Thanks for the heads up. Will close the channels and re-create the db.

**Comment by rustyrussell** [comment]
Yes, this works for me here.. However, we used to "upgrade" the database downwards(!), so if you ran a new version, then an old version, then a new version again, it would get deeply upset like this.

You can try hacking it by forcing the version to 38:
```
$ sqlite3 ~/.lightningd/lightningd.sqlite3 'UPDATE VERSION SET version=38;'
```
