### ISSUE TITLE
lnd wants up to 2016 to_self_delay: should we allow > 3 days?

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#1110]
From IRC:

user@machine:/lightning$ lncli fundchannel 02565b3920e81816040bf477c135cdbfc2c931a11fc41593bd3217b1eb5a399c6f 10000000
(20:22:37) p3tr: { "code" : -1, "message" : "sent ERROR to_self_delay 1201 larger than 432" }
(20:22:40) p3tr: user@machine:/lightning$ lncli fundchannel 02565b3920e81816040bf477c135cdbfc2c931a11fc41593bd3217b1eb5a399c6f 5000000
(20:22:43) p3tr: { "code" : -1, "message" : "sent ERROR to_self_delay 600 larger than 432" }
(20:22:46) p3tr: user@machine:/lightning$ lncli fundchannel 02565b3920e81816040bf477c135cdbfc2c931a11fc41593bd3217b1eb5a399c6f 7500000
(20:22:48) p3tr: { "code" : -1, "message" : "sent ERROR to_self_delay 901 larger than 432" }
(20:22:50) p3tr: { "tx" : "0200000000010125744673...", "txid" : "ac97847d5a070..." }

Looking at the lnd source, it ranges up to 2 weeks depending on the amount in the channel.  We don't allow more than 3 days, should we change default?

**Comment by practicalswift** [comment]
I'm in favor of changing the `c-lightning` default to allow for `lnd`'s `to_self_delay` defaults.

From BOLT-02:

> The receiving node MUST fail the channel if:
> * `to_self_delay` is unreasonably large.

Two weeks does not seem "unreasonably large" :-)

**Comment by cdecker** [comment]
I think 2 weeks is absolutely unreasonable, so that's a no from me.

**Comment by ZmnSCPxj** [comment]
Agree with @cdecker here.  3 days seems eminently reasonable, 4 or 5 days maybe reasonable, possibly a week, but two weeks? It seems unreasonable.

**Comment by practicalswift** [comment]
Seems like consensus NACK then :-)

Can we get `lnd` to change the defaults? Having `lnd` and `c-lightning` use incompatible defaults seems very unfortunate and is a recipe for a bad user-experience.

**Comment by aantonop** [comment]
I've submitted a PR to bring the LND max down to 3 days (the max accepted by c-lightning). I think there's probably a middle ground (4-5 days?) that could be met, but for now this is an interoperability problem that's affecting channel creation. 

https://github.com/lightningnetwork/lnd/pull/788

Perhaps the c-lightning max to_self_delay can be raised - if 4-5 days is considered "reasonable", even though 2 weeks isn't? I like the idea of having a bit more time than 3 days for a large capacity channel.

**Comment by ajtowns** [comment]
FWIW, I think it's probably reasonable to be able to setup channels such that you can safely have your node disconnected/non-functional/disabled for Easter break, which in Australia might last from Thursday night to Tuesday morning, which is about 112h or 672 blocks (5pm Thursday to 9am Tuesday). Letting the user set a maximum of up to a week/1008 blocks seems like a pretty reasonable "round" number there, maybe.

**Comment by ZmnSCPxj** [comment]
I am fine with 1 week = 1008 blocks; uncomfortably high, but still within the realm of (barely) reasonable.

**Comment by Ulmo** [comment]
The issue for me is that I can sometimes maintain my nodes on a Friday or Saturday, have a week full of overtime, then come back Sunday, so that's 9 days right there, and if I happened to be efficient Friday but slow Sunday, it could be 10 days.  Since I try to always put around 0.1BTC in every channel that I think is "important", to me, it makes sense I wouldn't want to risk that much to just being tired.  I know if you are trying to turn Lightning Network in a professional-only system, that isn't a good metric, but I'm talking about what one person can do on their own in a normal work week environment.

Another consideration is that some vacations last about 5 days, and there's two days packing and three days unpacking, so that's 10 days also.

I'm in favor of the limit being 11 days, which is a "week with personal delays", but under two weeks.  Of course, the main issue with that is that you would have to plan to close big channels before the long weeks; each person would have to consider their situaton.  For instance, right now, I could probably get away with 9 days; a week + a weekend (Saturday through Sunday, which is 8 days, but like I said, I could have an efficient Saturday but a slow Sunday and that goes to the 9th day).

**Comment by ZmnSCPxj** [comment]
How would you pay for anything on your vacation if your LN node is turned off? Everybody knows that nobody will accept anything other than Bitcoin, haha.

More seriously, you do bring up a good point. For myself, I conceptualize that, since LN requires 24/7 operation for optimal operation, we will at some point have high-availability high-uptime permanently-connected devices at home that will protect our funds and serve as an LN node; to spend, we will contact that home device with a mobile device.  But perhaps that would be quite a long way away.

**Comment by agustinf** [comment]
Let's not just say "leave it to the user to decide", that's always the easy way out for developers, but usability is all about proposing good default. Otherwise we are leaving this "un-interoperable by default".

**Comment by Ulmo** [comment]
Where is this set?  I want to change it.

**Comment by Ulmo** [comment]
As AAnton said on the LND side, please update "lightningd --help" where the text says:

        --max-locktime-blocks <arg>    Maximum blocks a peer can lock up our funds (default: 432)

to include the string "to_self_delay", so that users looking for the error string can find the solution.
