### ISSUE TITLE
"CLOSINGD_SIGEXCHANGE" over a week

### ISSUE THREAD

**Issue by FeedTheWeb** [ElementsProject/lightning#1199]
### Issue and Steps to Reproduce

Channel is stuck on "CLOSINGD_SIGEXCHANGE" for over a week now. 
How can I force close this channel, or re-negotiate some closing fee ? 

```
  "peers": [
    {
      "id": "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134",
      "connected": true,
      "netaddr": [
        "34.250.234.192:9735"
      ],
      "alias": "endurance",
      "color": "ffff00",
      "channels": [
        {
          "state": "CLOSINGD_SIGEXCHANGE",
          "owner": "lightning_closingd",
          "short_channel_id": "1286644:141:0",
          "funding_txid": "93142afdf95e329364bd06c0fe8c230cd72207d0de9031dff6367b0337209688",
          "msatoshi_to_us": 142879290,
          "msatoshi_total": 150000000,
          "dust_limit_satoshis": 546,
          "max_htlc_value_in_flight_msat": 18446744073709552000,
          "channel_reserve_satoshis": 0,
          "htlc_minimum_msat": 0,
          "to_self_delay": 2,
          "max_accepted_htlcs": 483,
          "status": [
            "CLOSINGD_SIGEXCHANGE:Negotiating closing fee between 191 and 289 satoshi (ideal 217)",
            "CLOSINGD_SIGEXCHANGE:Waiting for another closing fee offer: ours was 217 satoshi, theirs was 242 satoshi,"
          ]
        }
      ]
    },

```

### `getinfo` output

```
{
  "id": "03ef12386d4f89b8bc83e82bbad02579a54e42bd1e22cfd81bd2ca94124ec65792",
  ],
  "version": "v0.5.2-2016-11-21-2213-g8e8d7c2",
  "blockheight": 1287934,
  "network": "testnet"
}
```

**Comment by cdecker** [comment]
I would say the closing fee negotiation got stuck waiting for another offer by the remote peer. You could either restart the daemon, hoping that the negotiation restarts upon reconnecting and settles, or you could `dev-fail` the channel, forcing a unilateral close.

**Comment by FeedTheWeb** [comment]
Tried restarting, but nothing happened after that.
Then `dev-fail` , but it is not closing... still `CLOSINGD_SIGEXCHANGE`
the status message changed a bit, but it still seems to be stuck:
```
          "status": [
            "CLOSINGD_SIGEXCHANGE:Negotiating closing fee between 191 and 289 satoshi (ideal 217)",
            "CLOSINGD_SIGEXCHANGE:Waiting for their initial closing fee offer: ours was 217 satoshi"
          ]

```

**Comment by FeedTheWeb** [comment]
Something seems to happen now.   
(I'll update this when it finishes)

```
      "connected": false,
      "channels": [
        {
          "state": "ONCHAIN",
...
          "status": [
            "CLOSINGD_SIGEXCHANGE:Negotiating closing fee between 191 and 289 satoshi (ideal 217)",
            "ONCHAIN:Tracking mutual close transaction",
            "ONCHAIN:All outputs resolved: waiting 71 more blocks before forgetting channel"
          ]

```

**Comment by cdecker** [comment]
56 confirmations so far, should return your funds after 144 (could be more though). The recently added #1202 should show you exactly how long you'll have to wait.

**Comment by FeedTheWeb** [comment]
ok, channel is closed..

still, it would be good to have a option to re-start the negotiation.

**Comment by ZmnSCPxj** [comment]
If other side will not continue the negotiation, nothing we can do.  Only alternative, is to do a unilateral close.  Although, I suppose, this is possibility.

**Comment by CubicEarth** [comment]
Perhaps there should be a way to manually accept the other peers offer?
In the stalemate I am currently facing, I would happily pay 300 sats extra rather than wait for 144 blocks.

**Comment by ZmnSCPxj** [comment]
It is a bit difficult actually.  The specification specifies that we finish the negotiation by one side repeating the same fee that the other side last said.  If we are stuck waiting on the other side, we cannot know if the problem is that they sent something and we lost it somehow (in which case, how can we learn what to repeat back to it?) or if they have a bug and they stopped sending the close to us (in which case repeating back the last thing they said might not continue the sequence anyway).

Also, see issue #1361 which is a spec noncompliance bug we have, so you might have tripped over this if you were using a channel with a compliant non-c-lightning implementation (if we were funder, we would send a proposal, then expect the other side to send to send two proposals instead of one before sending our own proposal again, ha; you will not see this with channels with fellow c-lightning implementations as if we are fundee, we will send two proposals at that point too).  We should get #1362 merged in to fix this noncompliance.
