### ISSUE TITLE
HTLC value too large: 0

### ISSUE THREAD

**Issue by redstorm1** [ElementsProject/lightning#1213]
### Issue and Steps to Reproduce
connect a channel then try and fund the channel. fails with HTLC value too large: 0

./lightning-cli fundchannel 02faf31d72590671bdcbd65cef587e1eb35656e65aa27c24250ee2056c23c82a26 500000
{ "code" : -1, "message" : "received ERROR channel bc09665bd65f193992541ca7f3bb98ca2a161f97f77bcdc273755a8d4ba3f3ba: Unacceptable channel constraints: minimum HTLC value is too large: 0" }

### `getinfo` output
{ "id" : "0392419c02fbca83ae8d541cd2f48b662b2238ed8e1e92a93547c23ba32f0d64c6", "port" : 9735, "address" :
        [
                { "type" : "ipv4", "address" : "203.86.204.88", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2290-g640ff4b", "blockheight" : 1288129, "network" : "testnet" }

**Comment by rustyrussell** [comment]
This is an error from lnd, so I opened a PR there too...

**Comment by ZmnSCPxj** [comment]
This is an acknowledged lnd bug: https://github.com/lightningnetwork/lnd/pull/779 https://github.com/cdecker/lightning-integration/issues/11

Marking as `wontfix` as we cannot fix on our side.

**Comment by ZmnSCPxj** [comment]
The error has been fixed on lnd side.  However the node you are connecting might not be up-to-date.  If you know the owner of the node personally, ask them to update their lnd.  Otherwise, sorry, but, you will have to find another node to channel to; there is nothing we can fix in c-lightning side to make old lnd behave correctly.
