### ISSUE TITLE
"Funding transaction spent" shouldn't be a connection-level error

### ISSUE THREAD

**Issue by pm47** [ElementsProject/lightning#1229]
The `error` message for "Funding transaction spent" has `channel_id`=0 which means that all channels associated to the node will get closed. I think this should be a channel-level error.

Unfortunately I can't tell exactly what version of c-lightning does that or if it has been fixed since.

**Comment by ZmnSCPxj** [comment]
It has not been fixed: there is code that always uses "all channels" regardless. https://github.com/ElementsProject/lightning/blob/4ffd5e213b9099a676cf417c2a00d940cedd7e80/lightningd/channel.c#L307-L317

Note that the above code already has an in-memory `struct channel` as argument it could have referred to in order to get the correct channel id, but it does not use it and instead always fails all.

Arguably the code above should be using `towire_errorfmt` which will use the channel id from the given `struct channel`

**Comment by pm47** [comment]
> Arguably the code above should be using towire_errorfmt which will use the channel id from the given struct channel

Surely it doesn't really matter as long as c-lightning doesn't support channel multiplexing over a single connection, but I think the "spririt" of the BOLT 2 is that `error` messages should still be as specific as possible:

`The channel is referred to by channel_id, unless channel_id is 0 (i.e. all bytes are 0), in which case it refers to all channels.`  ([BOLT 2](https://github.com/lightningnetwork/lightning-rfc/blob/master/01-messaging.md#requirements-1))

**Comment by ZmnSCPxj** [comment]
No, but I believe there are vague plans to eventually allow multiple channels per peer eventually, as otherwise some changes (moving channel-related peer state into a `channels` array in JSON-RPC, for example) that would make no sense without such plans.  So better to make `error` specific to channel.
