### ISSUE TITLE
Bitcoin's Highly-Anticipated Lightning Network Goes Live

### ISSUE THREAD

**Issue by realcryptominer** [ElementsProject/lightning#1232]
Ok So here is a great news...

https://www.forbes.com/sites/ktorpey/2018/03/15/bitcoins-highly-anticipated-lightning-network-goes-live-as-startup-raises-2-5-million/

Now, I am already running lightning testnet on Linux Ubuntu 17.10 VPS since last more than a month and successfully buying starblocks coffee.

As far as my understanding to run bitcoin testnet and lightning testnet I needed to run following two commands.

bitcoind -testnet -daemon

lightningd/lightningd --network=testnet --log-level=debug

--------------

Now if I want to run bitcoin main blockchain and lightning node that went live on 15th March, I need to run following two commands instead of the above. [Of course, I will remove all the previous installation and do a fresh start on my Linux Ubuntu VPS!]

bitcoind -daemon

lightningd/lightningd --network=bitcoin --log-level=debug

---------------

Is this right?
Correct me if I am wrong?

Or Do I need to do something else for the lightning mainnet?

Kindly help!

**Comment by ZmnSCPxj** [comment]
Since testnet coins are generally nonvaluable, yes, just delete the entire lightningdir (usually `$HOME/.lightning/`).

But note that the announcement is based on [lnd](https://github.com/lightningnetwork/lnd) making a new release, which they claim is mainnet-ready.  For c-lightning (another project that works with lnd but is separate from it), notice that there is a line in our `README.md` file which says:

> __it should not be used for real funds__

**Comment by realcryptominer** [comment]
Ouch.....
I am biting my nails now.... 

- Yes, testnet coins are nonvaluable so formating everything and starting from scratch is a way to go... Agree...

- Ahhh... I see... so lnd and c-lightning are different things. And that is what I was missing....

These media guys are idiots... They should at least recognize c-lightning along with lnd. Because it is creating lots of confusions...

By the way, 

1) When will C-lightning will be on mainnet like lnd? I want to use C-lightning as a mainnet.

2) Here is my steps to install C-Lightning mainnet. Are they correct?

https://pastebin.com/wRtS6xTR

And in future will I have to do any additional changes in the above steps?

**Comment by cdecker** [comment]
c-lightning can indeed be used on mainnet, though the usual caution has to be taken since this is unreleased software that still may have bugs. That being said, we have been running it rather successfully ever since the Blockstream Store launched back in January, and aside from the odd usability issue or the daemon getting stuck, there have been no major issues.

So if you want to use c-lightning on mainnet, you can do it, just don't put your life-savings in it just yet :wink:

**Comment by cdecker** [comment]
As for your instructions they seem to be correct :smiley:

**Comment by cdecker** [comment]
btw this isn't really suited for the issue tracker, IRC or the c-lightning mailing list may be a better place to ask :-)

**Comment by ZmnSCPxj** [comment]
1. Maybe after 0.7?  Note that our next release is 0.6, which is somewhat of a feature freeze, maybe a few new features will be added in 0.6.1, then for 0.7 we will be in test test test mode, so hopefully (!!!!!!) 0.7 we might have a chance to maybe consider the possibility of potentially removing the scary "__it should not be used for real funds__" string.
2.  They seem broadly correct, yes.

As @cdecker says, Blockstream has been using c-lightning for a month or two now to sell promotional stickers and shirts.  Whether or not you consider this as a signal to use c-lightning for your "serious" money or not is up to you; Blockstream is not in the business of selling stickers and shirts, and presumably has some other income stream (e.g. mind-controlling Bitcoin developers using fluoride in the tap water, selling out to the evil banks, etc.) to keep it afloat in case of a massive problem with c-lightning.

**Comment by Ulmo** [comment]
My summary answer to the original question is that the announcement that "Lightning is live on Bitcoin" is outdated, since C-Lightning got there first, but that LND leapfrogged C-Lightning's readiness level with LND's announcement that their Beta is out and nominally considered more acceptable for real funds risks than C-Lightning, however, so far, I have not lost considerable funds to my knowledge using C-Lightning on Mainnet in its dev alpha stages on two nodes in the last many weeks (has it been months yet?), although it did require some internal database probing and bug fixes along the way for that to be true.

**Comment by cdecker** [comment]
> has it been months yet?

It has indeed been months: your [first post on this repo](https://github.com/ElementsProject/lightning/issues/701#issue-290287462) is about 2 months old by now :wink:
