### ISSUE TITLE
#1290 issue still happening. Owning subdaemon lightning_onchaind died

### ISSUE THREAD

**Issue by redstorm1** [ElementsProject/lightning#1392]
### Issue and Steps to Reproduce
hard to say how to reproduce.
Now have 2 channels #4 and #29 that report Owning subdaemon lightning_onchaind died

### `getinfo` output
{
  "id": "0392419c02fbca83ae8d541cd2f48b662b2238ed8e1e92a93547c23ba32f0d64c6",
  "port": 9735,
  "address": [
    {
      "type": "ipv4",
      "address": "203.86.204.88",
      "port": 9735
    }
  ],
  "version": "v0.5.2-2016-11-21-2529-g774af5f",
  "blockheight": 1293459,
  "network": "testnet"
}

http://paste.ubuntu.com/p/nbjbDqDWBV/

lightning-cli listpeers 03cc69575c7c22ec4a30a282f28a7e1cd3eb6fbfba9206738b65608092a6a5cb22 debug
http://paste.ubuntu.com/p/VdkvTvCrkS/

lightning-cli listpeers 02ed613f005d8dae7e7211d628c63c963c4df35d9b56afabac39fefe9e90a89c75 debug | pastebinit

http://paste.ubuntu.com/p/VHT7WrbR93/

**Comment by ZmnSCPxj** [comment]
Peer is disconnecting. If the peer is stopped, it will disconnect and lightning_channeld will exit since there is nothing for it to do. There is nothing we can actually do here, we cannot force the peer to come online if it wants to go offline.

Log you posted showed `lightning_channeld` not `lightning_onchaind`, this is normal behavior.

Alternatively maybe there is a problem in your network connectivity.

**Comment by redstorm1** [comment]
Ok if normal ill close
