### ISSUE TITLE
API change: `close` accept channel ID

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#1394]
In the (far) future we probably want to support multiple channels per peer, despite this being suboptimal for network health.  Otherwise what is point of making `channels` an array in `listpeers`?

In line with that, we should probably have `close` accept a channel ID rather than peer ID.  And, we should probably transition to this earlier rather than later.

For transitioning:

1.  Support peer ID, OR channel ID.  We can differentiate by size: peer ID is 33 bytes, channel ID is 32 bytes (maybe even support short channel ID "xx:y:z")
2.  If peer ID specified, only valid if peer has one channel exactly.  If more than one channel, error and tell user that multiple channel ID exists that can be closed.

**Comment by cdecker** [comment]
We are currently limited to a single active channel, i.e., not `onchaind` or `closingd`, per peer. Not sure if we want to lift this limitation any time soon since it is already possible to have channels open back-to-back, with only minor downtime.

But this improvement is a good idea either way.

**Comment by ZmnSCPxj** [comment]
A wrinkle here is that we support closing uncommitted channels.  Uncommitted channels do not have a stable funding transaction yet, and so do not have a channel ID.  So I suppose the best thing to do is to retain support for peer id indefinitely, so that we can close uncommitted channels. Hmm.

**Comment by jsarenik** [comment]
Just a summary as a preparation for me to understand what's going on here in order to make sure the documentation is ready for the release:

The related documentation is in file [`doc/lightning-close.7.txt`](https://github.com/ElementsProject/lightning/blob/52c243852ea36b2053bb08879e0293321b3a8380/doc/lightning-close.7.txt).

The related source is in [`lightningd/peer_control.c`](https://github.com/ElementsProject/lightning/blob/435e85a5b295076764f94959b7c65152658069eb/lightningd/peer_control.c). I suppose that `onchaind/onchain.c` is not related.

When the source is changed, the tests in `tests/test_lightning.py` need to be updated as well. Please correct me if I'm wrong or missed out something important.

**Comment by ZmnSCPxj** [comment]
>The related documentation is in file [`doc/lightning-close.7.txt`](https://github.com/ElementsProject/lightning/blob/52c243852ea36b2053bb08879e0293321b3a8380/doc/lightning-close.7.txt).

Yes

>The related source is in [`lightningd/peer_control.c`](https://github.com/ElementsProject/lightning/blob/435e85a5b295076764f94959b7c65152658069eb/lightningd/peer_control.c). I suppose that `onchaind/onchain.c` is not related.

Yes and Yes.

>When the source is changed, the tests in `tests/test_lightning.py` need to be updated as well.

If we retain the peer-id option for back-compatibility, no, but it would be good to change some (or most) of the `close` attempts to check this.
