### ISSUE TITLE
parameters for invoice generation 

### ISSUE THREAD

**Issue by fixone** [ElementsProject/lightning#1401]
the man page for ```invoice``` mentions a ```fallbacks``` parameter as
```or more fallback addresses to include in the invoice```, however it's not clear in my view what kind of addresses does it refer to. Is it my peer address (like IP:port) or something else?
Also on the subject of the ```invoice```: is there a way for me as the creator of the invoice to specify the preimage that will get passed to the payer upon successful payment? I'm thinking along the ways of a service that, provides some decryption keys or other 256bit information (say for viewing a restricted content) and would use this preimage to pass it on, without the need for a separate communication channel

**Comment by ZmnSCPxj** [comment]
Bitcoin onchain addresses, either Base58Check or bech32.

>is there a way for me as the creator of the invoice to specify the preimage that will get passed to the payer upon successful payment? 

Currently none, but that is actually a good idea.  Let me create an issue to track that.

**Comment by ZmnSCPxj** [comment]
Yes. As mentioned, however, we currently do not support using the fallback addresses. It is not certain what UI designers would prefer `pay` to behave in this case, so we are somewhat being lazy and waiting for somebody to explicitly request that paying to fallback addresses be implemented. The issue is that Lightning payments usually become final more quickly than onchain payments, and onchain payments may be delayed for days or weeks before getting confirmed or before they get dropped from most mempools, not to mention details like RBF and chain reorganization.

**Comment by ZmnSCPxj** [comment]
@fixone has your question been satisfactorily been answered?

**Comment by fixone** [comment]
yes, nothing more on this topic, thanks
