### ISSUE TITLE
Make `invoice` idempotent

### ISSUE THREAD

**Issue by RHavar** [ElementsProject/lightning#1411]
I really like the c-lightning API yall have made, it's definitely the best designed one for a merchant AFAICT. 

However one possible oversight from the `invoice` command:

> On failure, an error is returned and no invoice is created.  If the
> lightning process fails before responding, the caller should use
> lightning-listinvoice(7) to query whether this invoice was created or not.

imo is too complex and not realistic to expect of callers.

I think the API would be greatly improved by making the invoice command (optionally?) idempotent. The most obvious way of doing so would be a client-side generated uuid for a `invoice-id` or something, and if you use the same uuid with same details it just returns the invoice.

You could also overload providing the same `preimage` to achieve this

**Comment by ZmnSCPxj** [comment]
We have a uniqueness constraint on `label`, so we could use that instead of adding an `invoice-id` UUID that is client generated.  In essence, caller would generate some UUID and use it in `label` parameter.

`preimage` is an advanced feature and should be discouraged from usage. In addition, we do not expose `preimage`.

**Comment by RHavar** [comment]
> We have a uniqueness constraint on label, so we could use that instead of adding an invoice-id UUID that is client generated. In essence, caller would generate some UUID and use it in label parameter.

Ahh, sorry. Yeah that looks perfect

> A difficulty with idempotency is that we record expiry as an absolute time. 

I can see a few possibilities:
a) The caller provides the absolute time. Then you check for a match
b) You also store the relative time (of the call), and check for a match
c)  You just update the time if the invoice already exists

a and b seems the most conceptually clean, but perhaps c is the most practical

> What if the caller specifies expiry=3600, then 3598 seconds later, specifies expiry=3600 again? Should we reset the expiry time?

 At least for me, the only reason I'd be making the same call twice is because I wasn't sure of the status of the first call  (e.g. perhaps a network interruption), so it'd definitely be just most useful for me the expiry is reset.

Although perhaps it complicates things if the invoice can mutate like that, in which case I really doubt it's worth the trouble.

And likewise I'm not sure if it should revive an expired invoice or not, but I'd be guided but what has the cleanest implementation and just document it.

**Comment by rustyrussell** [comment]
OK, to be clear, the documented "what happens if this call crashes" is not the normal case.  If the call fails or succeeds, you know what to do.

The correct fix is to have an explicit return error which means "this is a duplicate label".  That's actually the useful parameter: the rest isn't.  You might vary the amount because you're using a dynamic exchange rate.  You might not vary the amount for different invoices because it's the same item.  The description might not be the same between calls because you might customize it to contain the caller's IP address or use their preferred language, or whatever.  Whatever it is, you can query the duplicate to make sure it's the right one if you want.
