### ISSUE TITLE
If the counterparty proposes fees outside of our acceptable range we should accept and collaboratively close

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#1443]
### Issue and Steps to Reproduce
To reduce the number of unilateral closes we should accept a fee update that is outside of our range, but then close the channel collaboratively instead of slamming the door (paying the on-chain fees and having to wait an eternity).

**Comment by ZmnSCPxj** [comment]
Should we, though?  Suppose it drops the fee to < 253 leading to a unbroadcastable close, or it inflates the fee so much that it spends 2mBTC of a 10mBTC channel on a unilateral close.  The point is not to accept the fee and use the current commitment transaction that we found acceptable before.

However, the closing process does have a fee negotiation.  I just wonder what our behavior will be if the funder suddenly suggests a feerate of 1sat/ksipa and we accept.  Given BOLT 2:

> MUST set `fee_satoshis` less than or equal to the base fee of the final commitment transaction, as calculated in [BOLT #3](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#fee-calculation).

If the funder provides a feerate of 1sat/ksipa, then the commitment transaction will have a ridiculously low fee, and a reasonable closing transaction may be larger than that feerate.

**Comment by ZmnSCPxj** [comment]
Maybe better would be to have a "soft limit" and a "hard limit"?

If the soft limit is violated but the hard limit is not, then we accept the `update_fee` but do a `shutdown` afterwards.

If the hard limit is violated, we `error` and drop the commitment onchain.

Use the current limits as the soft limit.

Use >= 250 as the lower end of the hard limit, and maybe 2 or 3 or 5 times the soft limit max as the upper end of the hard limit..?

**Comment by ZmnSCPxj** [comment]
No, still not good maybe....? One way for the channel funder to try to exploit this would be to:

1.  Wait for a high feerate time (e.g. 25000 sat/ksipa).
2.  Send a high-value HTLC out in exchange for expensive off-Lightning value, one with a low `cltv_delta` total.
3.  Slam the feerate to the minimum acceptable feerate that will still not `error` (e.g. 253 sat/ksipa).
4.  Sign the commitment transactions at that feerate and have the victim give the revocation key to the old 25000 sat/ksipa commitment tx to you.
5.  After `shutdown`, mess with the closing negotiation (i.e. go even lower than 253 sat/ksipa) so that the victim is forced to drop its latest commitment (the one at 253 sat/ksipa and which has no chance of getting confirmed during the high feerate time) onchain.
6.  Wait for the high-value HTLC to time out, then claim it using the HTLC-timeout transaction, and attach further claiming transaction with high onchain fees to trigger CPFP and get that branch of the HTLC confirmed.

**Comment by ZmnSCPxj** [comment]
Okay, here is a more refined version of the above attack.

I control two nodes, the attacker node A and the beneficiary node B.  There already exists a channel between the victim node V and the beneficiary node B, with most of the channel funds there in favor of V.  The actions below are primarily performed by A:

1.  Wait for high feerate time.
2.  Fund a channel between A and V.
3.  When it confirms, send a payment on route A->V->B.  On B, do ***not*** claim the funds immediately.
4.  Send a ridiculously low `update_fee` (253) from A to V.  V will freak out since it is outside the acceptable range, but will still accept it and send a `shutdown` to A.
5.  The closing cannot continue while HTLCs are pending, and B is not yet claiming it, so the HTLC on the A<->V channel still blocks closing.
6.  Send a `commitment_signed` from A to V.  V will respond with `revoke_and_ack`, revoking their previous high-feerate commitment for a low-feerate commitment.
7.  Tickle a unilateral shutdown from V: send an `error` from A to V.  V will drop its low-feerate commitment onchain, where due to high current feerates has no chance of being confirmed within the timelock window.
8.  Have B claim its payment from V.  V now has the preimage, but it already dropped the channel with A onchain and can no longer claim it easily except onchain.
9.  When the timeout ends, attach a child transaction on the HTLC outpoint with high feerate to CPFP the timeout branch to our side.  Note that V cannot use the pre-signed HTLC-success transaction with a low feerate to RBF that away, since the HTLC is on the commitment on their side and they are encumbered with a CSV (and thus unable to CPFP) but we are not.
10. Have B spend all its funds for offLightning value, start up a new attacker A, repeat until V has no more money on its *other* channels.

**Comment by ZmnSCPxj** [comment]
One thing we can do to prevent the above attack is to reject routing attempts over channels that have violated the feerange we accept, but we need to have a "quick" routing rejection method; BOLT2 prevents this:

> * until the corresponding HTLC is irrevocably committed in both sides' commitment transactions: 
>   * MUST NOT send an `update_fulfill_htlc`, `update_fail_htlc`, or `update_fail_malformed_htlc`.

The only "quick" rejection of HTLCs that have not been committed to (which is needed since committing to the ridiculously low fee is what the victim wants to avoid!) is to `error`.
