### ISSUE TITLE
mass closure again

### ISSUE THREAD

**Issue by robtex** [ElementsProject/lightning#1529]
```2018-05-27 10:56:45.762 [INF] CRTR: Block 000000000000000000391f3392faf6b5a9cb720c23dc502e6bdafcbab8c5cae3 (height=524634) closed 203 channels```

I suspect this is yet another issue with disagreement of fees, and c-lightning decides to close the channels down.
It's far too trigger happy. Can't it solve it another way? like just start a timer and if it still disagrees after X blocks, *then* it can [preferably cooperatively] close it.

We are ending up with two lightning networks now, if channels between lnd and clightning can't be stable. It will certainly hurt routing a lot. We old guys remember when the same thing happened to Internet. Wasn't pretty.

Thanks in advance

**Comment by ZmnSCPxj** [comment]
Delaying to do a cooperative close on a bad feerate is attackable: https://github.com/ElementsProject/lightning/issues/1443#issuecomment-385541379 (although it is possible the attack scenario is unfeasible)

What exactly is the fee disagreement?  If the lnd side is proposing a fee of 250 sat/ksipa then c-lightning will never accept that since bitcoind will never accept that either: https://github.com/ElementsProject/lightning/pull/1251 .  See also Eclair issue, which will also be fixed similarly (i.e. impose 253 sat/ksipa minimum): https://github.com/ACINQ/eclair/issues/602

**Comment by cdecker** [comment]
The fee smoothing implemented in #1650 has reduced this issue massively. In the long term we will remove fee commitments from the protocol altogether, finally removing this source of disagreement.
