### ISSUE TITLE
Clean up corrupted channels

### ISSUE THREAD

**Issue by pooleja** [ElementsProject/lightning#1571]
### Issue and Steps to Reproduce
My node seems to have gotten into a state where there are many channels in the state `CHANNELD_AWAITING_LOCKIN`.  The associated funding txids were never broadcast.

This is a pretty old node that has been running and updated multiple times since Jan.

Example
```
{
  "peers": [
    {
      "id": "02a2275465cc4dd1fbe2891b746943fa966dbf0e9d0fda09e6039efccdf104295f",
      "connected": false,
      "channels": [
        {
          "state": "CHANNELD_AWAITING_LOCKIN",
          "channel_id": "0d7036566b470410b0af492b4ffa71f131964b81bf919f251727dc33a784ed4a",
          "funding_txid": "4aed84a733dc2717259f91bf814b9631f171fa4f2b49afb01004476b5636700d",
          "msatoshi_to_us": 222222000,
          "msatoshi_to_us_min": 222222000,
          "msatoshi_to_us_max": 222222000,
          "msatoshi_total": 222222000,
          "dust_limit_satoshis": 546,
          "max_htlc_value_in_flight_msat": 18446744073709551615,
          "their_channel_reserve_satoshis": 0,
          "our_channel_reserve_satoshis": 2222,
          "channel_reserve_satoshis": 0,
          "spendable_msatoshi": 220000000,
          "htlc_minimum_msat": 0,
          "their_to_self_delay": 144,
          "our_to_self_delay": 144,
          "to_self_delay": 144,
          "max_accepted_htlcs": 483,
          "status": [
          ],
          "in_payments_offered": 0,
          "in_msatoshi_offered": 0,
          "in_payments_fulfilled": 0,
          "in_msatoshi_fulfilled": 0,
          "out_payments_offered": 0,
          "out_msatoshi_offered": 0,
          "out_payments_fulfilled": 0,
          "out_msatoshi_fulfilled": 0
        }
      ]
    }
  ]
}
```

What is the protocol for closing these out and removing the channels?  If I try to manually force close them, it will send a closing transaction but it is never broadcast either and the channel goes into `CHANNELD_SHUTTING_DOWN`.

Example
```
{
  "peers": [
    {
      "id": "036eab489338fb7ab7c4f0e8734d37a7d270a1c4d7b62a0b5286235aad580b9a91",
      "connected": false,
      "channels": [
        {
          "state": "CHANNELD_SHUTTING_DOWN",
          "channel_id": "9f1113754d4e100d416630612417efbaf3a56982513254aa43354d6dac7fd625",
          "funding_txid": "25d67fac6d4d3543aa5432518269a5f3baef1724613066410d104e4d7513119f",
          "msatoshi_to_us": 200000000,
          "msatoshi_to_us_min": 200000000,
          "msatoshi_to_us_max": 200000000,
          "msatoshi_total": 200000000,
          "dust_limit_satoshis": 546,
          "max_htlc_value_in_flight_msat": 18446744073709551615,
          "their_channel_reserve_satoshis": 0,
          "our_channel_reserve_satoshis": 2000,
          "channel_reserve_satoshis": 0,
          "spendable_msatoshi": 198000000,
          "htlc_minimum_msat": 0,
          "their_to_self_delay": 144,
          "our_to_self_delay": 144,
          "to_self_delay": 144,
          "max_accepted_htlcs": 483,
          "status": [
            "Loaded from database"
          ],
          "in_payments_offered": 0,
          "in_msatoshi_offered": 0,
          "in_payments_fulfilled": 0,
          "in_msatoshi_fulfilled": 0,
          "out_payments_offered": 0,
          "out_msatoshi_offered": 0,
          "out_payments_fulfilled": 0,
          "out_msatoshi_fulfilled": 0
        }
      ]
    }
  ]
}
```

### `getinfo` output
```
{
  "id": "0235447c7485ff2b945bac5fbc366d54a87389bab8cacf1b64b26ec01e96bd165a",
  "port": 9735,
  "address": [
    {
      "type": "ipv4",
      "address": "34.236.113.58",
      "port": 9735
    }
  ],
  "binding": [
    {
      "type": "ipv4",
      "address": "10.0.2.181",
      "port": 9735
    }
  ],
  "version": "v0.5.2-2016-11-21-2867-g56046d4",
  "blockheight": 527196,
  "network": "bitcoin"
}
```

**Comment by Saibato** [comment]
@pooleja  
you can close them the "shut the door way"  by force. (force = true)
Please try   lightning-cli  close [id] true
ie `lightning-cli  close 036eab489338fb7ab7c4f0e8734d37a7d270a1c4d7b62a0b5286235aad580b9a91 true`

When it worked listpeers will hint you when your funds minus the onchain fee will be again in your wallet and when the channel will be forgot.

**Comment by pooleja** [comment]
@Saibato thanks for the feedback.  Yeah I can close them by force.  The problem is that I don't think they are closing cleanly since there is no funding tx.  It will just hang around in CHANNELD_SHUTTING_DOWN with no updates.

**Comment by Saibato** [comment]
@pooleja  yep! 
i test now, this can be tricky to get your channels from listpeers because this txid will never show up on chain.
and i assume your funds list by listfunds are alos still stuck in the channel  and not in the output list.

**Comment by Saibato** [comment]
@pooleja  

a. dev-rescan-outputs call  will give you always the funds back, but  sadly the peers still list. (-

b. one way is to rebroadcast the original raw funding tx to get the inputs. and then force close this costs onchan fees but woks.

but this will not happen in automatic 
if the node was once closed, then AFAICS the raw tx is almost lost when not logged. 

And why spend  onchain fees for that went wrong on the way to the other node. 
Since the tx  is not  onchain? 

So I think there is an issue here, that needs to be addressed   ;-)

**Comment by cdecker** [comment]
You can also attempt to broadcast the funding transactions, thus completing the setup and then close them normally. To get the raw transactions use this:

```
sqlite3 $HOME/lightningd.sqlite3 "select hex(rawtx) from transactions;"
```

Alternatively you can use `dev-rescan-outputs` to get the funds back into your wallet, and then `dev-forget-channel` to remove the entry in `listpeers` (you'll need to run in `DEVELOPER=1` mode for those to be available).

**Comment by Saibato** [comment]
@pooleja 

if you want to have the channels removed and don't care about the onchain fees (3 transactions), you can try
ie for the 036eab489338fb7ab7c4f0e8734d37a7d270a1c4d7b62a0b5286235aad580b9a91 peer
an
`sqlite3  $HOME/lightningd.sqlite3 "select hex(rawtx) from transactions where hex(id) = upper('9f1113754d4e100d416630612417efbaf3a56982513254aa43354d6dac7fd625')" `

as @cdecker suggested

that's a select to the channel id of your stucked peer

this gives you a raw tx to the funding which was hopefully saved in DB
you have to check what the sql returns.

Then you just need to rebroadcast by
`bitcoin-cli sendrawtransaction [output of the sqlite call] `  then wait for the next block that will trigger the magic

Next i will try to figure out to remove the channel with some additional sqlite call's without the need to broadcast anything and not to have to build a DEVELOPER build  @cdecker, @ZmnSCPxj and @rustyrussell might also have some view on this, as this has  to be fixed in code, just to automatic rebroadcast is expensive and to be forced to this is an attack vector.
So we have to find a method to remove a useless  unresposive channels in production mode, when we are sure it never opened anyway and all our funds are safe after it is in the CHANNELD_SHUTTING_DOWN state , maybe this is already addressed in an unmerged commit
 
So if you like to experiment with rebroadcast tx try this with one channel.
To save your bugs wait until i figure out the cheap way 

BTW:  ccan/config.h might not set DEVELOPER=1 if you do a make DEVELOPER=1 so you might have to edit ccan/config.h and set it to 1 before you build  to use the `dev-forget-channel`call which will remove your  channels.

**Comment by pooleja** [comment]
OK thanks @Saibato and @cdecker.  I will run the `dev-rescan-outputs` to recover any funds and then just forget the channels with `dev-forget-channel`.  I am not worried about creating/closing the channels on the chain.

**Comment by cdecker** [comment]
Keep us updated @pooleja and let us know if we can help
