### ISSUE TITLE
node_announcements are sent in format violation of BOLT 7

### ISSUE THREAD

**Issue by TheBlueMatt** [ElementsProject/lightning#1596]
BOLT 7 states:
"The origin node:...MUST NOT include more than one address descriptor of the same type.", however, c-lightning happily relays along such node announcements (see, eg, the node with alias "BallLightning" which has two IPv4 entires).

See-also: https://github.com/lightningnetwork/lnd/issues/1407

**Comment by Saibato** [comment]
Yes  they are sent multiple times.
ie.
`101837e42c7ee90acfacee9af7dfae04e80d72f2cebd9a6c3118e444c2ebfdd9dad7010604b474b7ff20966364b6f7cfbef206f95c27a4fe832ad24a0ac3411a3a100005b26543c03712b48f497d8769c0e7d3768b638dd7988f1e2931e5c290b0cf5d929fb432d6903712b535452414e4745524f5554452d000000000000000000000000000000000000000021017b7b7b862607020000000000000000000000000000000104d2017b7b7b012607`

@TheBlueMatt  made some changes in my branch, so that types are sent only once.  Maybe you want to have  a look 
https://github.com/ElementsProject/lightning/commit/0c71902e0dd1b24cdcfe73436deb31880c0c2e19
this could be a PR or maybe you have already your own  PR to fix to this 
@ZmnSCPxj , @rustyrussell , @cdecker  i did no PR because we are short before 0.6 so this can be fixed in 0.6.1 or?

**Comment by Saibato** [comment]
this was introduced after Milan  in: https://github.com/lightningnetwork/lightning-rfc/pull/60/files#diff-210f53c64b4a7ac8da48642029437668 

if one  bind's to 0.0.0.0  and has multiple ip  and .onion for the same ID i can't see, why this should not be changed in BOLT?
as high connectivity is always good, if more then one address is known, a failed connection can fast switch trough the possible address and type  and reconnect in a timely manner.
