### ISSUE TITLE
 Owning subdaemon lightning_channeld died

### ISSUE THREAD

**Issue by JohnnyBackflip** [ElementsProject/lightning#1604]
### Issue and Steps to Reproduce
The first issue that I have is that I bought a few blockachinos, but at some point, while paying, my internet connection died. Sine then I'm getting this error spam:
>2018-06-20T15:10:43.309Z lightningd(28449): lightning_channeld-0277622bf4c497475960bf91bd3c673a4cb4e9b589cebfde9700c197b3989cc1b8 chan #5: Peer connection lost
2018-06-20T15:10:43.309Z lightningd(28449): 0277622bf4c497475960bf91bd3c673a4cb4e9b589cebfde9700c197b3989cc1b8 chan #5: Peer transient failure in CHANNELD_NORMAL: lightning_channeld: Owning subdaemon lightning_channeld died (62208)

The second issue is that from now on every payment fails with this error:
>sudo lightning-cli pay lntb17u1pdj5m03pp50vc2uaz6zelyvmepww2s0kdn6mr6cnnxszj2seks2dr4zdhmurkqdpzxysy2umswfjhxum0yppk76twypgxzmnwvycqp24n5ksc4al5jeh2ht5vwaxrdkxmgmwjzmrnv66ddy2fs6k0pse7s9dm63fcc9vl4fmaee4yt6qtc24jtv8cv4uh5dx3xyclpmtttx4lspf6kgut
{ "code" : 205, "message" : "Could not find a route", "data" : 
{
  "getroute_tries": 2, 
  "sendpay_tries": 1, 
  "failures": [
    {
      "message": "Outgoing subdaemon died", 
      "type": "FAIL_PAYMENT_REPLY", 
      "erring_index": 0, 
      "failcode": 4103, 
      "erring_node": "02c1626677d61bf1217e2028372d90435046f44d93b133fa6d159dcf76ec8a2610", 
      "erring_channel": "1325887:148:1", 
      "route": [
        {
          "id": "0277622bf4c497475960bf91bd3c673a4cb4e9b589cebfde9700c197b3989cc1b8", 
          "channel": "1325887:148:1", 
          "msatoshi": 1703714, 
          "delay": 304
        }, 
        {
          "id": "03a0df42e93655311fee911f857a5cf1c6415f395f6396bb5ac756cbc6f3532601", 
          "channel": "1297420:79:1", 
          "msatoshi": 1702713, 
          "delay": 160
        }, 
        {
          "id": "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134", 
          "channel": "1293286:57:0", 
          "msatoshi": 1702695, 
          "delay": 154
        }, 
        {
          "id": "035b55e3e08538afeef6ff9804e3830293eec1c4a6a9570f1e96a478dad1c86fed", 
          "channel": "1289859:10:0", 
          "msatoshi": 1701525, 
          "delay": 10
        }
      ]
    }
  ]
} }

The third issue is that, before things started failing, I couldn't pay yalls articles because the routing fee, relative to the amount that I wanted to send, was too high. How do I increase the maximum value? If I want to do this using the "pay" command I can't set the maxfeepercent because the payment Link I'm using includes an msatoshi amount and it gives me the error that it can't set msatoshis if the msatoshi amount is already included in the bolt11 payment string.

### `getinfo` output
>sudo lightning-cli getinfo
{
  "id": "02c1626677d61bf1217e2028372d90435046f44d93b133fa6d159dcf76ec8a2610", 
  "port": 9735, 
  "address": [
  ], 
  "binding": [
    {
      "type": "ipv6", 
      "address": "::", 
      "port": 9735
    }
  ], 
  "version": "v0.6rc1", 
  "blockheight": 1325933, 
  "network": "testnet"
}

**Comment by cdecker** [comment]
Not really a support forum, but I'll answer these quickly:

1. The connection to the peer was lost (not surprising since you mention that you lost your network connection). That means that the `channeld` that was handling that connecton exited (which we log as it dying). That shouldn't alarm you, it's pretty normal, and `channeld` will come back once the connection is re-established.
2. That's not surprising, since your channel got disconnected, there's no way to send a payment over it. Try `lightning-cli connect 0277622bf4c497475960bf91bd3c673a4cb4e9b589cebfde9700c197b3989cc1b8` and it should re-establish the connection (`lightning-cli listpeers` should show that peer as being `"connected": true`).
3. You can use the key-value version of the `lightning-cli` to provide `maxfeepercent`, e.g., `lightning-cli pay -k bolt11=[bolt11-string]  maxfeepercent=3` to allow up to 3 percent transaction fee. This is limited to 0.5% by default, otherwise the retry mechanism would happily pay huge fees without you getting to stop it.

Hope this helps, and please close the issue if it does :wink:

**Comment by JohnnyBackflip** [comment]
Thanks a lot, this solved my issues. Where is the best place to ask qustions like this?
