### ISSUE TITLE
`hsmd` is not used in invoice payment

### ISSUE THREAD

**Issue by stepansnigirev** [ElementsProject/lightning#1632]
I believe `hsmd` should be the only process touching the secrets.

Currently `lightningd` never asks `hsmd` to sign the invoice. It uses instead it's internal `hsm_fd` secret that is copied from `hsmd` during init phase. `sign_invoice` method in `hsmd/hsm.c` is never called.

It asks `hsmd` when openning connection and funding channel, but not when paying invoice.

### lightningd is starting
```
main
main
new_client
handle_client
check_client_capabilities
init_hsm
maybe_create_new_hsm
load_hsm
populate_secretstuff
send_init_response
hsm_peer_secret_base
node_key
handle_client
check_client_capabilities
pass_client_hsmfd
new_client
handle_client
check_client_capabilities
handle_channel_update_sig
node_key
handle_client
check_client_capabilities
sign_node_announcement
node_key
handle_client
check_client_capabilities
handle_ecdh
node_key
handle_client
check_client_capabilities
pass_client_hsmfd
new_client
handle_client
check_client_capabilities
handle_channel_update_sig
node_key
handle_client
check_client_capabilities
handle_cannouncement_sig
node_key
handle_client
check_client_capabilities
handle_channel_update_sig
node_key
```

### Connecting to the node
```
handle_client
check_client_capabilities
handle_ecdh
node_key
```

### Funding channel
```
handle_client
check_client_capabilities
sign_funding_tx
bitcoin_pubkey
hsm_key_for_utxo
bitcoin_keypair
handle_client
check_client_capabilities
pass_client_hsmfd
new_client
```

### Paying invoice
```

```

As you can see, invoice is paid without any calls from `hsm.c`.

**Comment by cdecker** [comment]
Interesting, how did you generate those traces?

You had me worried for a second there, but I think I have an idea on what happens. Let me trace the JSON-RPC call through to the `hsmd` and back. On the master daemon's side we have 
```
json_invoice -> bolt11_encode -> hsm_sign_b11 -> towire_hsm_sign_invoice
```
At this point `hsm_sign_b11` creates a signature request (`hsm_sign_invoice` message) and synchronously sends it to `hsmd` using the `hsm_fd` (the client side of a `socketpair` that is used to talk to the `hsmd`). The `hsmd` then picks up the request and it follows this path:

```
handle_client -> sign_invoice -> towire_hsm_sign_invoice_reply
```

The reply is then passed back to the master using its end of the `socketpair` fd, and returns it. If you used `status_trace` for the above call traces, that's probably the reason why we aren't seeing `sign_invoice` in there: the master waits synchronously for a reply (discarding messages that are unexpected) and since `status_trace` are also just messages to the master they'll get discarded.

A simple test is that by crippling the `sign_invoice` function in `hsmd` to not return a reply will simply hang whenever we want to create an invoice.

**Comment by stepansnigirev** [comment]
Sorry, I mixed up the purpose of `sign_invoice`. It is indeed called when I am generating a new invoice.

What I am worried about is that hsm is not involved when I am **paying** the invoice.
I tried to pay to the same node several times several different invoices. When paying for the first time I see a bunch of function calls in hsm, I assume they are used for communication. But then, when I am actually paying invoices with `lightning-cli pay <bolt11>` there is nothing happening in the hsm.

This probably means that per-channel secrets are derived from hsm in the very beginning but then handled by the master deamon, not by the hsm. 

But is it the right behaviour? I would expect that **all** secrets should stay in hsm.

P.S. To trace what is happening in hsm I just modified `hsm.c` to write logs on every function call.

**Comment by cdecker** [comment]
No, the peer sending the invoice remembers all previous payment secrets and just short-circuits payments which it had already completed. This is to make the `pay` command as idempotent as possible. Also the payment secret is not stored in the HSM, but in the DB, since that needs not have access to the node secret.

The comment refers to the `peer_seed` which is used to encrypt the transport only if I'm not mistaken (checking now). That is securely derived from the `node_id` key using `hkdf`, and cannot be used to retrieve the original key. Specifically those keys cannot be used to sign invoices.

**Comment by cdecker** [comment]
I think this question was addressed, so I'll close this for now. Ping me if it wasn't addressed completely yet :wink:
