### ISSUE TITLE
Implement feerate smoothing

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#1637]
Instead of using the `estimatesmartfee` output directly we should be smoothing it to avoid hitting spikes when one side witnesses a spike but the other doesn't yet (due to polling differences). This should be just a simple EWMA that ensures slow convergence towards 90% of the estimate over say 5 minutes.

Fixes #750
Fixes #1622 
Partially solves #1529

**Comment by SimonVrouwe** [comment]
Sounds good, so you are proposing EWMA with coefficient alpha=0.9 and using the last 10 fee estimates (polled every 30s)?

**Comment by cdecker** [comment]
> Sounds good, so you are proposing EWMA with coefficient alpha=0.9 and
> using the last 10 fee estimates (polled every 30s)?

Since the polling interval can be configured we need to compute alpha as
a function of that, but yeah, that's the basic idea :-)

**Comment by SimonVrouwe** [comment]
Looking at some fee estimates from my own bitcoind, polled every 5s, the spikes in fee estimates are very sudden. Looking at data from past year taken from p2sh.info, the largest spike was last June 25th with a factor 11x increase. Now I am just learning about exponential weighing (hope did it correct) and also plotted EWMA with alpha=0.5 for both series, see lowest two charts that zooms in at the fee spike of June 25th.

The alpha=0.5 smooths the factor 11x to a factor 6x, which is what you want I guess. However these factors seems rather arbitrary. So I was wondering, why does [BOLT#2](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#updating-fees-update_fee) not define an upper limit on the change in `feerate_per_kw` signalled by an `update_fee` message?

![estimatesmartfee](https://user-images.githubusercontent.com/3152756/42126662-c93ee0a4-7c93-11e8-90f7-1359eb6d4d35.png)
![estimatesmartfee_spike_june25th](https://user-images.githubusercontent.com/3152756/42126665-d0c3517a-7c93-11e8-95a3-c34579ff479a.png)

**Comment by SimonVrouwe** [comment]
To further bury this thread with fancy charts, here is the same data from p2sh.info plotted as xy-scatter, where each point's x-coordinate is the (previous) value of a fee estimate and y-coordinate its change-ratio. Plot is zoomed in at lower fee values, it shows all the really large large spikes occur below 30 sat/vbyte. Also drawn are the currently used `max_fee_multiplier` and the dotted line is a possible variable `max_fee_multiplier`.

So maybe in addition to EWMA (or instead of?) one could make the `max_fee_multiplier` variable to allow larger fee spikes in the low-fee zone.

![scatter_prev_vs_dratio](https://user-images.githubusercontent.com/3152756/42133493-e9e06986-7d33-11e8-8c88-0278a48a5f83.png)
