### ISSUE TITLE
Why can't we send two commits in a row?

### ISSUE THREAD

**Issue by renepickhardt** [ElementsProject/lightning#1739]
not sure if the issue tracker is the right spot to ask my question:

https://github.com/ElementsProject/lightning/blob/f8fa4213f1721f3c5e1e0bd027fb7153d60986e5/channeld/channel.c#L1014

I am certainly still not understanding the code correctly but send_commit is only called once in 
https://github.com/ElementsProject/lightning/blob/231f14e645a303096c48c3cc2e6b89ac8d435d18/channeld/channel.c#L1125 why can't this happen twice in a row if the commitment_tx has been updated?

**Comment by rustyrussell** [comment]
We need to wait for the `revoke_and_ack` from the previous commitment message: both for simplicity, and because that contains the next per_commitment_point which we need to create the next commitment transaction.

**Comment by renepickhardt** [comment]
what exactly do you mean when you and @cdecker talk about `per_commitment_point` first I thought you would mean the `commitment_number` as in the state of the channel. But I am not sure weather you mean the derrivation of the keys for the `per-commitment-secret` that should be used for that channel update or even something else?

**Comment by jb55** [comment]
Rene Pickhardt <notifications@github.com> writes:
> not sure if the issue tracker is the right spot to ask my question

There's the c-lightning[1] and lightning-dev[2] mailing lists which
might be better for future questions

Also #c-lightning and #lightning-dev on freenode

[1] https://lists.ozlabs.org/listinfo/c-lightning
[2] https://lists.linuxfoundation.org/mailman/listinfo/lightning-dev

**Comment by cdecker** [comment]
@renepickhardt the commitment number simply count the number of commits we had so far in our channel, starting with commit 0 and then incrementing every time we perform a new commit. It is also encoded (in an obfuscated way) in the sequence number of the input, to hint which state we need to react should we see an old one on-chain.

The `per_commitment_point` is an EC point that is mixed into the commitment transaction in order to ensure every transaction being unique.
