### ISSUE TITLE
maxfeepercent should be ignored for small payments e.g. < 10 sat

### ISSUE THREAD

**Issue by SerafinTech** [ElementsProject/lightning#1746]
Can't send payments of 1 satoshi to some expermental online games
https://github.com/ElementsProject/lightning/blob/f85084948678177199cf44bdb9f991cfba3edf2a/lightningd/payalgo.c#L438
Change that to something like
`fee_too_high = (feepercent > pay->maxfeepercent && fee > minfee);`

Where `minfee` default to 2000 millisatoshi. Maybe even add minfee in pay RPC call.

Would help on sites requiring 1 sat for access to a game when everyone is defaulting to a min of 1 satoshi fee for HTLC even C-Lightning

Thanks

**Comment by renepickhardt** [comment]
I have a similar request on my desk (and didn't open an issue yet because I wanted to first check what the protocol says and if I could find something in the implementation). But since it fits to this request I will just add it here:

While testing c-lightning with lnd we had a paymentchannel in which we were playing ping pong with 1 satoshi. We found it confusing that without routing and staying in the payment channel the satoshi also added some minor fees. I think in general sending money to a channel partner should be free (unless it is send for routing).

**Comment by cdecker** [comment]
> While testing c-lightning with lnd we had a paymentchannel in which we were playing ping pong with 1 satoshi. We found it confusing that without routing and staying in the payment channel the satoshi also added some minor fees. I think in general sending money to a channel partner should be free (unless it is send for routing).

If we are directly connected, we could elide the amount randomization that is true, it was just easier to reuse the routing implementation rather than having this particular edgecase be treated differently. However (hopefully) that will only be the minority of cases. If you decide to implement it I'd be happy to review and merge it though :-)

**Comment by renepickhardt** [comment]
since I am still reading code it would probably ease up my life if you could give me one or two pointers. I might try to implement this, since it seems much easier than my other suggestion to get started.

**Comment by jonathancross** [comment]
👍 I myself have been confused by the issue while trying to experiment with small test payments to a directly connected peer. It's something we noobs try when first experimenting with LN.  I would say this also qualifies as a UX improvement.

**Comment by cdecker** [comment]
We should probably make this a configurable setting at some point, because otherwise people might be caught off-guard by sending `x*1sat`, but having something like `10*x*1sat` in total difference.
