### ISSUE TITLE
Question about outputs

### ISSUE THREAD

**Issue by valuead** [ElementsProject/lightning#1754]
Opened over 100 channels and all of them waiting and waiting. Now, I'm sitting and closing them by hand.
few questions;
1. I have tons of outputs. Is there a command that gets them (aggregates)  all in one?
2. Additionally Is there a command that closes all channels at once? 
3. Shouldn't be a function if node didn't upgrade to certain version - we should be automatically refuse to connect. I have a feeling a lot of nodes messing around and only 10% of my connections are successful 
Thanks

**Comment by cdecker** [comment]
1. You can use `newaddr` to get a new address, and then `withdraw [address] all` to consolidate your outputs, however it is discouraged since that performs on-chain transactions, and is not needed since we'll select coins for future transactions correctly.
2. The following one-liner closes all channels: `for i in $(lightning-cli listpeers | jq .peers[].id --raw-output); do lightning-cli close $i`
3. We can't a priori know the version of the protocol they run, but we'll disconnect if they require a newer feature, or aren't compatible with us.
