### ISSUE TITLE
Laptop "test nodes" offline for 24 hours; channels closing after opening laptop and checking VMs

### ISSUE THREAD

**Issue by jwaugh** [ElementsProject/lightning#1828]
I didn't have my nodes up for roughly 24 hours, maybe a little more, and came back to my channel being closed.

Is there something I can do about this so that my channels stay open longer without the nodes checking in with each other and closing my channels? If that's even what they do, and what has happened to me here. I don't understand how they are talking and syncing up over the blockchain with only one transaction between them, honestly.

**Comment by SimonVrouwe** [comment]
The _remote_ peer can close the channel _unilaterally_ whenever it wants, but then it has to wait  (normally) 144 blocks = 24hr before it can spent the closing tx. When both peers are connected (online) a _normal_  (bilateral) channel close can happen and that closing tx can be spend immediately, so there is a trade-off and each node may have its own policy on which and how many channels it will keep open. Perhaps you can contact the remote node and ask?

I think the main idea with lightning is that, until we have watch towers, a node is online 24-7 so that it can detect cheats by the remote (i.e. broadcasting a revoked commit tx) and then broadcast the penalty tx. The time-window (starting from the moment of remote's cheat) to broadcast the penalty tx is normally 144 blocks, so that is about the max period a node could be offline not risk being cheated.

**Comment by rustyrussell** [comment]
Unless they manually close the connection, your peers should be happy with you being offline unless you were literally in the middle of a payment.  It's hard to know why the remote peer closed the connection, though...

**Comment by cdecker** [comment]
Without further information as to why the channels were closed, there is very little we can do here. I propose closing this.

**Comment by ZmnSCPxj** [comment]
The other side may decide to close channels at any time, without your approval, and nothing can be done on your side (other than identifying the person(s) running the peer and asking them not to close the channel while you are offline). You may very well want that option in the future if a peer you have is always down when you want control of your funds.

**Comment by cdecker** [comment]
Closing this for now, please let us know if you have any additional information and we can reopen this issue.
