### ISSUE TITLE
Can't close channels

### ISSUE THREAD

**Issue by ts61** [ElementsProject/lightning#1894]
Hi all,

I have many channels that i can't close.
Channel states are CHANNELD_SHUTTING_DOWN, AWAITING_UNILATERAL

I've attached my peers.
[peers.txt](https://github.com/ElementsProject/lightning/files/2332181/peers.txt)

I've tried to close these channels unilaterally and wait a long time but nothing happens. 

Appreciate for any help.

`# lightning-cli getinfo
{
  "id": "02dcdd7e18b80dc7fd51af34e871901c13f574e4b82325dc74c0beeada5771e8e9",
  "alias": "TRABZONSPOR",
  "color": "6b0000",
  "address": [
    {
      "type": "ipv4",
      "address": "138.68.14.201",
      "port": 9735
    }
  ],
  "binding": [
    {
      "type": "ipv4",
      "address": "127.0.0.1",
      "port": 9735
    }
  ],
  "version": "v0.6-424-g28bfa77",
  "blockheight": 539038,
  "network": "bitcoin"
}`

**Comment by rustyrussell** [comment]
What version?  You seem to be having trouble talking to peers, and even your unilateral closes don't seem to be going onto the chain.

**Comment by rustyrussell** [comment]
Is your bitcoind working properly?  This is very weird...

**Comment by ts61** [comment]
Here is a part of the log file @rustyrussell 
[lightning.log.tar.gz](https://github.com/ElementsProject/lightning/files/2337872/lightning.log.tar.gz)
Thank you.

**Comment by ts61** [comment]
@cdecker so there may be a solution?
I read a comment about, resetting channel states and try to close these channels again.
If it may be a solution for me, how can i reset these states?
Thank you.

**Comment by cdecker** [comment]
@ts61 there is no way to reset a channel, if we use `dev-forget-channel` as suggested in #1865 you'll be forfeiting the funds that are in those channels.

**Comment by cdecker** [comment]
Can you share the output of `sqlite3 $HOME/.lightning/lightningd.sqlite3 "select hex(rawtx) from transactions"`, that way we can see if the close transactions can be re-issued.

**Comment by emret** [comment]
@cdecker Here it is [hex_rawtx.log](https://github.com/ElementsProject/lightning/files/2343136/hex_rawtx.log)

Thank you

**Comment by ts61** [comment]
Here it is 
[hex_rawtx.log](https://github.com/ElementsProject/lightning/files/2343137/hex_rawtx.log)

Thank you.

**Comment by ts61** [comment]
Any suggestion here? @cdecker @rustyrussell 
Thanks.

**Comment by cdecker** [comment]
Ok, I took some time to dig into the provided information, and it seems that only 10 of the channels ever confirmed on-chain. It appears you have been creating the majority channels from a non-existing output, and all followup transactions are therefore automatically invalid. The close state was reached by your peers basically giving up waiting for a confirmation or you attempting to close unilaterally (which fails since the close transactions try to spend non-existent outputs).

The fact that the node still created empty close transactions in some cases suggests that you were using a very old version when creating the channels in the first place, which I suspect also caused the internal mixup with non-existent outputs being used to create channels.

For the full analysis please take a look at the following notebook: https://gist.github.com/cdecker/6131302c24e838344568b17307b77f33

Now on to resolutions: since most of the channels ever actually existed it should be safe to run in developer mode and just `dev-forget-channel`. That is also true for most of the transactions that actually confirmed on-chain since you don't have any balance on them. The only channel that we need to care about is the one with `021f87b5fcbbff2cbd839e3ac59c6a3bc620d1f0f638d85726f193cb1839019b90`, in which you have 0.0002BTC (~1.463USD). For that channel we have a close transaction:

```
020000000001011883AA819534873A8945846575F2883A3ED44FAB5DB43312B240EA2D522A2F8A0000000000E9009F8000040047304402203C42382773B7B4C463206CE6C4E92FC673D8ED0FD776F6F282CDBEC57CA419EC0220489CE735B0CD985550B212FEB37B857B965038B0454316438AD4247B0F32DFBB014730440220468175EAD8591FF90333E53B1079BAFC154E6ABF9300F28248A388567FFCBC35022010988C2070B70E0C2517867968B2FA186E7818F8FC5E116147CD88DDE692922F0147522102DD26CA09F1BB6CED06A948816A29097480BA868D6E8F789D0D9659DC82B6596221037AF9CC511989ABD53448963F6A132364D34EE4E0EA9F83BA929F56046A28C30352AEC88C0C20
```

which when decoded looks like this:

```json
{
  "txid": "4f39977dfdcd7d473e6b61e352821fd9f59768f79b2cc2dcab731ff59811a16b",
  "hash": "6cd7a82de13f5821885a3a111591035ac8b0b5ffa145f91d320026d365a097a1",
  "version": 2,
  "size": 271,
  "vsize": 106,
  "locktime": 537693384,
  "vin": [
    {
      "txid": "8a2f2a522dea40b21233b45dab4fd43e3a88f275658445893a87349581aa8318",
      "vout": 0,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "txinwitness": [
        "",
        "304402203c42382773b7b4c463206ce6c4e92fc673d8ed0fd776f6f282cdbec57ca419ec0220489ce735b0cd985550b212feb37b857b965038b0454316438ad4247b0f32dfbb01",
        "30440220468175ead8591ff90333e53b1079bafc154e6abf9300f28248a388567ffcbc35022010988c2070b70e0c2517867968b2fa186e7818f8fc5e116147cd88dde692922f01",
        "522102dd26ca09f1bb6ced06a948816a29097480ba868d6e8f789d0d9659dc82b6596221037af9cc511989abd53448963f6a132364d34ee4e0ea9f83ba929f56046a28c30352ae"
      ],
      "sequence": 2157904105
    }
  ],
  "vout": [
  ]
}
```

Since it doesn't have an output all the funds where eaten by on-chain fees at close time, but it can't confirm since 0-output txs are invalid. It's safe to forget that channel as well.

**Comment by cdecker** [comment]
So to sum up my findings: if you don't have any other channels (besides the ones that you sent us), you're far better off setting up a new node and just forgetting about this one. `dev-rescan-outputs` + `withdraw [your-address] all` should allow you to withdraw any funds that still are on the node, and are not borked.

**Comment by ts61** [comment]
Thank you @cdecker , i already want to migrate my node to an other server, so i'm just try to find a way to recover my funds. Now i understand that all gone.
Regards.

**Comment by cdecker** [comment]
Sorry for being the bearer of bad news. On the bright side though, most of the funds you had on the node were non-existent to begin with, so you only lost 1.45 USD to fees, that you'd have had to pay anyway.
