### ISSUE TITLE
 exec failed: Too many open files

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#214]
+3982.321600486 lightningd(27526):jcon fd 142:DEBUG: Closing (Bad file descriptor)

I see a lot of fd errors and then it runs out of files, though ulimit is only 1024 on my test node. Just wanted to know if this issue is seen before. I am calling the daemon at a high frequency

**Comment by cdecker** [comment]
`jcon` being closed is quite common, it's caused by the json-rpc connection being closed twice I think. It should not be cause for alarm. What is bad is that we run up against the ulimit. That might be an fd leak somewhere. Could you run `lsof` before the limit is reached so we can see what type of fds are kept open?

**Comment by jl777** [comment]
only 39 lightning based items show up on lsof
I think it was some other process going crazy that caused it. the Lightning code has been quite stable.

I am close to being able to run complete simulations with lots of transactions and hopefully it will not have any issues. I will close this for now until I can isolate a specific leak

**Comment by cdecker** [comment]
Perfect, thanks @jl777 for the feedback. Feel free to reopen should it manifest itself again :wink:
