### ISSUE TITLE
CircleCI and ARM32v7 build

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning#2195]
For BTCPayServer, I am maintaining my own fork of clightning mainly for docker purpose.

For our purpose, I use CircleCI to build docker images for different architecture + the docker image manifest (multi arch) and push this automatically on docker hub when we push a git tag with a certain format.

Thanks to the help of @arowser on https://github.com/ElementsProject/lightning/pull/2175, I managed to make an arm32v7 image which does not take 45min to build.

The branch I use is https://github.com/btcpayserver/lightning/tree/feature/arm32v7build
Is it something you would be interested to include in your repository? If yes, I can make a proper PR for you.

The result is this: https://hub.docker.com/r/btcpayserver/lightning/tags where the v0.6.2 version can be used equally on arm32 or x64 boards.

**Comment by ZmnSCPxj** [comment]
Are there code changes needed? Or only build?

We would need somebody to take some ownership over the ARM build but if you are up for it @NicolasDorier it would be better kept upstream here than in a fork.

**Comment by NicolasDorier** [comment]
My fork has features for the image that could not make it here that I rely on with btcpay. 

No much advantage for me to rely on images from docker hub c-lightning for now, until c-lightning becomes more stable and have all the changes I need.

If I make a PR here, I will strip things that only matter for my fork. By adding CircleCI integration, you will have multi arch images automatically built to your docker hub on tag push.

**Comment by ZmnSCPxj** [comment]
LGTM. @rustyrussell @cdecker @niftynei any reactions? @cdecker in particular regarding docker.

**Comment by cdecker** [comment]
Thanks for reporting this @NicolasDorier. I think having more
platforms would be a great addition in general, and I'd be happy to
add Dockerfiles to support those. I'll defer the detailed code review
to the PR, but imho these Dockerfiles should end up in
`contrib/Dockerfile.{variant}`, and shouldn't be in the root of the
repository.

I'm not really familiar with CircleCI, but if they allow us to build a
variety of images out of the box, that'd be a good addition, and I'd
love to backport the config in order to provide you with more reliable
base-images.

I couldn't really find the patches you mentioned regarding delaying
the startup until the blockchain has caught up, but we might want to
add those behind a feature flag, or maybe make that the new default
behavior.

Maybe it's best to split these 3 parts into 3 PRs and we can have a
detailed discussion there :wink:

**Comment by jsarenik** [comment]
Anything going on here?

**Comment by NicolasDorier** [comment]
@jsarenik this can be closed, I did https://github.com/ElementsProject/lightning/pull/2312 but this was rejected as circleci is too greedy on permissions.

I am using it in my own fork.
