### ISSUE TITLE
Cannot announce address ...

### ISSUE THREAD

**Issue by Elmit2015** [ElementsProject/lightning#2236]
I changed my config file to:
alias=TWronald✅
rgb=15C315
announce-addr=xxx.xxx.xxx.xxx:9735

I try to restart lightning by:
$ docker-compose stop clightning_bitcoin
$ docker-compose restart clightning_bitcoin
$ docker-compose logs clightning_bitcoin

I get:
lightning             | C-Lightning starting
lightning             | lightningd: --announce-addr: Cannot announce address xxx.xxx.xxx.xxx:9735; already have xxx.xxx.xxx.xxx:9735 which is the same type

How can I solve that?

**Comment by Saibato** [comment]
@Elmit2015  as of **BOLT 7**  https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#the-node_announcement-message
it states :  MUST NOT include more than one address descriptor of the same type.

if you can use ipv6 then an ipv6 for the second ipv4 might work for you 

hope that helped.

**Comment by cdecker** [comment]
Could it be that you are specifying an `announce-addr` both on the command line as well as in the config?

**Comment by Elmit2015** [comment]
For now I stopped the containers, removed them and rebuild them. So the new settings are taken. Maybe that's anyway the right way.

Next is to fund. 
$ lightning-cli newaddr
{
  "address": "bc1q9qy65l9xg2jcn4un4d29frp3ekqzzc9k0hu78w"
}

I thought an BTC address starts with 01 or 03, this address starts with bc...
I consult blockchain.com and ask for this address and get:
Illegal character l at position 9.

I am scared to send my money to that address now.

**Comment by jb55** [comment]
@Elmit2015 those are native segwit addresses, there's no reason to be afraid, they're fully supported by the Bitcoin network. If your wallet doesn't support it, it wouldn't send it anyways.

Here's an example transaction that uses bech32 native-segwit addresses: https://www.blockchain.com/btc/tx/35e0effdd95b510d4c4eb3b7e3456b89c2ec7a35fd9ef160ed3a11212b766ca8

**Comment by Elmit2015** [comment]
Thanks a lot for your help!
I am learning ;-)

I see so many messages in the docker-compose window, which I cannot understand yet.

What does it mean:
feerate estimate for slow hit floor 253
or
Received channel_update for channel ... now ACTIVE was ACTIVE from subdaemon)
same with DISABLED was DISABLED or DISABLED was ACTIVE ....
or
Received node for node ....

Where can I read about that?

I guess, if one of my channels would be used, then lightning-cli getifno would show something in msatoshi_fees_collected     ---- but it remains at zero, even after running the node and channel for 6 hours. Do I need to do something, or just patiently wait?

**Comment by cdecker** [comment]
Given that all the channels have the same capacity I assume you have opened all those channels yourself. If you opened them, you will not have any incoming capacity, which means you can't forward payments because nobody can send you any funds over those channels (on all channels you already own all the funds, so with what should they pay you?). You could try to perform some outgoing payments to move some funds to your counterpary and create outgoing capacity.

If by lucky draw you mean nobody has opened a channel with you, then that's probably because people still insist on manually managing channels, instead of randomly opening them. Hopefully that'll change soon.

As for the original issue, it seems that the configured IP address is now being broadcast correctly. I think we can close this issue.
