### ISSUE TITLE
two nodes with same codebase display a different version

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#2331]
I've done `git pull origin master` on both nodes, `make clean`, `make -j 4`, but when i run `getinfo`, i get this:

```
  "version": "v0.6.2-464-gd413fc7", 
  "version": "v0.6.1-703-gd413fc7", 
```
Is this expected?

**Comment by cdecker** [comment]
This can happen when the second pull misses the `v0.6.2` tag. Basically the number between version tag and the git commit ID is the number of commits since that tag. They are identical, but the second missed that there is the v0.6.2 tag (and both are missing 0.6.3 for that matter) hence it shows v0.6.1 + 703 commits. If you do `git fetch --tags --force` it should get the tags, and then rebuilding should use the correct version tags :-)
