### ISSUE TITLE
listfunds does not show anything after i send btc to address

### ISSUE THREAD

**Issue by barray888** [ElementsProject/lightning#2347]
1. cli/lightning-cli newaddr

2. cli/lightning-cli dev-listaddrs

```{
	"addresses": [{
			"keyidx": 0,
			"pubkey": "03b691cbb8b97170c8b8320b011272c3ed2b5cb2e38ab855cbde492bae7192d6ce",
			"p2sh": "36kPg6S6Z5BsbuXB87jX5VJEn4uKA5wQcZ",
			"p2sh_redeemscript": "0014eb354dcf11934b331751c4cc3cee6b15818fe688",
			"bech32": "bc1qav65mnc3jd9nx963cnxremntzkqcle5g3p5mef",
			"bech32_redeemscript": "eb354dcf11934b331751c4cc3cee6b15818fe688"
		}
	]
}
```
3. send btc to the address 36kPg6S6Z5BsbuXB87jX5VJEn4uKA5wQcZ

4.after all confirmed, listfunds shows nothing

**Comment by barray888** [comment]
something wrong with me? i need some help thx!

**Comment by barray888** [comment]
Is it because the wrong address type was sent? is bech32 address instead of p2sh?

**Comment by cdecker** [comment]
Was `3\. 36kPg6S6Z5BsbuXB87jX5VJEn4uKA5wQcZ` the address that was returned by `lightning-cli newaddr` or was that `bc1qav65mnc3jd9nx963cnxremntzkqcle5g3p5mef`. It shouldn't really matter since we ad dboth variants:

https://github.com/ElementsProject/lightning/blob/960664337f2afc1aa9aac7618e11a0cb07503560/wallet/walletrpc.c#L299

https://github.com/ElementsProject/lightning/blob/a00c357854bffd8add6f2a501110df0e56db6ce8/wallet/txfilter.c#L61-L71

**Comment by cdecker** [comment]
Ok, I tried to reproduce your issue, but couldn't. See here for details https://github.com/ElementsProject/lightning/commit/dd827a71c51c0b831b90af55c08cbf0484bb3909

**Comment by barray888** [comment]
@cdecker  thanks man ! i just went home a few minutes ago,checked again and  listfunds shows the balance alreay.

**Comment by cdecker** [comment]
ok, in that case we were simply lagging behind the blockchain head and didn't see the confirmation yet :wink: 

Thanks for the all-clear :-)
