### ISSUE TITLE
Python JSON-RPC shouldn't require space before '}'

### ISSUE THREAD

**Issue by bitonic-cjp** [ElementsProject/lightning#2350]
Minor nitpick on contrib/pylightning/lightning/lightning.py line 45:
`if b' }\n' not in buff:`
should be:
`if b'}\n' not in buff:`
(the difference is the space removed).

The way it is now, it requires a space before the closing '}' of received objects. I don't know why this works now. Maybe C-Lightning always emits a space? I discovered this because this RPC code doesn't work with a dummy C-Lightning placeholder I developed myself for testing purposes.

**Comment by cdecker** [comment]
That indeed comes down to the peculiarity with how we generate the result:

https://github.com/ElementsProject/lightning/blob/3e4a3bafc3db443c00a1bb16f95c0f0ca69850d4/lightningd/jsonrpc.c#L435-L453

The JSON object is terminated by manually appending ` }\n`. We kept this for now since we have to be backward compatible with old versions that didn't terminate messages with `\n\n`, but once we stop supporting those ancient versions we can use that indicator to split our messages more efficiently.

The space is there mainly in order to reduce the failed attempts that occur due to arrays of objects (a common pattern in our API) attempting to decode the object only to fail.
