### ISSUE TITLE
[feature request] channel rebalancing

### ISSUE THREAD

**Issue by renepickhardt** [ElementsProject/lightning#2376]
following [this discussion on stackexchange](https://bitcoin.stackexchange.com/questions/84786/is-it-possible-to-rebalance-channels-by-sending-to-yourself-from-a-channel-to-a/84787) I realize that it would be easy to provide an API for channel rebalancing. 

It could be done by allowing the `getroute` command to find a route to oneself (creating a circle) or by creating a new command. 

I might create this feature if you like. How would you want the API to look like? rather a low level `balancechannel channel1 channel2` command or a high level `balancechannels` command. Or is there no interest in this feature? It could also be an easy plugin to create.

**Comment by conscott** [comment]
Someone made a tool for lnd to do this : https://github.com/C-Otto/rebalance-lnd although I suspect it could look a lot simper. I keep intending to start this a plugin, but then getting side tracked with other stuff. 

I like the script above because it's a bit interactive. Basically you kind of want to know:
- Which channels have most funds on the local side (available as outgoing)
- Which channels have most fund on the remote side (available as incoming)
- Which 2 would be a good match for a rebalance. 
- If multiple sends should be done to get the desired effect. 

It can get a bit complicated, since the channel capacities themselves might not quite line up to do what you want. You could certainly automate the whole thing to do 'best choice', but a simple first version might just let you attempt to create and use a circulate route from your channel A to your channel B sending X amount. 

I am certainly interested in the feature and could help test.

**Comment by m-schmoock** [comment]
I would prefer a low level command that simply drains a channel to get 'cheap' liquidity if the channel is already low, i.e. `drainchannel <scid>`. The algorithm could decide itself which channel to use for inbound looping.

... or is the second channel argument in your `balancechannel channel1 channel2` used for somethign else?

**Comment by billygarrison** [comment]
I've been working on a script for this but running into some issues (see https://github.com/ElementsProject/lightning/issues/2362).

So far the script can create the circular route and send the payment, but it fails most of the time with `WIRE_TEMPORARY_CHANNEL_FAILURE`.

I also have another script that automatically detects your most unbalanced channels and tries to rebalance by paying out through one (the one that's heavy on the local side) and in through the other (heavy on remote side).

I've been keeping the repo private because the code is pretty messy/amateur so far. Since there's interest, I can clean it up this weekend and make the repo public.

cc @conscott @rustyrussell

**Comment by conscott** [comment]
Sure @billygarrison - In the mean time I have been working on a library for  'aggregators' and 'filters' associated with c-lightning [here](https://github.com/conscott/c-lightning-plugins/tree/dev/lib), to make it easier to have a singe call for something like "give me all unbalanced channels with majority of funds on local side / remote side". Looking at your implementation may give me some more ideas to help make things easier. 

I linked to the `dev` branch, the lib is coming together but I totally broke most of my plugins, need some time to fix everything up but likely won't have time for a few days. Once it's all ready and more battle tested I might try to merge the lib stuf back into c-lightning if people agree.

**Comment by renepickhardt** [comment]
started implementing it @cdecker the lightning-rpc `listchannels` call starts to take long time. I guess the reason is that the json parsing in the rpc interface is so inefficient. if I do `lighting-cli listchannels > channels.json` it takes less than a second. should I open a new bug request for this? I think we have previously discussed that the json parsing might become a problem if the data gets bigger

**Comment by m-schmoock** [comment]
Pretty sure the way you describe it, that your terminal emulator (maybe like gnome with transparency effect?) is the reason its sloooow. Especially since the pipe is fast using the same command.

Or am I misinterpreting something here?

**Comment by cdecker** [comment]
> started implementing it @cdecker the lightning-rpc `listchannels` call starts to take long time. I guess the reason is that the json parsing in the rpc interface is so inefficient. if I do `lighting-cli listchannels > channels.json` it takes less than a second. should I open a new bug request for this? I think we have previously discussed that the json parsing might become a problem if the data gets bigger

What are you using to call to the RPC? Is it the pylightning implementation? Notice that the first call will use the old style parsing, so do a short call first (`getinfo` is a good one), all calls after that should use the quicker `\n\n` separator.

Otherwise make sure to use that latest version (not the one from pypi).

**Comment by renepickhardt** [comment]
@cdecker I am using exactly this file: https://github.com/ElementsProject/lightning/blob/master/contrib/pylightning/lightning/lightning.py

calls to `listfunds` and `getinfo` execute fast. but once my program does `listchannels` execution does not even stop after 10 minutes. once I send sigterm the program always terminates in the loop parsing the response from the json 

```
^CTraceback (most recent call last):
  File "balance.py", line 54, in <module>
    get_network()
  File "balance.py", line 40, in get_network
    ln.listchannels()
  File "/home/rpickhardt/.local/lib/python3.6/site-packages/lightning/lightning.py", line 331, in listchannels
    return self.call("listchannels", payload)
  File "/home/rpickhardt/.local/lib/python3.6/site-packages/lightning/lightning.py", line 215, in call
    resp, _ = self._readobj_compat(sock)
  File "/home/rpickhardt/.local/lib/python3.6/site-packages/lightning/lightning.py", line 141, in _readobj_compat
    return self._readobj(sock, buff)
  File "/home/rpickhardt/.local/lib/python3.6/site-packages/lightning/lightning.py", line 171, in _readobj
    b = sock.recv(max(1024, len(buff)))
KeyboardInterrupt
```

However I have still an old version of c-lightning running. Wonder why some calls work perfectly. and with `lightning-cli` the call also works quickly as mentioned.

**Comment by renepickhardt** [comment]
Ok after updating to 0.7 the problem vanished and I don't want to trace down why it didn't work before. Still lightning-cli ist twice as fast

```
rpickhardt@Ubuntu-1804-bionic-64-minimal:~/plugins$ time python3 balance.py 
get Network
got network

real	0m13.111s
user	0m5.187s
sys	0m0.640s

rpickhardt@Ubuntu-1804-bionic-64-minimal:~/plugins$ time lightning-cli listchannels > tmp

real	0m7.355s
user	0m0.178s
sys	0m0.036s
```

**Comment by m-schmoock** [comment]
I think this can be closed. We have a rebalance plugin in the plugin repo:

https://github.com/lightningd/plugins/tree/master/rebalance

**Comment by cdecker** [comment]
Good catch @m-schmoock, happy to close it :-)
