### ISSUE TITLE
Why do the channel IDs stored in forwarded_payments use a different format?

### ISSUE THREAD

**Issue by billygarrison** [ElementsProject/lightning#2484]
It seems to me that c-lightning uses the 563528x1309x1 format almost everywhere. The only place I could find the "LND" format (e.g. 619605588663140353) in c-lightning is the `forwarded_payments` table.

I'm curious why this is the case, and what are the pros/cons of using the different formats for different parts of c-lightning?

I understand the benefit of 563528x1309x1 being human-readable and not needing to be converted to get funding tx information, but what benefit does the other format offer?

**Comment by cdecker** [comment]
Like you mentioned the advantage of using the `x`-separated format is that it is easier to read and debug if we get a database, at the expense of being larger (`varchar` field with extra separators vs 8 byte `u64` field). The advantage of using the raw `u64` representation is that we don't need to parse it from the DB and can directly use it in memory, but makes reading values from the database when debugging a bit more tedious.

As for why one format was chosen over the other in a specific table: it's likely due to historical reasons, or just an inconsistency. Given that we now have migrations that can invoke arbitrary code, we could consolidate on one format if desired, but that's likely just a minor cleanup, not all that important at the moment.

**Comment by billygarrison** [comment]
Thanks for the explanation!

For a bit more info, I was trying to join the forwarded_payments table to the channel_htlcs table on channel_id, but was unable to do it easily because of the different formats. I agree though, it's not very important relative to other ongoing development.

**Comment by cdecker** [comment]
Good point, that might be a good reason to make the `short_channel_id` in the `channel_htlcs` table a `u64` as well since they are way smaller to index and process.
