### ISSUE TITLE
stuck on "feerate estimate for slow hit floor 253"

### ISSUE THREAD

**Issue by DariusParvin** [ElementsProject/lightning#2502]
### Issue and Steps to Reproduce

I have bitcoind running on mainnet and I run the following command:
lightningd --network=bitcoin --log-level=debug

It then seems to get stuck on doing:
"lightningd(1078): ... feerate estimate for slow hit floor 253"

full log here:
https://pastebin.com/QEzDEFsG

thanks

**Comment by cdecker** [comment]
What were you expecting to happen? If you don't tell `lightningd` to connect somewhere, it'll just sit there happily tracking the feerate changes forever. If you want to establish a channel with a peer (let's call it `A` with address `1.2.3.4`) you need to do the following:

 - `lightning-cli newaddr` will give you an address to send some funds to, in order to open a new channel
 - `bitcoin-cli sendtoaddress [addr] 0.01` will send ~40$ to `lightningd` which it can then use to open channels.
 - `lightning-cli connect A@1.2.3.4` connects to `A`
 - `lightning-cli fundchannel A 0.005` will open a new channel with ~20$ with the node `A`

You can then use `lightning-cli listpeers` to check on the progress of the channel creation. It should take around 20 minutes to open the channel, and 60 minutes for it to become known to the rest of the world (explorers and nodes that might want to route through you). For routing you will need at least two channels and some incoming capacity, i.e., have someone open a channel with you or spend some of you funds somewhere, and even then you might not be picked by other nodes for routing.

**Comment by billygarrison** [comment]
Also you can do add `slow` to the end of that `fundchannel` command to pay less in transaction fees when opening the channel. E.g. 1 sat/byte vs 20

Also @cdecker does `fundchannel` work with 0.005? I always use amount in satoshis as that's what documentation calls for.

**Comment by DariusParvin** [comment]
Thanks a lot both of you. I'm fairly new to using developer tools and didn't realize you had to open a new terminal to use the other lightning-cli commands 😅
