### ISSUE TITLE
Closing channel question

### ISSUE THREAD

**Issue by mloop1** [ElementsProject/lightning#2595]
I'd like to ask 2 questions to improve my knowledge on the system, apologies if they have already been answered (I couldn't find any though).
1) When getting a message like the following, where is the closing originating from and what could the reason be? Also who is going to pay the closing fee to who?

```
            "CHANNELD_AWAITING_LOCKIN:Reconnected, and reestablished.", 
            "CHANNELD_NORMAL:Reconnected, and reestablished.", 
            "CLOSINGD_SIGEXCHANGE:We agreed on a closing fee of 11261 satoshi", 
            "ONCHAIN:Tracking mutual close transaction", 
            "ONCHAIN:All outputs resolved: waiting 91 more blocks before forgetting channel"
```

2) In relation to in/out_payments_offered/fulfilled what are the typical reason why a payment is offered but not fulfilled? May be because a more convenient route was found? 

Thanks for any help.

**Comment by darosior** [comment]
Hi, I'm not the most well informed out there, but I can try to give you a description.
> (I couldn't find any though)

You can learn more about the protocol [in the RFC](https://github.com/lightningnetwork/lightning-rfc). [Here](https://docs.google.com/presentation/d/1-eyceLlSmcLpbPJLzj6_CnVYQdo1AUP3y5XD716U-Lg/edit#slide=id.g5007643c03_0_121) is also a great introduction to Lightning Network by René Pickhardt.

> When getting a message like the following, where is the closing originating from and what could the reason be? Also who is going to pay the closing fee to who?
"CHANNELD_AWAITING_LOCKIN:Reconnected, and reestablished.",
"CHANNELD_NORMAL:Reconnected, and reestablished.",


These two are from the [channel establishment](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#channel-establishment) :
```
    +-------+                              +-------+
    |       |--(1)---  open_channel  ----->|       |
    |       |<-(2)--  accept_channel  -----|       |
    |       |                              |       |
    |   A   |--(3)--  funding_created  --->|   B   |
    |       |<-(4)--  funding_signed  -----|       |
    |       |                              |       |
    |       |--(5)--- funding_locked  ---->|       |
    |       |<-(6)--- funding_locked  -----|       |
    +-------+                              +-------+

    - where node A is 'funder' and node B is 'fundee'
```

> "CLOSINGD_SIGEXCHANGE:We agreed on a closing fee of 11261 satoshi",
"ONCHAIN:Tracking mutual close transaction",
"ONCHAIN:All outputs resolved: waiting 91 more blocks before forgetting channel"

These ones are from the [channel close procedure](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#channel-close), quoting the RFC : 
> Closing happens in two stages:
    1) one side indicates it wants to clear the channel (and thus will accept no new HTLCs)
    2) once all HTLCs are resolved, the final channel close negotiation begins.

```
 +-------+                              +-------+
 |       |--(1)-----  shutdown  ------->|       |
 |       |<-(2)-----  shutdown  --------|       |
 |       |                              |       |
 |       | <complete all pending HTLCs> |       |
 |   A   |                 ...          |   B   |
 |       |                              |       |
 |       |--(3)-- closing_signed  F1--->|       |
 |       |<-(4)-- closing_signed  F2----|       |
 |       |              ...             |       |
 |       |--(?)-- closing_signed  Fn--->|       |
 |       |<-(?)-- closing_signed  Fn----|       |
 +-------+                              +-------+
```
`CLOSING_SIDEXCHANGE` means your node exchanged signatures with the remote node (`closing_signed` on the above scheme). The last two are explicit enough.


To answer more precisely your questions :
> where is the closing originating from and what could the reason be?

A `shutdown` message sent whether by your node or the remote one.

> Also who is going to pay the closing fee to who?

The fees are always paid __to__ miners. In our case fees are paid __from__ the funding transaction output.

**Comment by mloop1** [comment]
thanks for the explanation and for pointing me to some useful documentation

**Comment by cdecker** [comment]
> where is the closing originating from and what could the reason be?

My guess would be that either you or your peer decided to manually close the channel (calling `lightning-cli close [peer_id]` for example). None of the usual suspects for automated close really apply as long as you have a working connection and are negotiating the parameters correctly (e.g., a fee spike doesn't cause collaborative closes).

> In relation to in/out_payments_offered/fulfilled what are the typical reason why a payment is offered but not fulfilled? May be because a more convenient route was found?

A payment is only retried on a different route if the first attempt which result in the offered payment has failed, i.e., the offered HTLC either succeeds, or fails, and only in the latter case it is retried. So a better route isn't really competing with you.

An offered payment may fail for a number of reasons:
 - If you are the destination of the payment, and the payment is not forwarded, but you don't have a matching invoice, or some of the payments details don't match the invoice (amount) then you will reject the payment;
 - If you are an intermediate hop, and are supposed to forward the payment:
   - You accept the incoming HTLC but are then unable to forward because the next hop is currently unavailable
    - You forward the payment correctly, but somewhere downstream from you the payment fails, and you have to fail your HTLC as well, in order to clean up;

Notice also that some nodes actively probe the network for failing routes, and the technique they use will show up as failed HTLCs even if the probe succeeded (they use payments that do not match an invoice). So don't think of faled `in/out_payments_failed` as an error, but merely some debug information we expose in addition to the successful ones :-)

**Comment by mloop1** [comment]
Thanks for the info!

**Comment by cdecker** [comment]
Anytime :wink: 

You might get even quicker answers to these kind of things on https://bitcoin.stackexchange.com/ by the way. There's quite a few knowledgeable people lurking there as well :-)
