### ISSUE TITLE
Enable additional sanitizers 

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#2606]
As @practicalswift pointed out in #2593 it would be a good idea to also enable the integer overflow sanitizer and some others.

> @cdecker They are compatible. We could run -fsanitize=address,integer,undefined in one job as we do for Bitcoin Core: https://github.com/bitcoin/bitcoin/blob/master/.travis.yml#L165
> 
> Please note that -fsanitize=integer will require suppressions to cover the intentional unsigned integer wraparounds (typically found in crypto/hashing code) but I think that is a fairly low price to pay to get immediate notification in case of introduction of unintentional unsigned integer wraparounds.
> 
> See the unsigned-integer-overflow suppressions in the Bitcoin Core project: https://github.com/bitcoin/bitcoin/blob/master/test/sanitizer_suppressions/ubsan

**Comment by practicalswift** [comment]
Worth noting:
* `-fsanitize=undefined` takes care of signed integer overflow (UB)
* `-fsanitize=integer` takes care of unsigned integer wraparound which is not UB but can be unintentional (likely a bug)

The four different cases:

|  | Signed integer overflow | Unsigned integer wraparound |
|---------------|--------------------------------------|------------------------------------|
| **Intentional** | BAD (UB)| OK: mark as intentional using suppression |
| **Unintentional** | BAD (UB) | BAD (likely bug) |
