### ISSUE TITLE
pylightning: "'description' should be a string, not '#  Frog' (note, we don't allow \\u)"

### ISSUE THREAD

**Issue by jarret** [ElementsProject/lightning#2753]
In my Python3 application which uses `pylightning` I am seeing this error:

```Traceback (most recent call last):
  File "/home/ubuntu/btc-rust/git/mart/lib/daemon/daemon.py", line 266, in invoice_c_lightning
    expiry=expiry, preimage=preimage)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/lightning/lightning.py", line 347, in invoice
    return self.call("invoice", payload)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/lightning/lightning.py", line 220, in call
    raise RpcError(method, payload, resp['error'])
lightning.lightning.RpcError: RPC call failed: method: invoice, payload: {'msatoshi': 7000, 'label': 'pOUskOQfR0GyAhSyug5DRg==', 'description': '#  Frog', 'expiry': 600, 'preimage': '9c610ec7b3e3e4c78dc8abdc242da1656402cdc95d73569d86ae7a3ae43f6032'}, error: {'code': -32602, 'message': "'description' should be a string, not '#  Frog' (note, we don't allow \\u)"
```

I was trying to include a frog emoji `🐸` (in the place of the `#` in the error string) in the description which I am feeding it in via the current `pylightning` version:

```$ pip3 show pylightningName: pylightning
Version: 0.0.7
Summary: Client library for lightningd
Home-page: http://github.com/ElementsProject/lightning
Author: Christian Decker
Author-email: decker.christian@gmail.com
License: MIT
Location: /home/ubuntu/.local/lib/python3.6/site-packages
Requires: 
```
Adding an emoji to the description field works fine via `lighning-cli` when it is give the string on the bash console like so:
` ./lightning/usr/bin/lightning-cli --lightning-dir=./lightning-dir invoice 1000 abc123label "🐸  Frog"`

I have determined that the issue is with the `json.dumps()` call in the `_writeobj()` call of `UnixDomainSocketRpc`. The output produced has escaped non-ascii characters with `\u` as the error message is indicating.

I have tried the `ensure_ascii=False` setting and it does work for me, however I am unsure about possible side-effects.

```diff --git a/contrib/pylightning/lightning/lightning.py b/contrib/pylightning/lightning/lightning.py
index e2e46f12..983bdcd2 100644
--- a/contrib/pylightning/lightning/lightning.py
+++ b/contrib/pylightning/lightning/lightning.py
@@ -133,7 +133,7 @@ class UnixDomainSocketRpc(object):
         self.next_id = 0
 
     def _writeobj(self, sock, obj):
-        s = json.dumps(obj, cls=self.encoder_cls)
+        s = json.dumps(obj, ensure_ascii=False, cls=self.encoder_cls)
         sock.sendall(bytearray(s, 'UTF-8'))
 
     def _readobj_compat(self, sock, buff=b''):
```

This is what I would propose as a fix, however it might also make sense to allow the daemon to interpret accept the escaped output as is formatted in the JSON.

**Comment by ZmnSCPxj** [comment]
The root issue is that we store strings using whatever JSON encoding we receive via JSON-RPC.  This means we consider the string `"\n"` as not equal to the string `"\012"`.  This can be problematic for invoice `label`s if you use different JSON-RPC interfaces with divergent ways of encoding the same string.  For description it likely does not matter as we do not support searching by description, only by `label`.

JSON spec indicates "Any character *may* be escaped", so properly speaking C-lightning "should" store the string being represented, rather than (as we do now) the representation of the string minus double quotes.  Or alternately use a canonical representation (i.e. parse string escapes, then use a canonical escaping algorithm).

Otherwise, if you have two clients working with the same C-lightning instance, and somehow expect that unicode chars used in labels by one client are properly usable on the other client, and the clients use different JSON-RPC libraries (e.g. if they are in different languages) this will be very problematic.

**Comment by rustyrussell** [comment]
I think this is best done by the caller.  If you've got unicode escapes, convert to UTF-8.  But this is @cdecker 's domain.
