### ISSUE TITLE
Don't freak out when bitcoind says it's rewinding blocks...

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#286]
From #284 crash.log:

    +136792.168286138 lightningd(9465):BROKEN: bitcoin-cli getchaintips exited 28: 'error code: -28
    error message:
    Rewinding blocks...

This is unfortunate, but we should give it a few tries I think?

**Comment by cdecker** [comment]
There's two different issues here I think:

1. `bitcoind` failing to respond upon startup
2. `bitcoind` becoming unreachable potentially restarting and becoming reachable again

In the former case we can probably just poll for readiness on startup. It's unlikely that something urgent has to be done, so waiting for `bitcoind` to finish its startup before continuing ours seems reasonable (we couldn't do anything anyway). The second case is dangerous, we can't just wait for it to come back, it might not come back at all, and we might be in the middle of an urgent situation. We currently just die whenever we lose contact to `bitcoind`, but I'd like to ween off of the full node dependency slowly, which is why I'm implementing the bitcoin protocol and am planning to keep a connection pool to public nodes. That'd allow us to monitor for blocks and transactions, and it allows us to broadcast transactions even without a `bitcoind` running locally.

So if this is an attempt to fix the startup problem, I'm all for it. If it is more about fixing outages while running, I'd say we allow some downtime, but if `bitcoind` doesn't come back in time we should be looking for alternatives to settle and shut down.
