### ISSUE TITLE
Error connecting to .onion node

### ISSUE THREAD

**Issue by kalibox** [ElementsProject/lightning#3036]
Hi, 

I'm a "case#8" from the tor documentation and have existing inbound and outbound clearnet connections. I've setup a tor proxy on the local machine and have confirmed it is working. However, when trying to connect to a tor node, I keep getting this message with no connection initiated:

2019-09-07T20:52:21.155Z DEBUG lightning_connectd(11769): Failed connected out for 02d419c9af624d0e7a7c90a60b9ffa35f4934973a9d7d3b4175cc3cc28b7ffcde1: 4k65ti7tyv6ejntpvtxwtzc2ala25fx4bxms2dekax3lb5n2c3rexhid.onion:9735: Connection establishment: Operation now in progress. 4k65ti7tyv6ejntpvtxwtzc2ala25fx4bxms2dekax3lb5n2c3rexhid.onion:9735: Connection establishment: Operation now in progress.

Thoughts?

Thanks

**Comment by Saibato** [comment]
There is a high prob that your tor version does not support V3 onions.
Can you do i.e. tor --version  it should be above 0.3.2.9  and 0.3.2.1 might work but below only
V2 addr will work.

The return message is not that clear, so that we might have to address.
Hope that helps.
FYI: the node 02d419c9af624d0e7a7c90a60b9ffa35f4934973a9d7d3b4175cc3cc28b7ffcde1: 4k65ti7tyv6ejntpvtxwtzc2ala25fx4bxms2dekax3lb5n2c3rexhid.onion:9735 is online and can be reached. 

A simple way to test without update the tor software in your default system distribution. 
Is to install the tor browser from the tor project, start it and then setup your nodes to use 9150 and 9151 instead of 9050 and 9051. The tor browser has the newest tor version included.
Hope that helps.

**Comment by kalibox** [comment]
Hi, thanks very much for the reply. You're right, I'm running an older version:

$ tor --version
Tor version 0.2.9.16 (git-9ef571339967c1e5)

This is on a RaspPi, I should add.

I'll try the browser tip you've mentioned and will also look to build the tor service locally to the Pi.

Many thanks.

**Comment by kalibox** [comment]
By the way, how were you able to validate that the above .onion URI was online?

**Comment by Saibato** [comment]
You can check with a working node.
But I guess what you want to know is this  
<details><summary>Click me for Netcat magic</summary>
<p>

####  nc!


nc -vvx 127.0.0.1:9150 4k65ti7tyv6ejntpvtxwtzc2ala25fx4bxms2dekax3lb5n2c3rexhid.onion 9735
</p>
</details>

**Comment by kalibox** [comment]
Thank you :)

**Comment by kalibox** [comment]
Thanks for your help. We can close this now. I've downloaded and built tor Tor version 0.4.1.5. and am able to open channels with .onion addresses. Many thanks.
