### ISSUE TITLE
proxy setting is not affecting connection to clearnet address

### ISSUE THREAD

**Issue by bitcoin-software** [ElementsProject/lightning#3239]
### Issue and Steps to Reproduce
i'm in FreeBSD jail ( using https://github.com/bitcoin-software/bitbsd-clouds )
the jail has no clearnet internet access, only communication over tor proxy
```
[lightning@clnee69fa68 ~]$ lightning-cli connect 0388a2cd707ac944a2b0c8adbf67c4a313d24b6dc2ab2baba842f9a9eecf925131@92.62.97.26:9735
```
_long waiting_
```
{
   "code": -1,
   "message": "92.62.97.26:9735: Connection establishment: Operation timed out. "
}
```
if i try connect to onion:
```
[lightning@clnee69fa68 ~]$ lightning-cli connect 0388a2cd707ac944a2b0c8adbf67c4a313d24b6dc2ab2baba842f9a9eecf925131@cm5qj4ub4xfswke7.onion:9735
```
```
{
   "id": "0388a2cd707ac944a2b0c8adbf67c4a313d24b6dc2ab2baba842f9a9eecf925131"
}
```

When i enable access to clearnet 9735 port from exact jail then connection to clearnet address succeeds.

This potentially means that TOR-ed c-lightning node discloses its real IP address to another clearnet nodes.

It may be reproducable using https://github.com/bitcoin-software/bitbsd-clouds/tree/master/lightningd . You can access clearnet (port 9735) and .onion addresses, while 'proxy=' setting is set up, you will fail to connect to node with port other from 9735, because connection on clearnet will be blocked by firewall

$ lightningd --version
v0.7.3

**Comment by Saibato** [comment]
hi @bitcoin-software I tried to confirm your observation, 
but I can not confirm that any leak was the reason for your possible  observation.

My guess so far is, that you successfully connected over Tor, but then not closed the peer but entered connect [ID] IP directly after, that would without this IP address show PR see ff even work with any ip you type after peer ID as the old connection is persistent until you close the peer.
On active master it will just show you the node id an return success and not accept the new ip.
That cry's a bit for some PR to have better UX

I created a test branch
https://github.com/Saibato/lightning/commit/6477c98a8505e37af303180bfca745624dc4cb00 
on top of active master https://github.com/ElementsProject/lightning/commit/4c2f51ce13ee01b509ce53e57b8f002b2f6a3d3f that will show also the Ip (address) the peer connects to on a
successful connect command
i.e:
`lightning-cli  --lightning-dir=/tmp/N1 connect 02fab1a406203b2419bc48556638012d20baff2a2c90834e4766bb7cd9898222f0 127.0.0.1


{
   "id": "02fab1a406203b2419bc48556638012d20baff2a2c90834e4766bb7cd9898222f0",
   "address": {
      "type": "ipv4",
      "address": "127.0.0.1",
      "port": 9735
   }
}
`

, can you please run this and share here the output of you connect commands.  
Lets hope that will close this issue, since leaking IP over Tor is definitive not a desired feature.

**Comment by bitcoin-software** [comment]
well, i can confirm that it seems that there is an IP leak unfortunately...

First, in the enviroment where TOR-only is possible. Any other outgoing conn are blocked.

Connecting to .onion node:

`satoshi@okab:~ % lightning-cli connect 02b6194e45209f77f20315308560946c141fe6159b45aaca26faaae45f915d0f43 szmya7aejdv7j2n7kazqcq2tioyjixidslk6lp7qf4ekpb2stuk4xeyd.onion:9735`

```
{
   "id": "02b6194e45209f77f20315308560946c141fe6159b45aaca26faaae45f915d0f43",
   "address": {
      "type": "torv3",
      "address": "szmya7aejdv7j2n7kazqcq2tioyjixidslk6lp7qf4ekpb2stuk4xeyd.onion",
      "port": 9735
   }
}
```

Connecting to clearnet node:

`satoshi@okab:~ % lightning-cli connect `

```
02a04446caa81636d60d63b066f2814cbd3a6b5c258e3172cbdded7a16e2cfff4c 3.122.40.122:9735
{
   "code": -1,
   "message": "3.122.40.122:9735: Connection establishment: Operation timed out. "
}
```

Okay, now i enable outgoing port 9735:

`satoshi@okab:~ % lightning-cli connect 02a04446caa81636d60d63b066f2814cbd3a6b5c258e3172cbdded7a16e2cfff4c 3.122.40.122:9735                                                              
`

```
{
   "id": "02a04446caa81636d60d63b066f2814cbd3a6b5c258e3172cbdded7a16e2cfff4c",
   "address": {
      "type": "ipv4",
      "address": "3.122.40.122",
      "port": 9735
   }
}
```

My config file:

```
alias=[bitclouds.sh]
bind-addr=0.0.0.0:9735
rgb=ff0000
#announce-addr=.onion:9735
#announce-addr=bitbsd.org:9735
network=bitcoin
log-level=info
#ignore-fee-limits=1
fee-base=0
fee-per-satoshi=1
proxy=192.168.0.IP:9050
#log-file=/home/lightning/.lightning/c-lightning.log
min-capacity-sat=200000
```

You may want to connect to that test instande, you can do so:

`$ ssh satoshi@bitbsd.org -p62303`

password: `nakamoto`

connect to tmux, by typin `tmux a` under `satoshi`. there's `sudo su` available if any...

![image](https://user-images.githubusercontent.com/56356999/68340748-b3167a80-00ef-11ea-973c-ef74880d995a.png)

**Comment by bitcoin-software** [comment]
9735 port is enabled currently.. you can try any other clearnet port node, eg. `02bed1812d3824f7cc4ccd38da5d66a29fcfec146fe95e26cd2e0d3f930d653a8d@172.81.178.38:9736`

**Comment by Saibato** [comment]
hi @bitcoin-software so far all fine thanks for the infos I found some explanation to your observations, I assume , what you observe is the inner bindings of all address incl. loopback_ regardless what the app picks or binds too, in a freeBSD jail the first address of the outer jail  your real routeable address is bound by default, since all adapters are emulated. Sigh...
As long as you not announce any ipv4/6 address and have the firewall close the port, the node should by that  only be reachable by his tor onion address that tunnels the firewall, as long as you use the Tor socks5 proxy c-ln can reach all other nodes regardless if Tor / ip / or a FQDN is used all will only see the ip of the Tor exit point, but not your address. and all other can reach you over Tor.
So glad no c-ln leak, but some strange freeBSD jail network handling  It might help to create your own BPF adapter i.e lo2 in the jail.conf.  
 
vf3gsyce6rl6otd52umhoqmwzz2uwpdg3s2yfunhgc6dxxcj243n34ad.onion 9735  /  okab.bitclouds.sh

**Comment by bitcoin-software** [comment]
but i run my tor node on all interfaces (0.0.0.0), so why cln does not catch the LAN address set up on instance (192.168.0.X) to proxy via that?

Also, why c-lightning still is connecting via non-proxied connection in case of non-existanse of loopback interface? it should just fail.. i dont get how the IP of my node is not exposed (on network level, i am not talking about announce-addr) if i am getting a working connection in this case.. on the other side i definetely can see clearnet IP in TCP headers i think..

**Comment by Saibato** [comment]
hi @bitcoin-software in therms of UX thats a good point I tried to address this in a
PR that warns the user about the implication his config might have https://github.com/ElementsProject/lightning/pull/3249/commits/48d6a227a903313e615e061927f3e3b3e761168b

**Comment by bitcoin-software** [comment]
@Saibato much thanks for your answers and commits! I will try TOR with 48d6a22 mentioned flags.
But i have feeling that you misunderstood me a bit. The problem i am talking about is not a DNS leak (while mentioning it has a valid point, yes, i agree), the problem is that connection happens at all, even by IPv4 address. For me as a node operator what i see: if i will try to connect to clearnet IPv4 address (without a FQDN, just by IP), with enabled `proxy` in `c-lightning`, the `c-lightning` will by-pass proxy for non-onion addresses.

**Comment by Saibato** [comment]
> (without a FQDN, just by IP), with enabled proxy in c-lightning, the c-lightning will bypass proxy for non-onion addresses, and for that reason the connection to that "other" node will happen on clearnet in fact.

The design allows to connect to onion address by use of the tor api in form of a socks5 proxy it provides.  There is no need to route and hide everything about the node over tor exitnodes.
Since we want to be found over our ip and the bitcoin like bootstrap.
 
The so called hidden part is a different realm, if you want to stay quite you should also
consider to provide non exit bridge relays for the Tor system for the bandwide you use, if you route all traffic routes over the exitpoints.
Also make sure dns/ip leaks are minimized by the options we provide in the lightning protocol and on the transport side. (--disable-dns and --always-use-proxy ) 

> P.S. i dont get how changing flags of TOR daemon can affect a way in what cln is making connections.. 

We change no tor options, all in regard what we proxy or not is done on our side.
please take a look at the revised draft #3249

Lightning is by default not designed to be hidden,
All in lightning is quite the opposite of staying hidden, since we by default as service want to be found connected, announced and routed over to grow the network.
The anonymity of lightning is mainly a feature in its protocol, that is independent from the transport layer, achieved by the onion protocol in lightning.   
And most users use the tor hidden onion address just as a convenient method to tunnel firewalls
and stay inbound connected behind a NAT.
At least we have that options in contrast to other implementations to go in to hidden quiet mode. 
       
Users should be aware what the hidden means and use the options we provide
and take care about that, c-ln at least try its best by defining some options that would help you to stay as hidden as possible, but in high sea and with tor you are at some point on your own what you do.

I totally agree with you, that the future of lightning is highly tied to how high the level of privacy and annon set will be.

**Comment by bitcoin-software** [comment]
Sorry, i was completely misunderstanding your previous messages. Now it is completely clear to me that those are c-lightning parameters and how they should be used. Thanks for your contribution!
