### ISSUE TITLE
HWI sign during commitment transaction

### ISSUE THREAD

**Issue by htczion** [ElementsProject/lightning#3355]
During funding transaction, HWI device can sign PSBT raw. 
For security concern, will C-lightning extend this **HW protect** for every **commitment** transaction in the future?

**Comment by cdecker** [comment]
That is certainly something that we are looking into. We deliberately made the `hsmd` subdaemon small and single-purpose so it can be swapped out with a more fleshed out version that can talk to an actual hardware security module or a HW wallet.

There have been some experiments, but as always the devil is in the detail. Since you need to sign off on changes to your channel, and therefore need to interactively sign the commitment transactions and others on-demand, the UX is really annoying at the moment. You wouldn't want to be woken at 3AM just to authorize your HW wallet to perform a fee update :wink: 

That is ok for funding channels or withdrawing funds from c-lightning since we know the user is online, but for the spontaneous updates we need a better UX first.

That means giving a signing device enough information and logic to automatically verify and sign off on changes to you channels. If you are interested in this kind of research there is a recent article [here](https://medium.com/@devrandom/securing-lightning-nodes-39410747734b) and a proof-of-concept implementation for c-lightning [here](https://gitlab.com/ksedgwic/liposig/wikis/Lightning-Policy-Signing-PoC).
