### ISSUE TITLE
Return erring channel direction from sendpay

### ISSUE THREAD

**Issue by s-tikhomirov** [ElementsProject/lightning#3537]
### Issue and Steps to Reproduce

Currently, `sendpay` returns the following information in case of an error ([docs](https://lightning.readthedocs.io/lightning-sendpay.7.html)): `erring_index`, `erring_node`, `erring_channel`, `failcode`, `channel_update`. It would be nice to also include the direction of the erring channel. A possible use case would be to do a route search with the erring channel / direction `exclude`d (in the format `AAAAxBBxCC/0`).

### `getinfo` output
```
{
   "id": "026e7cb4237b4042db75a991af29c2d7704780c8e7fbebe5fdbad8f38e958dfba5",
   "alias": "clightningM",
   "color": "026e7c",
   "num_peers": 6,
   "num_pending_channels": 0,
   "num_active_channels": 3,
   "num_inactive_channels": 4,
   "address": [],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9737
      }
   ],
   "version": "v0.8.0-40-g899f5de",
   "blockheight": 1666013,
   "network": "testnet",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/sergei/.lightning/testnet"
}
```

**Comment by cdecker** [comment]
It appears that the `erring_direction` is included in the result if a channel is the cause of the failure:

https://github.com/ElementsProject/lightning/blob/3b7d0e7a620486604b0143f79ee91b89ea543cb8/lightningd/pay.c#L185-L211

It has been since 7e41d6c9c4d42ec2d389038f26c82bdccd080837, but appears to be undocumented. I'll fix that :+1:
