### ISSUE TITLE
Using CookieAuthFileGroupReadable without specifying an explicit CookieAuthFile doesn't work.

### ISSUE THREAD

**Issue by dscotese** [ElementsProject/lightning#3548]
Following the instructions at https://github.com/ElementsProject/lightning/blob/master/doc/TOR.md and then running tor produced `[warn] CookieAuthFileGroupReadable is set, but will have no effect: you must specify an explicit CookieAuthFile to have it group-readable.`

I don't know how to specify an explicit CookieAuthFile, so I don't know if doing that will solve this, but I do know that tor is reporting the warning when I try to run it, and that running lightning with the config file changes from the documentation I linked produces `(version 0.8.0)d: Tor returned '513 Invalid key type`

**Comment by Saibato** [comment]
The Invalid key type is probably from an old tor version when used with statictor.

Please do a ` sudo tor --version` that should give you something like `0.4.4.0-alpha-dev (git-9b2eccc0604aaa319).` if your tor version is smaller than 0.4.x.x you should upgrade tor to use 
i.e. statictor since that works only for ed25519  v3 onions.  
autotor has a fallback to v2 so that will even work on older tor versions.

But even then it is possible you run with a standard tor installaton then i.e. on ubuntu or debian in access problems of the 
CookieAuthFile  /var/run/tor/control.authcookie that has only r on groups and is in user/group debian-tor  

You might want or have done a simple groupadd  ` sudo usermod -a -G  debian-tor  your-user-name`
But keep in mind that will be not active before you do  a  `sudo su your-user-name` or on reboot in that user. 
You can check with groups or groups  your-user-name if it worked.
hth

Ping @ZmnSCPxj , we could/should add this tor distro depend install hints to the md?

**Comment by dscotese** [comment]
I am closing this issue as I discovered, as @Saibato suggested, that I have an old version of Tor installed, which is because installing Tor on Ubuntu requires special handling as outlined at https://linuxize.com/post/how-to-install-tor-browser-on-ubuntu-18-04/

**Comment by vincenzopalazzo** [comment]
An update reference to install the tor on ubuntu from tor project https://www.linuxuprising.com/2018/10/how-to-install-and-use-tor-as-proxy-in.html
