### ISSUE TITLE
Plugin life-cycle on shutdown

### ISSUE THREAD

**Issue by TKone7** [ElementsProject/lightning#3664]
Hi together,
I am new to c-lightning but I am amazed by the flexibility and ease of use of the plugins. It's a lot of fun to use the `pyln` library, thanks a lot for this.

I wonder if there is a way for my plugin to know when the lightning process ends. I would like to do some clean up (as stopping another thread) when c-lighting shuts down. I was looking for event notifications or an equivalent to the `init` method (like `shutdown`), but couldn't find any. So is there a solution for my problem or might this be a future extension for the plugin functionality?
Regards
Tobias

**Comment by cdecker** [comment]
Thanks for the feedback @TKone7, we're rather proud of the plugin API we built 🙂

The plugin is started as a subprocess of the main `lightningd` process, and
will therefore receive either a `SIGTERM` or a `SIGKILL` signal if the parent
process (`lightningd`) terminates. Usually it should be a `SIGTERM` if the
process stops correctly, either due to receiving a signal itself, terminating
correctly due to a `lightning-cli stop` call, or due to Ctrl-C in the terminal
in which the process is currently in the foreground.

This means that, unless you explicitly detach through a double-`fork` call,
i.e., daemonize the plugin, you should be able to use the `signal` or `atexit`
modules in python to call something when the plugin is about to be
terminated. This doesn't work for `SIGKILL` since that doesn't call the signal
handlers, but in that case `lightningd` itself would not be able to intercept
and give notice to its plugins.

I'm a bit hesitant to add a notification about `lightningd` terminating, since
plugin developers might rely too heavily on such a promise to get a
warning. Like pointed out above, there are cases in which we can't provide
this feedback, and relying too much on a warning notification means that in
cases we can't provide that warning the plugin may end up leaving things
around.

Since you mention that you'd like to stop a thread when `lightningd`
terminates, that should happen automatically, since the subprocess gets killed
as a result of `lightningd` exiting, so any process internal resource will be
freed automatically. Notice that the threading model in python is a bit
strange in that a `threading.Thread` that was started without marking it as
`daemon` may keep the process running despite being orphaned. Since that's
something that you probably don't want, it's best to mark the thread as
`daemon` when constructing it:

``` python
t = threading.Thread(target, args, daemon=True)
t.start()
```

I think this is a good question, and if you'd like we can certainly add an
entry detailing this in the FAQ or the plugin docs.

**Comment by TKone7** [comment]
Hi @cdecker 
Thank you so much for this fast and extensive explanation. It surely already helped me for my specific case. You were right that the thread, à la: 
```python
t = threading.Thread(target, args, daemon=True)
t.start()
```
was stopped when the parent process stopped. So far so good.

However, I also wanted to learn how to work with signals in python, so I tried this as well. As I could learn from the documentation one can handle the different signals like this:
```python
signal.signal(signal.SIGTERM, handler)
```
Unfortunately, I was not able to get this to work inside my lightning-plugin. I tried to simply create an empty file with the following handler. 
```python
import signal, os

def handler(signum, frame):
    os.mknod("/home/bitcoin/handler.txt")
```
Then I registered it in the init method.
```python
plugin = Plugin(autopatch=True)
...
@plugin.init()
def init(options, configuration, plugin):
    ...
    signal.signal(signal.SIGTERM, handler)
```
But the file never gets created. Am I registering the handler at the right position? Or can you see what I am doing wrong?

Thanks for the great support.

**Comment by cdecker** [comment]
Fwiw there is now a notification that is sent to plugins when shutdown is being done, however plugins can never rely on either OS signals or the shutdown notification being dispatched (kill -9 anyone?), so make sure to not rely on them for anything security related.
