### ISSUE TITLE
memleak in log.c?

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#3681]
I was playing around with [heaptrack](https://github.com/KDE/heaptrack) and I noticed this memleak:

![Apr30-102728](https://user-images.githubusercontent.com/45598/80741186-15b06800-8ace-11ea-9c30-be11e2a412ef.png)

looks like at [vim lightningd/log.c +443](https://github.com/ElementsProject/lightning/commit/b210c9d91fc1a4c3bbb02bb38f1ea50231d691d4#diff-6196cd48b2e3744d0cb85c6a997fbc2fR443)

is this legit? (just want to be sure, since this is my first time using this tool). anyone else seeing this?

data: `heaptrack --analyze` [heaptrack.lightningd.18883.gz](https://jb55.com/s/heaptrack.lightningd.18883.gz)

**Comment by cdecker** [comment]
The in-memory log has been something that I wanted to remove for a while, since it accounts for a lot of memory and there are only a few places we actually use them (`getlog` JSON-RPC call, and `listpeers` afaik).

We could externalize this kind of log management into a plugin by adding a `log` notification and then removing the in-memory logs. That'd then allow things like log-shipping to an external log management tool, or alerting, or other things.

**Comment by whitslack** [comment]
I excised the in-memory log from my node since I have it logging to disk at the `DEBUG` level and don't want my precious RAM being wasted to hold redundant information. Since @cdecker mentioned that this is something he's been wanting to do anyway, I figured I'd share my work and maybe save him some effort. I think I was pretty thorough and correct in my modifications, but of course it's always good to have another set of eyes on any change.

https://github.com/ElementsProject/lightning/compare/v0.10.2...whitslack:no-memlog

**Comment by jb55** [comment]
was just closing old issues I had open, feel free to create a new issue if this is still a problem...

**Comment by SimonVrouwe** [comment]
> The in-memory log has been something that I wanted to remove for a while, since it accounts for a lot of memory and there are only a few places we actually use them (getlog JSON-RPC call, and listpeers afaik).

IMHO `getlog` command can be useful for debugging and experimenting to retrieve info from of recent log entries. And the `listpeers` "level" option to have a per-channel "log" field is quite handy!

Is the 10Mb memory usage really a problem?
https://github.com/ElementsProject/lightning/blob/f72a08c80261296f2649bb04c2f3b2552636d404/lightningd/lightningd.c#L177-L181
