### ISSUE TITLE
pyln.proto.wire should use coincurve PublicKey/PrivateKey types

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#3751]
Now we use coincurve elsewhere, seems a bit like it's reinventing the wheel here?

**Comment by ofek** [comment]
Any update?

**Comment by cdecker** [comment]
I'll take care of this for the next release. Shouldn't be too hard, and I'm working on a python implementation of the sphinx construction anyway.

**Comment by sr-gi** [comment]
I can take care of this one if you'd like @cdecker

**Comment by sr-gi** [comment]
Some questions regarding this so I tackle it.

Should the current interface for `PublicKey` and `PrivateKey` be preserved (to prevent any internal/external tools using it to break) or should the classes be completely deleted and adapt the rest of the `pyln.proto.wire` code using `coincurve` (and potentially any other dependant parts of the codebase)?

**Comment by cdecker** [comment]
I think we'd like to keep a wrapper class, just to maintain flexibility internally and keep external dependees happy.

**Comment by sr-gi** [comment]
Looks like the current version of `PrivateKey.serializeCompressed` is not working with `cryptography==2.8`. 

https://github.com/pyca/cryptography/blob/25494f96d57b8995ee2fde099146b1192582ee1b/src/cryptography/hazmat/backends/openssl/backend.py#L1752-L1755

There's no tests for this atm, so I'm guessing this passed unnoticed. Not that it's being used in any other part of the code, nor that would matter after this issue gets fixed since `cryptography` won't be used here anymore.

However, I don't know what the expected return for `PrivateKey.serializeCompressed` is supposed to be (type, format, etc).

Any clue?
