### ISSUE TITLE
How to unstuck payments?

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#3916]
I've managed to get some payments stuck in #3915 . If i run `listsendpays`, i see a lot of 'pending' payments. How do i fail these? I am unable to send payments or receive payments, as all of my channels already have a lot of active htlcs.

**Comment by ZmnSCPxj** [comment]
You cannot fail them.  You just have to wait them out.  `pay` has a `maxdelay` parameter which limits the amount of time you have to wait out a stuck payment.

**Comment by thestick613** [comment]
Most of them reverted. I had over 100 `pending` htlcs, now there are only 7.

**Comment by ZmnSCPxj** [comment]
Okay, seems fine?  Can we close this?

**Comment by thestick613** [comment]
I still have 7 pending HTLCs, with these timestamps:
         "created_at": 1596970304,
         "created_at": 1596970304,
         "created_at": 1596970305,
         "created_at": 1596970305,
         "created_at": 1596970305,
         "created_at": 1596970305,
         "created_at": 1596970305,

Shouldn't they have expired by now?

**Comment by cdecker** [comment]
The `expiry` parameter in the `listpeers` output will tell you at which height the HTLCs will expire.

**Comment by thestick613** [comment]
Something is broken:
```
listpeers  | grep \"htlcs
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []
               "htlcs": []

```

```
listpeers  | grep expiry
no output
```

```
listsendpays | grep -A 2 -B 9 pending | grep created_at
         "created_at": 1596970304,
         "created_at": 1596970304,
         "created_at": 1596970305,
         "created_at": 1596970305,
         "created_at": 1596970305,
         "created_at": 1596970305,
         "created_at": 1596970305,

```

They seem to be orphaned.

**Comment by thestick613** [comment]
Am i potentially losing funds with these stuck HTLCS?


      {
         "id": 5393,
         "payment_hash": "payment_hash_1",
         "partid": 348,  
         "msatoshi": 12074345,
         "amount_msat": "12074345msat",
         "msatoshi_sent": 12075357,
         "amount_sent_msat": "12075357msat",
         "created_at": 1596970304,
         "status": "pending"
      },
      {
         "id": 5397,
         "payment_hash": "payment_hash_1",
         "partid": 351,  
         "msatoshi": 11356038,
         "amount_msat": "11356038msat",
         "msatoshi_sent": 11357049,
         "amount_sent_msat": "11357049msat",
         "created_at": 1596970304,
         "status": "pending"
      },
      {
         "id": 5399,
         "payment_hash": "payment_hash_1",
         "partid": 359,
         "msatoshi": 11361588,
         "amount_msat": "11361588msat",
         "msatoshi_sent": 11362599,
         "amount_sent_msat": "11362599msat",
         "created_at": 1596970305,
         "status": "pending"
      },
      {
         "id": 5400,
         "payment_hash": "payment_hash_1",
         "partid": 363,
         "msatoshi": 11982223,
         "amount_msat": "11982223msat",
         "msatoshi_sent": 11983234,
         "amount_sent_msat": "11983234msat",
         "created_at": 1596970305,
         "status": "pending"
      },
      {
         "id": 5401,
         "payment_hash": "payment_hash_1",
         "partid": 366,  
         "msatoshi": 12103393,
         "amount_msat": "12103393msat",
         "msatoshi_sent": 12104405,
         "amount_sent_msat": "12104405msat",
         "created_at": 1596970305,
         "status": "pending"
      },
      {
         "id": 5402,
         "payment_hash": "payment_hash_1",
         "partid": 364,  
         "msatoshi": 11951859,
         "amount_msat": "11951859msat",
         "msatoshi_sent": 11952870,
         "amount_sent_msat": "11952870msat",
         "created_at": 1596970305,
         "status": "pending"
      },
      {
         "id": 5403,
         "payment_hash": "payment_hash_1",
         "partid": 361,  
         "msatoshi": 12410606,
         "amount_msat": "12410606msat",
         "msatoshi_sent": 12411618,
         "amount_sent_msat": "12411618msat",
         "created_at": 1596970305,
         "status": "pending"
      },

**Comment by cdecker** [comment]
No, the funds are safe. Either the payment attempts become unstuck, or the funds are returned once the HTLC times out. Since you have `partid`s I assume you initiated the payment, in which case the timeout is probably pretty substantial, but should last a couple of days at most (the timestamp puts them on August 9., but that's hard to believe, given the CLTV deltas on the network).

The absolute worst case that can happen is that the CLTV deltas are badly distanced along the path, which could result in the channel being closed, but that shouldn't happen in most cases (eventually an intermediate node will have a correct CLTV delta that allows it to pick up the sweep of the HTLC and return the preimage or timeout the upstream HTLCs, which would allow all upstream channels to stay active).

**Comment by cdecker** [comment]
> Narrator: @thestick613 sent @cdecker the `listsendpays` output, and @cdecker spent a bit of time delving into it

I built a [small tool](https://gist.github.com/cdecker/27c46e368b8f60754496d851dd72eb65) that goes through the payment attempts and tries to reconstruct the causal order in which they were performed. This is the output:

![thestick](https://user-images.githubusercontent.com/120117/98114653-d8c29500-1ea5-11eb-8e7e-e5ae5a490fd1.png)

It's the causal order in which the payments are executed, with color-coded outcome. As suspected this is one of the payments that predates our scaling of the presplit modifier and has resulted in 163 parallel first attempts out of the gate. All 7 attempts marked as `pending` are leafs of the attempt tree. The corresponding HTLCs not being present on the channels leads me to the following possibilities:

 - We were missing a state-transition in `master` at the time this payment was performed, leaving the `pending` state on the payment despite it being processed correctly.
 - A restart caused us to miss the state-transition since we weren't able to reconnect it with our in-memory representation (notice that the `pay` plugin is not restart-safe)

The latter option seems unlikely given that the attempts were not towards the end of the payment attempts according to their `created_at` timestamp (clustered around 12 seconds after start and well before the last attempt was started after 41 seconds).

So I'd argue this is a left-over from incomplete code being run from `master` that is unlikely to be usefully resolved no matter how much forensics we perform. Like I mentioned above, the funds are safe, no HTLCs are in-flight putting the channels at risk, and this is merely an accounting issue, so no need to worry :wink:

**Comment by thestick613** [comment]
From what i recall, the pay plugin crashed several times in that period, so maybe that was the cause.
Do i have to do anything else?
