### ISSUE TITLE
legacypay overpayed the invoice a bit

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#3932]
I payed a bolt11 invoice using legacypay. The amount encoded in the bolt11 was 499907 satoshi, however, this was outputed by the legacypay command:

```
   "msatoshi": 501908132,
   "amount_msat": "501908132msat",
   "msatoshi_sent": 501914643,
   "amount_sent_msat": "501914643msat",
   "created_at": 1597237826,
   "status": "complete",

```

What's happening? Is it normal?

**Comment by cdecker** [comment]
That seems totally normal to me:

 - 501908.132 sat - 499907 sat = 2001.132 sat fee
 - 499907 sat * 0.5% max fee = 2499.535 sat maxfee
 - 2001.132 sat fee < 2499.535 sat maxfee

What might be a bit confusing is that we overpaid the invoice amount (501908.132 sat > 499907 sat) which is due to the shadow routing, which pretends to continue on a longer route and adds bogus routing fees on top. This is ensured to be within the 0.5% fee budget, and enhances privacy, but you can disable it for future payments by using the `use_shadow` argument set to `false`:

```
lightning-cli -k legacypay bolt11=[bolt11] use_shadow=false
```

**Comment by thestick613** [comment]
I paid it on https://fixedfloat.com/, which told me that i overpaid the invoice by XXX sats.
Overpaying 0.5% seems like too much.

**Comment by ZmnSCPxj** [comment]
The 0.5% is the default fee percentage.  The fee budget is considered for use by the `pay` / `legacypay` command as its sees fit, and if it misleads a surveillor into thinking that you paid somebody else, that would be money well spent.  0.5% is tiny.  If you want smaller, you can reduce the budget as well.

**Comment by cdecker** [comment]
FWIW the amount fuzzing for `shadow_route` is no longer present if using multi-part payments (i.e., the `pay` command) since it can obfuscate the amount by splitting. MPP invoices will always be paid exactly to the satoshi.

**Comment by thestick613** [comment]
This should probably be off by default, and only enabled as a flag when paying. You can close this ticket. If you pay a 100$ invoice, 5$ is too much as a fee.

**Comment by ZmnSCPxj** [comment]
The fee limit is 0.5%, so paying a $100 invoice only incurs a $0.50 fee **at maximum**.  Note that the overpayment comes from the same budget as paying intermediate nodes *and* the same budget for the privacy-improving route randomization (not that route randomization has been operating since 0.7.x or thereabouts)

**Comment by thestick613** [comment]
`-k legacypay bolt11=BOLT11______BOLT11 use_shadow=false 
`
results in
```
{
   "code": -32602,
   "message": "unknown parameter: use_shadow"
}
```

**Comment by ZmnSCPxj** [comment]
`use_shadow` is a parameter used in testing only, and only exists in `DEVELOPER=1` mode.  Default build has `DEVELOPER=0`.

Just limit your fee budget.  You *are* considering your on-Lightning fees at some point, right? If you want an absolute limit on your fees, just set `maxfeepercent=0` and set `exemptfee` to your absolute fee limit in millisatoshis.
