### ISSUE TITLE
MPP causes "label" and "bolt11" data to disappear

### ISSUE THREAD

**Issue by fiatjaf** [ElementsProject/lightning#3939]
Neither `listsendpays` nor `listpays` with a given `payment_hash` return the `"label"` and `"bolt11"` parameters given when issuing the `pay` command. That only happens when there is more than one MPP shards in the `listsendpays` output.

Perhaps the first shard in the `payments` table should store this data so `listpays` will be able to pick it up later.

**Comment by ZmnSCPxj** [comment]
What version are you using?  We recently fixed a biunch of `listpays` problems with 0.9.0-1

**Comment by vincenzopalazzo** [comment]
I tried to reproduce this bug with the actual version of master, we can wait for the result of tests

This is the test implementation, maybe I don't understand the problem described here

https://github.com/vincenzopalazzo/lightning/blob/4b9b664545276a34bea8e7421b1f1b08264432e1/tests/test_pay.py#L3460-L3480

**Comment by fiatjaf** [comment]
Sorry, I always post the version information but forgot this time.
It's commit `639eaaf2b4dad02a761285ef96d45392b0230b9e`.

I'll get the latest master and see.

**Comment by cdecker** [comment]
These should have been fixed by #3927. Notice that it can't recover `bolt11` or `label` strings for payments that were performed without the fix, but they will store them correctly for all future payments.

For context: we used to pass those values to the DB only for the root payment in order to reduce the amount of duplicate data we store. That however meant that if the root payment isn't attempted (i.e., a call to `sendonion` wasn't done) then `lightningd` would never learn those details, and couldn't store them with the payment. This would happen if the `preplit` modifier split the root payment and then skipped that attempt. We now inherit that information to the children created by `preplit` so they shouldn't get lost anymore.

**Comment by cdecker** [comment]
From the [commit comparison between `639eaaf2b4dad02a761285ef96d45392b0230b9e` and current `master`](https://github.com/ElementsProject/lightning/compare/639eaaf2b4dad02a761285ef96d45392b0230b9e..f495363bc4c4f72c5a740901db4e283828aafa13) I can see that your version just missed that one update. Upgrading to either v0.9.0-1 or `master` should fix that.

**Comment by fiatjaf** [comment]
Ok, I had upgraded and was waiting for some action to happen so I could check again.
But this issue was more than properly addressed already. Thank you!
