### ISSUE TITLE
Getroute vs listchannels

### ISSUE THREAD

**Issue by d4amenace** [ElementsProject/lightning#3956]
This is a general question about these 2 api calls and which can be used in a particular scenario:

Let's say I have a node and I want to find and list all possible routes to another node using only 2 hops.   Let's also assume there are 4 routes, all with 1 node inbetween us and equal fees....Will getroute [id] display all 4 indirect channels? Or should I use listchannels null [source] to show all 4 indirect channels?

**Comment by ZmnSCPxj** [comment]
In theory `getroute` can find such a route if one exists, and be quicker on finding the route as well.  If you use `listchannels`, you slurp the data from `gossipd`, which sends it to `lightningd`, which prints out the data into ASCII, which sends it to your program, which then has to parse the data.  So if such a route exists, `getroute` will be quicker.

However, `getroute` returns exactly one route, and if you want to look for alternatives, you have to specifically `excludes` one or more of the nodes/channel-dirs in the returned route in order to progress.  Further, if you are interested in ***only*** 2-hop routes, `getroute` will scan *way* beyond that.  There is a `maxhops` argument, but that only prevents `getroute` from succeeding with a longer route, it does not prevent `getroute` from *searching for* a longer route, as its primary goal is to connect the source to the destination and maxhops only comes into play later.

**Comment by d4amenace** [comment]
Thanks!
