### ISSUE TITLE
"Could not parse destination address" for p2sh withdrawal destination

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/lightning#410]
This is problematic for users of multisig or segwit wallets.

**Comment by ZmnSCPxj** [comment]
Below are some changes needed to support P2SH (for confirmation with @cdecker @rustyrussell ):

1.  `bitcoin_from_base58` in `bitcoin/base58.c` needs to also return a `is_p2sh` flag.  It has to identify `version` byte == 5 as a P2SH mainnet address, and == 196 as a P2SH testnet address.
2.  The `hsm_sign_withdrawal` message in `hsmd/hsm_client_wire_csv` needs to include this `is_p2sh` flag too.
3.  The `sign_withdrawal_tx` function in `hsmd/hsm.c` needs to add this `is_p2sh` flag too, and generate the correct transaction output if `is_p2sh` is set.
4.  Withdrawal transactions are made by `withdraw_tx` in `bitcoin/withdraw_tx.c`, so this function should probably add a `is_p2sh` flag as input.  If this flag is set, it should call `scriptpubkey_p2sh_hash` instead of `scriptpubkey_p2pkh` when assigning to `tx->output[0].script` (but there may need to be some conversions between types here).
5.  Finally the `json_withdraw` function needs to keep track of this `is_p2sh`, load it from `bitcoin_from_base58`, send it to hsm, and also to its own call of `withdraw_tx`.

**Comment by ZmnSCPxj** [comment]
@cdecker @rustyrussell this is now my current plan, if you think it is a solid plan, I shall implement it:

1.  Modify `bitcoin_from_base58` to return an `is_p2sh` flag and add this flag to its only caller, `json_withdraw`.  For this step, `json_withdraw` will error if this flag is set after a successful call to `bitcoin_from_base58`.
2.  Modify `withdraw_tx` to accept a `scriptpubkey` to withdraw into rather than a `const struct bitcoin_address *destination`.  Its callers, `json_withdraw` and `sign_withdrawal_tx`, need to call `scriptpubkey_p2pkh` directly to generate the `scriptpubkey` to pass into `withdraw_tx`.
3.  Change the `hsm_sign_withdrawal` message to accept a `scriptpubkey` instead of a `pkh`.  Modify `sign_withdrawal_tx` to get the `scriptpubkey` from this field instead of calling `scriptpubkey_p2pkh`, and modify `json_withdraw` to pass in the `scriptpubkey` to this message.
4.  Rearrange the `json_withdraw` code.  Instead of failing when `bitcoin_from_base58` returns false, it initializes `scriptpubkey` to `NULL` and loads it using `scriptpubkey_p2pkh` if `bitcoin_from_base58` returns true (and `is_p2sh` is false).  Show the "Could not parse destination address" error if the `scriptpubkey` is still `NULL` after the address parsing stage, and add a comment here that this point is where new address types will be added.
5.  Factor out the address parsing code to a new function, `scriptpubkey_from_address`, which returns a (possibly `NULL` meaning parsing failure) `scriptpubkey` from a length-delimited ASCII string.  Include the comment of where new address types will be added.  Also returns the `testnet` flag, and still fails if `is_p2sh` is set.
6.  Finally, check `is_p2sh` is set and format the `scriptpubkey` with `scriptpubkey_p2sh_hash` if so in the new `scriptpubkey_from_address` function.
7.  Create a new issue "Bech32 BIP173 direct SegWit address is not supported yet"

**Comment by ZmnSCPxj** [comment]
As it turns out, there exists already a `psh_from_base58` address.  So I shall largely skip step 1 above, and change step 6 to add `p2sh_from_base58` as yet another address type in the `scriptpubkey_from_address` function.
