### ISSUE TITLE
support for lightning pool

### ISSUE THREAD

**Issue by LightningHelper** [ElementsProject/lightning#4215]
Is it possible to add support for the lightning pool?
https://lightning.engineering/posts/2020-11-02-lightning-pool/

I did not managed to understand how it works exactly, but as it is a non-custodial I assume any implementation can connect to it.

**Comment by ZmnSCPxj** [comment]
Possibly out of scope for *this* project.  Though if Lightning Pool starts trying to standardize their new channel opening proposals, we would have to implement that here.

Why do you need support for Lightning Pool specifically?  If you need incoming capacity, [CLBOSS](https://github.com/ZmnSCPxj/clboss) handles that and more, and I am wondering if I should implement Lightning Pool support in CLBOSS.  On the other hand the current mechanisms in CLBOSS seems adequate *so far*.

**Comment by niftynei** [comment]
> as it is a non-custodial I assume any implementation can connect to it.

Lightning pool channels don't comply to the BOLT spec, the commitment transaction scripts have been modified.

**Comment by ZmnSCPxj** [comment]
>Lightning pool channels don't comply to the BOLT spec -- the commitment transaction scripts have been modified.

I thought the current initial version does not have this yet --- it is in their whitepaper but not quite yet in their implementation?  My understanding from their initial release announcement was that they still use standard Lightning channels for now.  Though if that has changed since the announcement, well ---

**Comment by niftynei** [comment]
Oh I haven’t checked their implementation, that may very well be the case.

If so, then they’re not incentiving the channel contract time. I’d be
surprised if they shipped without this. Will investigate.

**Comment by ZmnSCPxj** [comment]
My understanding is that since the pool server is a single centralized one, they impose the channel contract time by demeriting a reputation score when the channel is closed before the contract time expires.

**Comment by niftynei** [comment]
Ah that’s clever. Man, aren’t reputation systems handy lol.

**Comment by MrManPew** [comment]
> Why do you need support for Lightning Pool specifically?

Mainly thinking that it would be a shame if you can "Stack" your channels only using lnd...

> Lightning pool channels don't comply to the BOLT spec

Thats a stinky move...

**Comment by ZmnSCPxj** [comment]
Yes, too bad third-party reputation systems are fundamentally tr\*st requiring.  Personally, my concern is that the central server does too much.  It is one thing where a Wasabi central server is expected to have lots of one-time interactions with wallets, and you can get a new identity (Tor routing connection) and you'd get basically the same service from the central server (the server *does* identify you by UTXO but you can change that, at cost, by a self-paying transaction, and if you manage to get in a mix then your incoming UTXO is not associated with your outgoing UTXO, so the identity is fundamentally temporary).  CLBOSS relies on Boltz exchange to get incoming capacity, so it is another central server, but again you just have one-time interactions with the Boltz exchange, and the protocol with the server does not include identity and you can connect over Tor and get basically the same service from the central server each time regardless --- Boltz just issues an invoice and we can pay it from any node and Boltz never learns which node we use (well, CLBOSS self-identifies as `clboss` in the UA string, I should probably go the Tor Browser route and use "Windows Firefox", but who points a browser at an RPC endpoint?).

With Pool, the makers have to have a stable identity tied to their node IDs.  Presumably takers also have that (maker has to know pubkey of node they make channel to, after all, presumably the server is how the maker learns this).  Then the algorithm the server is using to match them up is unknown (even if they open-source it, nothing really assures you that the *actual* server is using the open-source code unless they give enough data for it to be validated), allowing the possibility that certain makers and takers are censored.

(Sure it is closed-bid, but maybe you can reveal the bid later to validate?)

On the other hand I could be bitter since CLBOSS and Lightning Pool basically do the same thing --- get incoming capacity --- but Pool got into Bitcoin Optech and CLBOSS did not, so there is also that, which is why I am trying to think about whether I can get CLBOSS to support Pool rather than dismiss Pool outright.

**Comment by ZmnSCPxj** [comment]
> Mainly thinking that it would be a shame if you can "Stack" your channels only using lnd...

What do you mean by "stack"?

On the C-Lightning side, CLBOSS will manage your funds for you and should be able to get you incoming capacity, and will also build out channels to possible destinations (using various heuristics).  It falls short in that there is no way for a new merchant to signal to anyone that they would appreciate incoming capacity.

CLBOSS does centralize its incoming-capacity-generation around the Boltz exchange, but it is easier to replace Boltz exchange than to replace the server in Pool, since Boltz does less than Pool (and there is an open-source Boltz server implementation, though built on top of lnd).

Otherwise CLBOSS is significantly more decentralized --- other than Boltz it does not require any particular single server to survive the coming robot apocalypse (which I will not trigger, promise), and Boltz should be easier to replace.  Boltz even has a viable competitor, Lightning Loop (not Pool), so one of the things I should be doing would be to support Loop in CLBOSS as well (they use different protocols, and it took me a stressful two weeks to implement the Boltz protocol correctly, so I am largely procastinating on implementing the Loop protocol because of that).

> > Lightning pool channels don't comply to the BOLT spec
>
> Thats a stinky move...

Most BOLT updates are of the form "show us an implementation first", so it does make sense for them to implement it first, *then* request an update to the BOLT spec later.

**Comment by MrManPew** [comment]
Thank you for all the information!

> What do you mean by "stack"?

Users of lightning pool can earn sats by renting their channels (probably "stack" is not the correct word)
"Over the last few weeks, participants in our closed mainnet alpha have been earning a yield on real bitcoin without trusting a third party, as Pool uses the bitcoin blockchain as its clearing and security layer. Their channels sold through Pool have been transformed into brand new bitcoin-native yield-bearing assets. In these early days, Pool channels will have a fixed two-week duration, but as Pool matures we plan to add additional markets with other durations."
https://lightning.engineering/posts/2020-11-02-lightning-pool/

**Comment by ZmnSCPxj** [comment]
Yes, which is another reason to consider putting Pool into CLBOSS.  C-Lightning itself, not so much.  Note in particular that AFAIU Pool client is a separate program that runs on top of `lnd`; it would be in a similar position as CLBOSS and C-Lightning.

The economic basis of Lightning Pool is sound --- if I know that I need incoming liquidity because I am deploying a new online store or similar, and that I expect that this will earn me more funds compared to the case where I have no incoming liquidity, then I should be willing to pay up to just below my projected difference in net earnings (compared to not having Lightning liquidity) in order to get the incoming Lightning liquidity.  If I know I have extra liquidity lying around not earning anything useful, I should be looking for such signals from merchants.

What is lacking is a signaling layer for this kind of market.  Lightning Pool provides this signaling layer, but this uses a centralized server, which, in theory, can be co-opted by powerful actors in order to censor certain signals.  Even if Lightning Labs is honest now and does not censor, it can be bought out or otherwise coerced later once the Lightning network is dependent on it ("too big to fail").

So really, what we need is a signaling layer.  For example, a forwarding node with extra liquidity can raise a featurebit in its gossiped node details.  New merchants can contact multiple such forwarding nodes and request bids for them.  The new merchant is the only one to receive those bids, so it is closed-bid and prevents front-running as well.  Then the merchant requests a channel from a selected forwarding node.  To pay for this, the merchant generates a preimage and its hash, then sends out a standard Lightning payment to the forwarding node.  The forwarding node then opens a channel in two steps: first it onchain pays to an HTLC variant where the hashlock-branch requires signature of both merchant and forwarding node, and then it has a transaction (signed by both) spending the hashlock-branch and paying out to the normal channel opening outpoint.  This does not require a change in BOLT specs or even a change in `lightningd` itself, just a new plugin, because of the `fundchannel_start`/`fundchannel_complete` split.  The preimage required in the hashlock-branch of the first step is the preimage that was generated by the merchant and used in the payment to from the merchant to the forwarding node.  This is just bog-standard submarine swaps like Boltz or Lightning Loop, except you are buying a channel instead of buying onchain funds.

Now, how do we enforce that the channel *remains* open for the contract period?  During channel opening we already know the TXID of the funding tx and the outpoint for the channel.  The advertising forwarding node can sign, using its node ID, a short message including the funding outpoint details, and the contract period.  This is provided by the forwarding node between the `fundchannel_start`(`open_channel`) and `fundchannel_complete`(`funding_signed`) commands.  Then if the channel is closed before the contract period,  the merchant can take this message, plus the closing transaction of the channel, plus a proof that the closing transaction was included in the blockchain before the contract period ends, to create a fraud proof.  It then looks for other forwarding nodes advertising the channel-making service and sends the fraud proof to them.  Since those forwarding nodes are competing, they have every incentive to store fraud proofs of their competitors, in order to convince prospect clients (merchants buying incoming capacity) to not go to their competitors, xref. Trezor v Ledger and Wasabi v Samourai.

Of course, the flaw here is that the *merchant* can close the channel during the contract period, then generate the fraud proof.  An evil forwarding node can spin up a couple thousand merchant nodes, pay for new channels, then close them immediately, then gossip the generated fraud proofs and ruin the reputation of every other forwarding node in the market.

It was at this point that I stopped thinking and started watching K-ON!! instead.

**Comment by cdecker** [comment]
Now that dual-funding and liquidity ads are implemented as experimental features, and the spec proposals for it are under review I think we have a less centralized alternative to Pool, including the lockup period that takes the role of the reputation system.

I think this addresses the issue, despite not directly integrating with Pool directly. Do you think we can mark this as resolved?

**Comment by ZmnSCPxj** [comment]
I would agree as well.

**Comment by LightningHelper** [comment]
me2!
