### ISSUE TITLE
Ligthningd assumes plugin locations and ignores --plugin-dir

### ISSUE THREAD

**Issue by artlav** [ElementsProject/lightning#4223]
### Issue and Steps to Reproduce

0.9.2 release, maybe 0.9.1, not 0.9.0

1. Install lightningd into a custom directory (both bin and libexec content in one place), put plugins in a subdirectory.

2. Specify the directories used:

`--lightning-dir=/data/btc/ln_run --bitcoin-datadir /data/btc/core_btc_chain --plugin-dir=/data/btc/ln_run/plugins`

3. Try running it. It would complain about plugins: 

`error starting plugin '/data/btc/ln_run/../plugins/autoclean': opening pipe: No such file or directory`

If you symlink the plugins to ../plugins, then it complains about duplicate plugins.

`plugin-bcli: Killing plugin: Could not register method "getrawblockbyheight", a method with that name is already registered`

The issue is that in lightningd.c:497 it makes an assumption:

`/* If we're running in-tree, all the subdaemons are with lightningd. */`

This assumption is not always true, and making it take priority over user's explicit order to use --plugin-dir is a problem.

(Commenting out the following plugins_set_builtin_plugins_dir piece fixes the issue)

**Comment by ZmnSCPxj** [comment]
`--plugin-dir` does *not* specify where the *builtin* plugins are placed.  It specifies where *user-specific* plugins are placed.  Messing with how `lightningd` is installed is not what you should do --- use `make install` to install.  If you want to override paths, override it during build: `make libexecdir=${WHEREVER}`, then `make libxecdir=${WHEREVER} install`.  Note that you have to install builtin plugins inside the specified `libexecdir` because that is the formal place to install builtin plugins.

If you really  want to override the builtin plugins, you need a `--clear-plugins`.  At which point `lightningd` will forget it had builtin plugins.

Why do you need a custom installation location?  For the purposes of most package managers, we support `$DESTDIR`, which package managers usually use.

**Comment by artlav** [comment]
Hm, on the "why' - i compile clightning myself, and don't want to have it smeared across the filesystem and have to hunt down which files went where the last time.

In general i like to have programs localized to their own directories when they are not handled by a package manager (think package bundles in macos).

Is there a stable way to achieve this? None of it is in PATH or supposed to be manually invoked.

I'm not attached to the specific file placement, only that the placement is relative or runtime-specified.

**Comment by ZmnSCPxj** [comment]
You can use `DESTDIR`, which will install the relative pathnames in the "correct" position.  `lightningd` searches for its subdaemons and builtin plugins relative to its own binary, so you can `make DESTDIR=/clightning/location install`.  Then `/clightning/location/usr/local/bin/lightningd` should be able to find its subdaemons and builtin plugins without any additional flags.

`make installcheck` (which is run by the CI) internally uses `DESTDIR` to "install" `lightningd` in a temporary directory and, from the temporary dir, check that `lightningd` can find its subdaemons and builtin plugins, so we know that `DESTDIR` is working.

**Comment by ZmnSCPxj** [comment]
@artlav has your use-case been adequately addressed?

**Comment by artlav** [comment]
I think so, yes.

I would have preferred something like a `--builtin-plugin-dir=` for completeness of user configurable path set, but this works too.

**Comment by ZmnSCPxj** [comment]
okay to close?
