### ISSUE TITLE
unreserveinputs gives me " "unknown parameter: cHNidP..."

### ISSUE THREAD

**Issue by gabridome** [ElementsProject/lightning#4251]
### Issue and Steps to Reproduce
```
lightning-cli  utxopsbt all 10 40 "[\"3f...:1\"]"
{
   "psbt": "cHNidP....",
   "feerate_per_kw": 253,
   "estimated_final_weight": 311,
   "excess_msat": "12...msat",
   "reservations": [
      {
         "txid": "3f2......",
         "vout": 1,
         "was_reserved": false,
         "reserved": true,
         "reserved_to_block": 659811
      }
   ]
}
```

If I repeat the command, obviously:

```
lightning-cli  utxopsbt all 10 40 "[\"3f23...:1\"]"
{
   "code": -32602,
   "message": "UTXO 3f23...:1 already reserved"
}
```
So I try to unreserve:
```
lightning-cli unreserveinputs cHNid...
{
   "code": -32602,
   "message": "unknown parameter: cHNid..
}

# maybe with quotes?

lightning-cli unreserveinputs "cHNid..."
{
   "code": -32602,
   "message": "unknown parameter: cHNid..
}
```
Also, any advice on how to set the startweight parameter?
EDIT: found!
>EXAMPLE USAGE
>"Let’s assume the caller is trying to produce a 100,000 satoshi output."

In https://lightning.readthedocs.io/lightning-fundpsbt.7.html

### `getinfo` output
{
   "id": ".....",
   "alias": "...",
   "color": "...",
   "num_peers": 1,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "torv3",
         "address": ".....onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9735
      }
   ],
   "version": "v0.9.2",
   "blockheight": 659741,
   "network": "bitcoin",
   "msatoshi_fees_collected": 8384703,
   "fees_collected_msat": "8384703msat",
   "lightning-dir": "/home/..../.lightning/bitcoin"
}
```

**Comment by cdecker** [comment]
This is most likely related to #4287, i.e., the PSBT is not recognized
as a valid parameter because `lightning-cli` detects the trailing `=`
and infers that key-value-mode is desired, but then splitting keys and
values results in invalid keys being matched against the parameter
list.

This can be addressed by manually switching to key-value mode with
`lightning-cli -k unreserveinputs psbt=cHNid...` this will split keys
and values at the correct position, i.e., after `psbt=`, and from
there on it works as expected. Notice that this is limited to the
`lightning-cli` tool which is trying to be too clever for its own
good. Other JSON-RPC clients such as `pyln-client` are not impacted.

**Comment by cdecker** [comment]
As for your second question on how to use `startweight` it's basically
the size of the transaction before calling `utxopsbt`, i.e., the size
of the outputs and the shared tx fields such as nLockTime, the vin and
vout counters, etc.

Since you use rather a lot of arguments, some of which I expect are
there just so you can get to the positional arguments you really want
to use, I think key-value mode is much easier for you to use: it
allows skipping arguments you don't want to change, and it doesn't
require you to remember the position of all params, rather you can
specify them in any order.
