### ISSUE TITLE
Base64-strings are not recognized as arguments to lightning-cli

### ISSUE THREAD

**Issue by fiatjaf** [ElementsProject/lightning#4287]
1. If they are passed directly as `'<base64>'` an odd error is returned, "unknown parameter".
2. The same thing works with a normal string ("alskdnas"), maybe it's because the base64-encoded thing has "/".
3. But then if we pass it with `-k key='<base64>'` then it works.

### Issue and Steps to Reproduce

```bash
~> ./cli/lightning-cli --network regtest signpsbt 'cHNidP8BAHEBAAAAAZ+dQXWMU0UUQW5guh1gAqRk6qV1EfswIxDz/l6pI4BYAAAAAAD/////AuQGAAAAAAAAFgAUNiXEouqXR2CoFjaP0V3ncVlEdue0RKASAAAAABYAFKswhKbTAJ6fHwhnBttaS62vUkitAAAAAAAAAAA='
{
   "code": -32602,
   "message": "unknown parameter: cHNidP8BAHEBAAAAAZ+dQXWMU0UUQW5guh1gAqRk6qV1EfswIxDz/l6pI4BYAAAAAAD/////AuQGAAAAAAAAFgAUNiXEouqXR2CoFjaP0V3ncVlEdue0RKASAAAAABYAFKswhKbTAJ6fHwhnBttaS62vUkitAAAAAAAAAAA"
}

~> ./cli/lightning-cli --network regtest signpsbt alskdnas
{
   "code": -32602,
   "message": "psbt: Expected a PSBT: invalid token '\"alskdnas\"'"
}

~> ./cli/lightning-cli --network regtest signpsbt -k psbt='cHNidP8BAHEBAAAAAZ+dQXWMU0UUQW5guh1gAqRk6qV1EfswIxDz/l6pI4BYAAAAAAD/////AuQGAAAAAAAAFgAUNiXEouqXR2CoFjaP0V3ncVlEdue0RKASAAAAABYAFKswhKbTAJ6fHwhnBttaS62vUkitAAAAAAAAAAA='
{
   "code": -1,
   "message": "Aborting PSBT signing. UTXO 588023a95efef3102330fb1175a5ea64a402601dba606e411445538c75419d9f:0 is not reserved"
}
```

### `getinfo` output

```json
{
   "id": "02812bb5806368e1623ae62635c32747e23a7edd3be0f2790b217f49748b84b33b",
   "alias": "LIGHTNINGCHEF-0.9.1-360-g5e71de7",
   "color": "02812b",
   "num_peers": 5,
   "num_pending_channels": 1,
   "num_active_channels": 3,
   "num_inactive_channels": 1,
   "address": [],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9738
      }
   ],
   "version": "v0.9.1-360-g5e71de7",
   "blockheight": 955,
   "network": "regtest",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/fiatjaf/.lightning/regtest",
   "warning_bitcoind_sync": "Bitcoind is not up-to-date with network."
}
```

**Comment by ZmnSCPxj** [comment]
The issue is that many Base64 encodings tend to include an `=` character, which is autodetected by our naive `lightning-cli` code as you using the `param=value` format (yes, `lightning-cli` does autodetection of `-k` mode).  The workaround is to use `-k`mode explicitly, as you discovered.  The issue is completely in `lightning-cli`, and will not occur if you use programmatic interfaces.

We could try to see if an arg parses to Base64 and suppress the `-k` autodetect, but personally I am wary of adding [more magic](http://www.catb.org/jargon/html/magic-story.html) to the autodetect.  And because the autodetect already exists, it is likely somebody already depends on it, so it's difficult to remove as well.

**Comment by fiatjaf** [comment]
I didn't know there was autodetect, I always use `-k` explicitly.

**Comment by ZmnSCPxj** [comment]
> In fact it would be better if no autodetect existed event.

I broadly agree, except it might break the existing script of somebody.
