### ISSUE TITLE
Keysend enabled on LND but feature bit 55 missing in node announcement

### ISSUE THREAD

**Issue by hMsats** [ElementsProject/lightning#4299]
### Issue and Steps to Reproduce

`keysend` is working for c-lightning version `v0.9.2-77-g23d4e53` but not for version `v0.9.2-126-gd971e3d` because it generates the error `feature bit 55 missing in node announcement`.

So it seems that on LND `keysend` is enabled but the feature bit 55 is nonetheless missing. It's not clear to me if this is a c-lightning or LND error or shortcoming.

**Comment by cdecker** [comment]
We signal support for features in the node announcements in the gossip. It takes a while for the node announcement to be sent (not sure how often lnd sends them) and it takes a while for it to reach every key on the network. So this might be a simple issue of a missing update, which causes us to report the error on the preflight checks so to speak.

Could you include the info from `lightning-cli listnodes [recipient_id]` which should include the features.

**Comment by hMsats** [comment]
The node is on 24/7, it outputs:

```
{
   "nodes": [
      {
         "nodeid": "021779d56f6992431e959991a664d678a2f41054073adb48c5a351d791c9cb0781",
         "alias": "Banana!🍌",
         "color": "ffe135",
         "last_timestamp": 1609084278,
         "features": "8252a1",
         "addresses": [
            {
               "type": "ipv4",
               "address": "212.51.132.226",
               "port": 9735
            }
         ]
      }
   ]
}
```

**Comment by cdecker** [comment]
Indeed bit 55 which we interpret as keysend as reverse engineered from lnd is not set:

```
(0x8252a1 >> 55) &0x01 = 0
```

So that warning is correct. It may still be stale information because we haven't seen a newer node announcement, but if this persists then the recipient doesn't signal support correctly. This of course assumes that lnd didn't change the feature bit without telling us.

**Comment by hMsats** [comment]
Well same thing for the node with alias "BALANCER-Keysend-Enabled" (036bd7addc94c938d9db556d967929d8a531a4187e6a8b3aee2dc6be76f50c20bc). Keysend works with c-lightning version `v0.9.2-77-g23d4e53` but same error message for `v0.9.2-126-gd971e3d`. Listnodes gives `"features": "02a2a1"` which of course doesn't have feature bit 55 set to 1. So maybe it's better for the time being to display the error message but try the keysend payment anyway.

**Comment by cfromknecht** [comment]
> This of course assumes that lnd didn't change the feature bit without telling us.

@cdecker there has never been a feature bit to signal keysend in lnd. AFAICT the 54/55 was never standardized in the RFC (e.g. what it contexts it should be announced in, presumably only node ann?). Currently if a node supports TLV onion lnd will attempt the payment, and assume they don't support it when receiving IncorrectPaymentDetails.

There hasn't been much effort on our part to standardize because keysend will be made obsolete by https://github.com/lightningnetwork/lightning-rfc/pull/658 (or the rewrite coming soon-tm 😉), which generalizes the technique to more than one HTLC.

**Comment by cdecker** [comment]
Good point, I think I remember pulling the featurebit 55 from Joost's original implementation and interpreting it as a necessary opt-in, but if you guys just try and see what sticks we'll do the same. I think I'll still use featurebit 55 to explicitly signal support, just because it's already implemented and I prefer having explicit opt-in.

**Comment by hMsats** [comment]
Implemented your changes and that made  `keysend` work again :-)

**Comment by hMsats** [comment]
Tested it and this seems to solve this issue. Closing.
