### ISSUE TITLE
Add [in/out_channel_id] params to listforwards

### ISSUE THREAD

**Issue by hosiawak** [ElementsProject/lightning#4305]
Currently `listforwards` returns all forwards across all channels. I think I can add `[in_channel_id]` and `[out_channel_id]` optional params to it to make it run much faster and be more flexible (eg. in my case I'm interested only in forwards for a particular in or out channel.

Additionally (while I'm on it) I could add `[status]` param (I'm interested only in settled forwards).

I think I can do this if someone gives me a green light (maybe @cdecker ?)

**Comment by darosior** [comment]
But these fields are [already present](https://lightning.readthedocs.io/lightning-listforwards.7.html#return-value) ?

**Comment by cdecker** [comment]
> But these fields are [already present](https://lightning.readthedocs.io/lightning-listforwards.7.html#return-value) ?

Yes, but he is asking for the ability to query only for entries that match his criteria.

Generally speaking i think this is a great idea, and we should be adding better querying capabilities to many of the `list*` commands. I'd like to eventually have a generic query framework that allows the user to both drill down on the specific entries as well as adding paging support. However that may be a longer term improvement that needs to be carefully designed.

In the meantime I think having a simple way to specify what needs to match is a good first approximation. But let's try to set things up so we can later extend / migrate if we come up with a good solution. Logically speaking I'd aim for SQL-like semantics, since often we translate into SQL queries. For now let's make sure keys match the keys in the result, i.e., `in_channel`, `out_channel` and `status`. If multiple are specified we logically `AND` the conditions.

**Comment by mb300sd** [comment]
Filtering for the last x forwards, settled vs failed would be nice as well. With a large node, listforwards takes several seconds and filtering/sorting with jq several more.

**Comment by hosiawak** [comment]
This was merged into master in #4349 

> Filtering for the last x forwards, settled vs failed would be nice as well. With a large node, listforwards takes several seconds and filtering/sorting with jq several more.

@mb300sd - I think it's worth discussing a generic pagination system in a separate issue because it would be useful in most other RPC calls that return long lists. `listforwards` is the most obvious one of course.

I don't think I'm ready to tackle this yet so I'll leave this open to discuss to whoever wants to tackle it.
