### ISSUE TITLE
Changes needed for Liquid

### ISSUE THREAD

**Issue by fiatjaf** [ElementsProject/lightning#4308]
What should be considered when running a node on Liquid?

I was thinking that since blocktimes are 10x faster on Liquid all CLTV and CSV times should be multiplied by 10, does that make sense? Does c-lightning do that already automatically? Are there other considerations I should have in mind?

**Comment by cdecker** [comment]
Good question. We currently do not adjust CLTVs for the faster blocktime, but we probably should.

Adding a scale-factor to `chainparams.c` seems like the simplest option, but would require us to go through all the places we compute CLTVs and scale them accordingly.

**Comment by fiatjaf** [comment]
How should the user go to fix that on their side? What configs to change?
Are there any other differences besides the blocktimes?

An unrelated question: wouldn't it be possible to just use the Bitcoin codebase and apply it to Liquid directly? Without doing any of the confidential transactions thing, Liquid still works with unconfidential transactions, right?

**Comment by cdecker** [comment]
> How should the user go to fix that on their side? What configs to change?
> Are there any other differences besides the blocktimes?

I can't think of any other parameters that differ. Setting the CLTV delta to something that you feel comfortable should be sufficient, but we should definitely also scale the default, otherwise the CLTV choices of different nodes might not overlap, and the negotiation might fail.

> An unrelated question: wouldn't it be possible to just use the Bitcoin codebase and apply it to Liquid directly? Without doing any of the confidential transactions thing, Liquid still works with unconfidential transactions, right?

I'm sure the elements team can shed more light on this, but from the tx and block format alone there are already quite a few differences that'd make this hard. Each transaction has its fee materialized as an extra output. All outputs have an asset tag added, and a proof (which is empty for non-confidential types). Blocks also have a new proof that isn't present in the bitcoin block. In addition to these, I think there were also quite a number of fixes that were added, since it was a new network we didn't have to keep them broken for backward compatibility (checkmultisig popping an extra element off the stack, ...)

Pretty sure the elements team is maintaining a patchset on top of bitcoind, so that'd be the place to look for details, but the tldr is "it's harder than it may appear initially" :wink:

**Comment by fiatjaf** [comment]
Another thing I noticed is that a route between two Liquid peers returned by `getroute` is always `legacy` even though I'm using the latest c-lightning.

**Comment by cdecker** [comment]
> Another thing I noticed is that a route between two Liquid peers returned by `getroute` is always `legacy` even though I'm using the latest c-lightning.

That might be an issue with the `node_announcements` in the gossip, since we identify the destination's capabilities based on their announcements and we default to `legacy` as a safe fallback option. If you query your `gossipd` for the destination with `lightning-cli listnodes [dest_node_id]` do you get just the `node_id` or the full information?

**Comment by fiatjaf** [comment]
I get just the `nodeid`.

**Comment by cdecker** [comment]
> I get just the `nodeid`, both for myself and for the other node (which is also myself).

Yep, that sounds like an issue with the `node_announcement` then. Can you debug `gossipd` to see where it fails?

**Comment by fiatjaf** [comment]
How do I do that?
