### ISSUE TITLE
pay $invoice doesn't work, even though i have direct channel to node, and legacypay says "message": "Route wanted fee of 47005700msat"

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#4387]
I'm running `v0.9.2-448-gd134580`

I tried paying an invoice which failed, so i decided opening a direct channel to that node. After i opened the channel, i tried again to pay, but it also failed. I then tried to do legacypay, so this showed up:

```
{
   "code": 206,
   "message": "Route wanted fee of 47005700msat"
}

```

I'm also running the rebalanceall and feeadjust plugins.

What does that mean?

**Comment by cdecker** [comment]
Hard to tell, could you include the logs for a `pay` attempt, and the `listpeers` output, so we can check what might be the issue. You can also share them privately with us if you prefer that.

**Comment by thestick613** [comment]
The node was ACINQ, and they were forwarding the payment to a BLW wallet which was offline.
I've also received these error messages:
         "shadow": "No suitable channels found to 0242XXX(the blw node id). ",                                                
         "message": "failed: WIRE_CHANNEL_DISABLED (reply from remote)",                                                                                       

I know there's a trick where you can generate an invoice which hides your real node id behind another one, and the issue is probably related to this.

**Comment by cdecker** [comment]
Well, that's pretty much the answer: channel disabled means that the recipient is offline (thus the channel was temporarily disabled, as opposed to closed). You cannot send a payment to a node that is offline, since they need to acknowledge the incoming payment. If the node failing the payment were to hold onto the payment we'd be holding onto the liquidity along the entire path, which is detrimental to the network as a whole.
