### ISSUE TITLE
[Feature Request] waitanyinvoice

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning#439]
I am looking into lightning as Eclair and LND as standing now does not provide the features I need.

I am creating BTCPay, an open source payment processor for Bitcoin, and plan to have lightning integration.

I see that `waitinvoice` is very near from what I want but it has one big flaw:

What if BTCPay has 100 concurrent invoices? (let's say a spammer create lots of invoices and never pay them) I guess that RPC server will start sending 500 error as the queue is reached and if not the case, BTCPay socket client ports would be soon exhausted.

A feature I would really need is `waitanyinvoice` so BTCPay can have 1 call for all invoices it is waiting.
`waitanyinvoice` would take a `lastknowninvoice` as parameter. So that if BTCPay missed an invoice, lightning would send it when I reconnect.

* `waitanyinvoice` first call (Blocking)
* Invoice 1 is paid
* `waitanyinvoice` returns Invoice1 
*  Invoice 2 is paid
* `waitanyinvoice invoiceId1` second call (Non-Blocking)
* `waitanyinvoice` returns Invoice2
*  `waitanyinvoice invoiceId2` third call (Blocking)
*  Invoice 3 is paid
* `waitanyinvoice` returns Invoice3

Doing so would allow my payment processor to process an arbitrary amount of invoices while making sure nothing is missed.

**Comment by ZmnSCPxj** [comment]
I believe this is already implemented in c-lightning: https://github.com/ElementsProject/lightning/blob/master/doc/lightning-waitanyinvoice.7.txt

Your described use case seems to match the expected usecase in the example of the above document.

My understanding is that this is already "completely" implemented, also.

It is not linked to in the top README.md file, admittedly, so probably should refer to it there also.

**Comment by ZmnSCPxj** [comment]
Looking through the `json_waitanyinvoice` and `invoice.c` in general, it seems the behavior is something like this:

1.  `waitanyinvoice` will skip over any unpaid invoices.
2.  New invoices are put at the head of the list of invoices.
3.  Payment of invoices does not change the ordering of the list.
4. Given an argument, `waitanyinvoice` will scan the list starting from the given label,

The intent is that `waitanyinvoice` will be called repeatedly, with the first call given no argument, and succeeding calls being given as argument the `label` property of the previous return value of `waitanyinvoice`.

So it seems to me (unsure) that it would be possible for `waitanyinvoice` to report invoices multiple times.  For example:

1.  2 invoices are created, A and B.  Because new invoices are created at the head of the invoice list, this means the list is [B, A].
2.  `waitanyinvoice` is called once without an argument.
3.  The code scans over the list.  Since the none of the invoices are paid, the call blocks until any invoice is paid.
4.  Invoice A is paid.
5.  This triggers the `tell_waiter` function.  It then reports invoice A.
6.  `waitanyinvoice` is called with argument A (the previous return value).
7.  A is the last invoice in the list and we reach end-of-list.  So the call blocks until any invoice is paid.
8.  Invoice B is paid.
9.  This triggers `tell_waiter`, it reports invoice B.
10.  `waitanyinvoice` is called with argument B (the previous return value).
11.  The code starts with the invoice B.  B is the first item in the list [B, A].  So it looks starting at the next item.
12.  The next item after invoice B is invoice A, which is a paid invoice.  We dutifully report this invoice back to the caller without blocking.
13.  Oops, invoice A is credited twice by BitPay losing trillions of BTC!!!!!!!

@cdecker @rustyrussell can you confirm my analysis is correct?

If my analysis is correct, I think we should have a separate list of paid and unpaid invoices.

When an invoice is paid, it is removed from the unpaid invoice list, and added to the *end* of the paid invoice list.

Then `waitanyinvoice` should scan the paid invoice list only.

Also, `waitinvoice` also uses the same mechanism as `waitanyinvoice` (I think), so if `waitinvoice` is invoked, the invoice specified is unpaid, and then a *different* invoice is paid, it seems to my analysis that `waitinvoice` will return the other invoice invoice, not the one it was told to scan.

**Comment by NicolasDorier** [comment]
@ZmnSCPxj I am happy it already exists! While being called twice is counter intuitive, my database should be idempotent so it would not have side effects. I will give a go to lightning-c today or tomorrow. Thanks a lot!

**Comment by ZmnSCPxj** [comment]
@NicolasDorier

Actually if my analysis is correct, it may be possible for waitanyinvoice to block while an invoice is paid that has not been encountered by the caller to waitanyinvoice under a race condition.

1.  Make invoices A and B, creating the internal list [B, A]
2.  Pay A.
3.  waitanyinvoice with no argument, returning A.
4.  BtcPay processes etc etc
5.  Pay B.
6.  BtcPay finishes processing.
7.  waitanyinvoice with argument A.  Since A comes after B in the internal list, c-lightning assumes B is already reported and blocks.
8.  Payer of B wonders why BtcPay is not working and loses trillions of BTC due to lost business opportunity.

But in any case, waitanyinvoice "should" be something c-lightning provides, it's just that it might be buggy for now. If I can confirm my analysis is correct, I shall open a new issue.
