### ISSUE TITLE
Peer transient failure in CHANNELD_AWAITING_LOCKIN

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#449]
On testnet, with both of my computers on commit 4022fc00346c12f21057268b6800461fa47dcd44, make cleaned. I've replicated this 3 times in a row by deleting my `lightningd.sqlite3` on both computers each time. I just noticed hsm_secret, should I be deleting that as well or does it not matter?

In both situations, I've addfunds with the raw tx at 0 confirmations, if that matters.

## Initial fundchannel

From peer-a: 

```
$ lightning-cli fundchannel 021ba1e2bba7fda4f396d56fe3fb1f90c6fd3163ba3a677874c31f6e40839a39f0 10000000
```

peer-a logs: https://jb55.com/s/cbcabccc925ea4e9.txt
peer-b logs: https://jb55.com/s/f1204cd746b68479.txt

## On reconnect from peer-a to peer-b

```
$ lightning-cli connect 021ba1e2bba7fda4f396d56fe3fb1f90c6fd3163ba3a677874c31f6e40839a39f0 10.144.14.20  
channel ALL: 496e7465726e616c206572726f7200
```

peer-a logs: https://jb55.com/s/9793b7a4d1bc9f45.txt
peer-b logs: https://jb55.com/s/84dc3dfc75235377.txt

**Comment by cdecker** [comment]
It appears that the funding transaction is being created from outputs that are no longer there. I assume you're either using `addfunds` with the same transaction or it is picking the outputs out from the blockchain when it traverses it. In the latter case generating a new `hsm_secret` is the only known way to fix it currently, until I add spent monitoring as well.

**Comment by cdecker** [comment]
I added issue #451 to track progress on this :-)

**Comment by jb55** [comment]
>  I assume you're either using addfunds with the same transaction or it is picking the outputs out from the blockchain when it traverses it

hmm not sure what you mean, I'm simply following the instructions in the readme for opening a channel. I have tried following those steps around 10 times now without success... perhaps I'm missing something 🤔

Thanks for your help! I'll keep trying...

**Comment by cdecker** [comment]
I think it's something like this:

1. You followed the instructions from the readme, but something went wrong the first time
2. You deleted the database following the first failed attempt, but `hsm_secret` is still the same
3. Restarting the daemon will regenerate the same addresses for which the builtin wallet is looking
4. So when the wallet sees the funds that were assigned to it in the first test it goes "great, got some incoming funds", but the funds were already spent in the first, failed, attempt
5. Now you try to fund a new channel, and the builtin wallet happens to pick those funds that are no longer available, so it'll fail again.

This is an error in the builtin wallet, because we don't look for spends in the blockchain, absolutely not your fault. I'll take a look at it as soon as I have fixed the wallet recognizing its close transactions. In the meantime, deleting `hsm_secret` in the lightning dir should fix the problem (but also lose your testcoins so don't do this on mainnet!!!)

**Comment by jb55** [comment]
@cdecker my latest test deleted the entire ~/.lightning folder on both machines and I still got stuck. I'll try it again for a sanity check.

**Comment by cdecker** [comment]
Sorry you're having such a hard time, but thanks for reporting all of these, they're really helpful. Would you mind running your tests like this:

```lightningd/lightningd --log-level=debug |& tee lightning.log```

That increases the log-level and writes a logfile that we can then analyze and see where we get stuck.

**Comment by jb55** [comment]
So I believe this was happening because walletbroadcast was set to 0 in my bitcoin.conf. When I addfunds it was from addfunds transaction that hasn't been broadcasted yet. I believe that's why I have been seeing the missing inputs errors?
