### ISSUE TITLE
Daemon problem with log file + Service Fail

### ISSUE THREAD

**Issue by BitSocial-lb** [ElementsProject/lightning#4490]
lightningd --daemon
--daemon needs --log-file

lightningd.service

ExecStart=/usr/local/bin/lightningd --daemon --pid-file=/run/lightningd/lightningd.pid

Faill exit error

Seems some problem with daemon

Shall I change the service file like this ? 

ExecStart=/usr/local/bin/lightningd --daemon --log-file=debug.log --pid-file=/run/lightningd/lightningd.pid

**Comment by cdecker** [comment]
When daemonizing the process spawned by systemd will fork and exit as if it terminated, and the fork will live in the background. See [here](http://thelinuxjedi.blogspot.com/2014/02/why-use-double-fork-to-daemonize.html) for some additional information about how and why it works this way.

The process exiting and a child running in detached mode is detected by systemd as it terminating correctly, when in reality it is running in the background.

In order to tell systemd that this is the intended behavior and that it should track another pid instead (the one of the detached process) you need to update the `Type=` to `Type=forking`:


From the [systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=)

> If set to forking, it is expected that the process configured with ExecStart= will call fork() as part of its start-up. The parent process is expected to exit when start-up is complete and all communication channels are set up. The child continues to run as the main service process, and the service manager will consider the unit started when the parent process exits. This is the behavior of traditional UNIX services. If this setting is used, it is recommended to also use the PIDFile= option, so that systemd can reliably identify the main process of the service. systemd will proceed with starting follow-up units as soon as the parent process exits.

So you'll need to set both `Type=forking` and `PIDFile=/run/lightningd/lightningd.pid` and have a matching command line argument `--pid-file=/run/lightningd/lightningd.pid`. Alternatively you can always remove the `--daemon` option and keep the `Type=simple` since that way we keep the main process running in the foreground (and we get logs in `journalctl` and `systemctl` as a nice side-effect).
