### ISSUE TITLE
Cooperative channel close - loss of funds due to excessively low fee. Unable to CPFP.

### ISSUE THREAD

**Issue by Cannon-Ciota** [ElementsProject/lightning#4515]
Both lightning nodes are using clightning. I control both nodes. I did a channel cooperative close today. The fee for the channel close is 4 sats/vB which is WAY TOO LOW. It will never confirm. I lost a high amount of money from this and unable to recover. The problem is that there is no way I can find to CPFP this with a proper fee on any of the two nodes. On both nodes tx does not show as a confirmed or unconfirmed output in "Outputs" when I do "lightning-cli listfunds", but it does show the channel that was closed as "state: CLOSINGD_COMPLETE". 

I tried to reference the txid that it is  the output of the closure, as a utxo input in the lightning-cli withdraw option but clightning does not recgonize the UTXO as existing, it says "code -32602" and message "Unknown UTXO".

The command I used to close the channel is "lightning-cli close 12345x123x1" (I replaced the short chan ID with an example one)

WHY DOES IT SET SUCH A LOW FEE!!!!?

HOW CAN I CPFP OR RECOVER THESE FUNDS?

**Comment by Cannon-Ciota** [comment]
The closure transaction got broadcasted to network mempool. It remains unconfirmed. It will never confirm because the fee is way to low beyond any reasonable amount. clightning has no way to CPFP causing loss of funds.

**Comment by Cannon-Ciota** [comment]
Just venting here. There is a major unfixed security issue with lnd that I have been aware of, simply because it is based on go-lang. ANYTHING THAT IS PROGRAMMED IN GO-LANG SHOULD BE CONSIDERED POTENTIALLY COMPROMISED. This is why I'm anti-lnd and refuse to use it and simply don't acknowledge the existence of anything based on go-lang.

The only other two implementations I'm aware of is eclair and this, c-lightning. I love c-lightning, and see it as the best lightning network implementation. BUT, if this discovered issue of loss of funds has no solution, then I'll have to stop using c-lightning and just simply consider it unsafe for use and recommend people against it for the time being and will have to try out eclair. If eclair is broken as well, then lightning is not ready for production use and only a theory and alpha state experiment.

**Comment by GlenCooper** [comment]
I know this doesn't help much, but I feel the need to say it anyway;
Bitcoin is still an experiment.
The Lightning Network, even more so.
Never risk more funds than you're willing to lose.

Fwiw, the mempool was processing transactions as low as 3 sat/vB within the last 48 hours.

**Comment by Cannon-Ciota** [comment]
> I know this doesn't help much, but I feel the need to say it anyway;
> Bitcoin is still an experiment.
> The Lightning Network, even more so.
> Never risk more funds than you're willing to lose.
> 
> Fwiw, the mempool was processing transactions as low as 3 sat/vB within the last 48 hours.

Thanks for your reply. It is a good reminder. It wasn't my life savings or anything that I lost in this channel closure, but still an amount I dont want to permanently lose. I reported this as an issue in hopes that this can be something that could be fixed, and to also seek guidance on how to CPFP this unconfirmed utxo in the meantime. It should be a very simple fix, by including CPFP in c-lightning as an option. How can I prevent from losing funds of my other channels when closing? And does anyone have a solution on how I can spend another transaction with this unconfirmed utxo as the input to get this transaction through?

**Comment by vincenzopalazzo** [comment]
Hello

> The fee for the channel close is 4 sats/vB which is WAY TOO LOW.

I don't think your UTXO has a fee too low, but I think that all the transactions now on the blockchain (bad wallet used?) has the fee too high, my transaction with a test on c-lightning is confirmed in a couple of hours with 3.1 sats/vB.

https://blockstream.info/tx/de51f2ec4e180da5d17a6fe1c7aac9c072903fbf063c0d02e90d75b4d30227d5

I don't know how works the close logic of the channels in deep, but I strongly believe that your found are safe in the UTXO and just wait the confirmation, after that, you can see your funds in the listfunds

**Comment by cdecker** [comment]
I'm sorry you are having a bad time with c-lightning, I hope I can add a bit of color, and assure you that the funds will eventually return.

> I did a channel cooperative close today. The fee for the channel close is 4 sats/vB which is WAY TOO LOW. It will never confirm.

The fees are based on the `bitcoind` `estimatesmartfee` with the `100 ECONOMICAL`. This was done in https://github.com/ElementsProject/lightning/pull/4113 as a result of several people complaining that we were too aggressive with the fees in such a collaborative scenario. These parameters mean that we ask `bitcoind` to estimate the fee to get the transaction confirmed in the next 100 blocks (2/3 of a day) and try to stay as economical as possible. The estimates are not perfect, especially when looking this far ahead, and depending on the feerate evolution we might have to wait several days to get the funds back, but the feerate is safe as such, the transaction will just sit in the mempool until it is eventually confirmed. Feerate estimates are a bit of black magic at the moment, which is why we defer it to the experts from `bitcoind`.

> The closure transaction got broadcasted to network mempool. It remains unconfirmed. It will never confirm because the fee is way to low beyond any reasonable amount. clightning has no way to CPFP causing loss of funds.

It would not be in the mempool if there is no chance of it confirming, why would nodes keep it in their active set? We see periodic behavior in the feerate, and especially over the weekends we have lulls that can clear down to 1sat/byte. I know it's not what anyone wants to hear, but patience is key here.

> I tried to reference the txid that it is the output of the closure, as a utxo input in the lightning-cli withdraw option but clightning does not recgonize the UTXO as existing, it says "code -32602" and message "Unknown UTXO".

This is the direct return value from `bitcoin-cli` called underneath `lightningd` itself. It appears that in this case your transaction got dropped from the backing node's `bitcoind` which is why it can't just chain on top of the unconfirmed one. Notice that it is likely still in the mempool of miners, which tend to run with larger mempools.

If the transaction is still not confirmed you can recover it using `lightning-cli listtransactions` and then broadcast it with `bitcoin-cli` again. This is the sledgehammer command that I use for this:

```
lightning-cli listtransactions | jq '.transactions[].rawtx' --raw-output | xargs -L 1 bitcoin-cli sendrawtransaction
```

I say sledgehammer because it'll resubmit all transactions we have ever sent from this c-lightning node, including the missing close transaction. Notice that it'll return loads of `Missing inputs` and `Transaction already in block chain` errors since all transactions except the ones dropped from the mempool are already confirmed (`Missing inputs` is returned if `-txindex` is off, so `bitcoind` can't check if the tx is confirmed and it'll just check if the inputs are unspent which they won't be).

**Comment by Cannon-Ciota** [comment]
This happened again today, I closed some channels and a couple of them closed sub 5 sats per byte, one is even 2 sats per byte!  It is going to be a very very long time now before fees this low clear, if ever. Is there a way to CPFP (even if manually?), or is there some other way to recover funds?

And how can I prevent excessively low fees from being set again in the future when closing a channel? These were closed mutually not unilaterally. Thank you

**Comment by Cannon-Ciota** [comment]
I'm sure I am probably not the only one experiencing these issues or the last. Does clightning have a CPFP feature or way to recover funds, if not then this is a much needed feature, and I'd like to start conversation on the best way to implement this. And if anyone knows how I can recover my funds it would be very helpful.

**Comment by cdecker** [comment]
CPFP is not possible without anchor outputs and even then there are issues with pinning attacks. Closing as this is a spec-related issue.
