### ISSUE TITLE
At what situations will c-lightning try to close a channel?

### ISSUE THREAD

**Issue by urza** [ElementsProject/lightning#4540]
On several places in documentation I found mentions about closing or force closing channels, e.g. in config documentation:

> ignore-fee-limits=BOOL Allow nodes which establish channels to us to set any fee they want. This may result in a channel which cannot be closed, should fees increase, but make **channels far more reliable since we never close it due to unreasonable fees**.

I would like to open channels with (mostly) trusted counterparties and I would like to avoid closing channels as much as possible. Basically I would like to instruct c-lightning to never ever close a channel unless counterparty submitted cheating transaction on blockchain.
1. How to best achieve this?
2. What situation/conditions lead to c-lightning closing channel automatically?

**Comment by cdecker** [comment]
> > ignore-fee-limits=BOOL Allow nodes which establish channels to us to set any fee they want. This may result in a channel which cannot be closed, should fees increase, but make **channels far more reliable since we never close it due to unreasonable fees**.

This option might be good for your case, since you mention semi-trusted counterparties, but never do this in untrusted scenarios, since a peer could back you into a corner by low-balling fees, preventing you from punishing him if he misbehaves.

> I would like to open channels with (mostly) trusted counterparties and I would like to avoid closing channels as much as possible. Basically I would like to instruct c-lightning to never ever close a channel unless counterparty submitted cheating transaction on blockchain.
> 
> 1. How to best achieve this?

With decent feerate estimates this option should not be necessary. In order to guarantee that you and your peer should make sure that the `bitcoind` backend has been running for a while, i.e., it has a decent view of the mempool size to gauge demand for blockspace and what common fees look like.

> 2. What situation/conditions lead to c-lightning closing channel automatically?

The only cases we close channels automatically (that I remember atm) are:

 - Counterparty cheated, and we need to punish
 - Proposed fees are such that we don't believe they are sufficient to guarantee safe operation (they low-ball, hoping to slow down our reaction).
 - Have a stuck HTLC. This is currently the most common cause, and there is nothing we can do against this. HTLCs that are about to time out require us to go on-chain ahead of time to settle them correctly, and safeguard our funds.

**Comment by cdecker** [comment]
I should also mention that we limit automatic closes to scenarios in which the safety of the underlying funds are in danger, so any attempt to reduce closes may result in reduced security as well. That being said, we do welcome feedback as to what reasonable defaults look like, so feel free to share your experience.

**Comment by urza** [comment]
Thanks for the answer @cdecker, this clarifies it enough for me.
