### ISSUE TITLE
Running a single unit tests with reports

### ISSUE THREAD

**Issue by dangershony** [ElementsProject/lightning#4547]
Hi devs,
Not so much a c++ dev here, I am tying to run a single tests with not much luck.
I want to execute the run-commit_tx (to examine its output reports) from the logs I understand I should do `make check-units -k run-commit_tx` but no luck, some help please?

**Comment by cdecker** [comment]
No problem, there are two steps here: a) compile the binary that contains the tests, and b) run the binary. The following will get you going:

```
make channeld/test/run-commit_tx  # Full path of the binary from the repo root
channeld/test/run-commit_tx  # Run it as a binary
echo $?  # Print the return code to determine if we are ok or have an error
```

Depending on which test you're running this might give more or less context, but the test will return ok (return code `0`) if all tests passed, or error (return code other than `0`) if something went wrong.

**Comment by dangershony** [comment]
Thanks I will eave this issue open a bit longer in case I have more questions

**Comment by dangershony** [comment]
Hi quick question I noticed there are not tests  for `option_anchor_outputs = true` did I miss them?

**Comment by cdecker** [comment]
The `option_anchor_outputs` option is guarded by the `--enable-developer` configure flag, and specific tests will be skipped if not configured to enable them.

However the anchor outputs option may not have their own tests because they get extensively tested as part of the other tests (they are involved in every channel that is created in any tests).
