### ISSUE TITLE
Incorrect unilateral close fee used ?

### ISSUE THREAD

**Issue by f-hayek** [ElementsProject/lightning#4632]
`feerates perkb` reported:

```{
   "perkb": {
      "opening": 7992,
      "mutual_close": 7992,
      "unilateral_close": 7992,
      "delayed_to_us": 7992,
      "htlc_resolution": 7992,
      "penalty": 7992,
      "min_acceptable": 3996,
      "max_acceptable": 834080
   },
   "onchain_fee_estimates": {
      "opening_channel_satoshis": 1402,
      "mutual_close_satoshis": 1344,
      "unilateral_close_satoshis": 1194,
      "htlc_timeout_satoshis": 1324,
      "htlc_success_satoshis": 1404
   }
}
```

I thought it was a good time to close an inactive channel with an offline peer because I'd only pay 8 sats/vB accrding to the numbers above.
However the unilateral close tx that landed on the blockchain paid 76.1 sat/vB - 10x increase.

Why didn't it use what was reported by `feerates` ? The `feerates` command is still reporting 7992 for unilateral close. Is this a bug ?

**Comment by f-hayek** [comment]
I noticed that `listpeers` reports the feerate much closer to what was used:

```
               "feerate": {
                  "perkw": 20922,
                  "perkb": 83688
               },
```

If this is the actual feerate that's used for unilateral close then what's the purpose of reporting a misleading number in `feerates` ?

**Comment by f-hayek** [comment]
OK, I figured I was looking for the `last_tx_fee` in `listpeers`:

```
"last_tx_fee": "422000msat"
```

If that's the case then is the output from the `feerates`.`unilateral_close` command used for anything ? I reckon it's the current, global value for some negotiation/starting step but I don't know what exactly and when it's useful. If someone could explain it briefly I'd be grateful.

**Comment by cdecker** [comment]
Let's start by looking at what feerates are considered at what time:

 - the `feerates` command  reflects the current best estimate that `lightningd` will use to negotiate fees, and use for on-chain transactions in general.
 - the `feerate` in the `listpeers` command reflects the last negotiated feerate, so that can diverge significantly from the current one if the peer has been offline for a while
 - `last_tx_fee` reflects the fee attached to the last negotiated commitment transaction, and is just the size of the commitment transactions times the `feerate` in `listpeers`.

Since you mentioned that the peer is offline, the commitment transaction has been negotiated when he was last online, potentially at a much higher estimate. The fee attached to the commitment transaction cannot currently fluctuate along with the network-wide feerate, since that'd invalidate the signature you and your peer created for it. If you want to change the feerate you need to get a new signature from your peer, which doesn't work since it is offline.

This is being tracked and discussed at the spec level, and proposals for anchor outputs and eltoo are making progress, allowing us to decouple the feerate from the peer's signature, this allowing the feerate to change with the network weather.

**Comment by f-hayek** [comment]
It makes sense now. Thank you @cdecker . Looking forward to anchor outputs/eltoo.
