### ISSUE TITLE
DB mismatch sqlite version

### ISSUE THREAD

**Issue by Thuurio** [ElementsProject/lightning#4818]
### Issue and Steps to Reproduce

Hi All,
I have a laptop running Fedora 33 and have downloaded the lightning binary for Fedora 28 64bit. It was the only one available.
I extracted to the file (clightning-v0.10.1-Fedora-28-amd64.tar.gz) and ran the following command:
lightningd --network=bitcoin --log-level=debug

Bitcoin Core is running : downloading IBD 

### Output
lightningd: SQLITE version mismatch: compiled 3026000, now 3034001

### Possbile Solution
Recompiling c-lightning with the latest Fedora 33 Sqlite3 version will solve the issue ??
sqlite-3.34.1-1.fc33.x86_64 is already installed on my Fedora
Compiling instruction : https://github.com/ElementsProject/lightning/blob/master/doc/INSTALL.md  for Fedora

Please advise

Br,

**Comment by vincenzopalazzo** [comment]
Hi @Thuurio,

>lightningd: SQLITE version mismatch: compiled 3026000, now 3034001

SQLITE it is a shared library in c-lightning, and this error usually means that your local version in the system it is not compatible,

>Recompiling c-lightning with the latest Fedora 33 Sqlite3 version will solve the issue ??

Yes, or you can downgrade the local version of your `sqllite`, but I don't think the downgrade is a good thing because you can break somethings else in your system that is running with the actual version of c-lightning.

ping us when you have this problem fixed, or ping us on libera chat if you have some problem with the process

**Comment by cdecker** [comment]
I'd strongly suggest recompiling with your current sqlite3 version, since that'll minimize chances of issues, downgrading the sqlite3 version of the OS is very likely to break something (from browsers, to addressbooks, everything nowadays uses sqlite3).

I have a patch that'll weaken the check, to ensure we are running with a compatible version, not an exact match, but that'll be released in v0.10.2 and not backported.

**Comment by Thuurio** [comment]
> Hi @Thuurio,
> 
> > lightningd: SQLITE version mismatch: compiled 3026000, now 3034001
> 
> SQLITE it is a shared library in c-lightning, and this error usually means that your local version in the system it is not compatible,
> 
> > Recompiling c-lightning with the latest Fedora 33 Sqlite3 version will solve the issue ??
> 
> Yes, or you can downgrade the local version of your `sqllite`, but I don't think the downgrade is a good thing because you can break somethings else in your system that is running with the actual version of c-lightning.
> 
> ping us when you have this problem fixed, or ping us on libera chat if you have some problem with the process

Hi VicenzoP & @cdecker
Thanks for your reply.
After I ran ./configure and make I got an error 1 "No module found" see below : 

wiregen hsmd/hsmd_wiregen.h
Traceback (most recent call last):
File "/home/xxxxx/lightning/tools/generate-wire.py", line 24, in <module>
from mako.template import Template
ModuleNotFoundError: No module named 'mako'
make: *** [Makefile:301: hsmd/hsmd_wiregen.h] Error 1
[xxxxx@zebravink lightning]$ 

My background: new to crypto. I'm Linux user more apps than tech ..... Never compile an app ok... I can install Linux on my laptop........

Pls assist,
Br

**Comment by cdecker** [comment]
That means that some of the developer dependencies are missing. This should fix it:

```
pip3 install --user \
     --use-feature=in-tree-build \
     requirements.txt \
     ./contrib/pyln-client \
     ./contrib/pyln-proto \
     ./contrib/pyln-testing
```

That will install `mako` among other things, which is required for some of the generated files.

**Comment by Thuurio** [comment]
> That means that some of the developer dependencies are missing. This should fix it:
> 
> ```
> pip3 install --user \
>      --use-feature=in-tree-build \
>      requirements.txt \
>      ./contrib/pyln-client \
>      ./contrib/pyln-proto \
>      ./contrib/pyln-testing
> ```
> 
> That will install `mako` among other things, which is required for some of the generated files.
Hi @cdecker,
I got the following error after running the pip3 command in the lightning dir.. and I have attached the requirement.txt 

### Error
Processing ./contrib/pyln-client
Processing ./contrib/pyln-proto
Processing ./contrib/pyln-testing
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt

[requirements.txt](https://github.com/ElementsProject/lightning/files/7231734/requirements.txt)

**Comment by cdecker** [comment]
Oh sorry, to load dependencies from a file requires `-r requirements.txt`, my bad

**Comment by Thuurio** [comment]
> Oh sorry, to load dependencies from a file requires `-r requirements.txt`, my bad

It is working now I assume........ Thanks for your help 

Final Q : in the logfile I see lines of "unable to estimate ..... fees"
IBD is still downloading 
These lines are normal .......  

Thanks for your help so far.

**Comment by cdecker** [comment]
Yep, these lines are normal, if `bitcoind` is downloading it can't track the mempool, which is required to estimate how much blockspace contention there is, and thus how much fees will be required for a given confirmation target.

Since `lightningd` is working ok now, I'll close this for now, but feel free to open a new issue or reopen this one if anything comes up.
