### ISSUE TITLE
v0.10.2 permission issue during install

### ISSUE THREAD

**Issue by iamthen0nce** [ElementsProject/lightning#4939]
When building c-lightning v0.10.2 from source, we run into this issue:

```
/bin/sh: common/htlc_state_names_gen.h: Permission denied
```

when executing `make` as unprivileged user.

Not sure if it's a bug or if the doc just has to be adapted to tell users to do `sudo make` instead.

```
Build lightning:

./configure
make
sudo make install
```
should probably become
```
Build lightning:

./configure
sudo make
sudo make install
```

**Comment by vincenzopalazzo** [comment]
adding `sudo make` to compile the sources doesn't make sense IMO, instead, run the command `sudo make install` make sense because we are asking to copy some files in some special directory of the system.

In addition, the command make will generate some source code files so the file `common/htlc_state_names_gen.h` is autogenerated, one thing that I have in mind is if you have on your machine the write permission.

**Comment by iamthen0nce** [comment]
Okay; wasn't sure if I could just ignore that error and run `sudo make install` directly. But normal `make` threw this error that's all I can tell you. Wasn't like that in the past.

**Comment by cdecker** [comment]
I'm almost certain that running with `sudo` isn't what you want. This looks like it is trying to execute a header file, potentially because the tool that we actually wanted to call (i.e., `/path/to/tool.sh common/htlc_state_names_gen.h`) can't be found, leaving it blank, and thus causing us to instead attempting to execute the argument instead (i.e., `./common/htlc_state_names_gen.h`). This fails because the file being passed as an argument is not marked as executable (and that's a good thing).

We should rather be checking if the tool exists and if not report it as an error.

**Comment by andrewtoth** [comment]
> wasn't sure if I could just ignore that error and run `sudo make install` directly.

`sudo make install` copies the compiled binaries into places where they will be found by other system users' paths. If `make` fails then the binaries aren't compiled successfully, so you will be installing the previous version again.

Does `ccan/ccan/cdump/tools/cdump-enumstr common/htlc_state.h` output some C code in the terminal for you, or does it return an error?

**Comment by ZmnSCPxj** [comment]
`sudo make` is almost always a mistake and it would be a bug to require that.

Can you provide the *full* logs of `configure` and `make`?  More likely something else is broken.

**Comment by iamthen0nce** [comment]
> > wasn't sure if I could just ignore that error and run `sudo make install` directly.
> 
> `sudo make install` copies the compiled binaries into places where they will be found by other system users' paths. If `make` fails then the binaries aren't compiled successfully, so you will be installing the previous version again.

I know, so it's weird that `make` works with `sudo` but not without.

> Does running the command `ccan/ccan/cdump/tools/cdump-enumstr common/htlc_state.h` output some C code in the terminal for you, or does it return an error?



> `sudo make` is almost always a mistake and it would be a bug to require that.
> 
> Can you provide the _full_ logs of `configure` and `make`? More likely something else is broken.

./configure works without issues and ./make fails with:

```
ccan/ccan/cdump/tools/cdump-enumstr common/htlc_state.h > common/htlc_state_names_gen.h
/bin/sh: common/htlc_state_names_gen.h: Permission denied
make: *** [common/Makefile:134: common/htlc_state_names_gen.h] Error 1
```

**Comment by iamthen0nce** [comment]
> @iamthen0nce thanks, managed to reproduce! So you ran `sudo make` at some point in the past which caused some generated files to be owned by root, like `common/htlc_state_names_gen.h`. Then running `make` in a future version doesn't allow you to overwrite it again (this is what it's trying to do here `ccan/ccan/cdump/tools/cdump-enumstr common/htlc_state.h > common/htlc_state_names_gen.h`) because it's owned by root.
> 
> Run `sudo rm common/htlc_state_names_gen.h` and `make` should work.

Thanks a lot! What a stupid mistake :D I built it as a different user once (not root though); that's what I saw from a simple `ls -l`. Just cloned lightning freshly and it works perfect. Sorry for the troubles; classic PEBKAC :(
