### ISSUE TITLE
Gossip unusual?

### ISSUE THREAD

**Issue by Coinomatron** [ElementsProject/lightning#4997]
Hi, seeing a lot of "Can't send commit: nothing to send, feechange not wanted ({ SENT_ADD_ACK_REVOCATION:253 }) blockheight not wanted ({ SENT_ADD_ACK_REVOCATION" in the debug output. All the while, my node isn't trying to relay transactions at all. Could be coincidence, but wanted to check if this is unusual behavior or not. Thanks.

**Comment by cdecker** [comment]
This is perfectly fine. What it's reporting is that it'd like to send a fee update, but it can't right now because the protocol disallows empty commits in some states (commit pending for example). The message you're seeing is just saying "we'd like to commit, but can't so we'll defer until there is a change that warrants a commit.

**Comment by Coinomatron** [comment]
Great, thanks. Updated to the latest build in the meantime.
