### ISSUE TITLE
trying to understand inactive channel closure and fund recovery

### ISSUE THREAD

**Issue by riannom** [ElementsProject/lightning#5074]
### Issue and Steps to Reproduce
I have a channel that somehow decided to unilaterally close.  I didn't initiate a close voluntarily.

The 'state' in the logs and listpeers seems to flip between "FUNDING_SPEND_SEEN" and "ONCHAIN" for the past few days now.
I'm also not sure what the listpeers output of "2 outputs unresolved: waiting confirmation that we spent OUR_HTLC (26c955d117efa587e63da41e4e988f8029fb7ada9346bda00535b4b8d1959781:0) using OUR_HTLC_TIMEOUT_TX"" means in terms of: do I just need to wait or is there something else I need to do?

EDIT: I was able to figure out issue by rescanning blockchain

**Comment by riannom** [comment]
I was able to figure out issue by rescanning blockchain

**Comment by heyambob** [comment]
I got this same issue. I had to rescan twice. I got stuck in "waiting confirmation that we spent OUR_HTLC (xxxxx:0)". After the first scan, it discovered xxxx was confirmed, then I got stuck again at "waiting confirmation that we spent OUR_HTLC (yyyyyyy:0)", and to do another rescan.

It looks like a bug to me because it shouldn't happen in the first place + need multiple rescan to solve. I didn't notice any issues with bitcoind/clightning
