### ISSUE TITLE
Very slow block download

### ISSUE THREAD

**Issue by d4amenace** [ElementsProject/lightning#5117]
I am running c-lightning in an lxc container and am experiencing block download delays.  My instance is RPC connected to a fully updated bitcoind.  The blocks are downloading horrendously slow.  I am adding blocks at 3-4 per minutes and the lightning client is unavailable for more than a week.

Is there a way to use a fully validated ln node and port over it's blocks?  Just curious, as setting up a lightning node shouldn't take weeks.

**Comment by cdecker** [comment]
Two things here:

 - That download rate is really way too slow, usually we process 3-4 blocks per second, so that's worth investigating
 - c-lightning should not have started with much lag if this is a new wallet being created (we only scan the last couple of blocks since the wallet cannot have any funds in lower blocks since it was just created). I presume this is a new wallet?

I remember a similar issue with docker based deployments, which had issues starting subprocesses because of the way we close file descriptors before calling `execve` (#4872), however that was merged in c-lightning v0.10.2. What version are you running?

**Comment by d4amenace** [comment]
I actually figured out what the problem was after investigating that same docker issue. I found that the problem was caused by my container duplication method. When the duplication occurred I did not remove the hidden lightning folder when spinning up a new node and caused a conflict, which caused the lightning nodes to literally download the blocks in reverse.

Once I removed this folder and restarted the node, the blocks were added instantaneously, a new key was created and everything was fine.
