### ISSUE TITLE
`listfunds` still shows spent output until child tx is confirmed

### ISSUE THREAD

**Issue by kristapsk** [ElementsProject/lightning#5249]
### Issue and Steps to Reproduce
1) Have no onchain funds in CLN wallet.
2) Use `newaddr` and then send some coins to it.
3) Wait for tx to confirm. Now `listfunds` shows the new UTXO.
4) Do `fundchannel`, spend specific amount, not the whole amount of UTXO (so have change).
5) Now `listfunds` under `outputs` shows both new unconfirmed UTXO and also old TXO actually spent by the new unconfirmed tx.
```
   "outputs": [
      {
         "txid": "YYYYYY",
         "output": 1,
         "value": nnn,
         "amount_msat": "nnn000msat",
         "scriptpubkey": "YYYYYYY",
         "address": "bc1qyyyyyy",
         "status": "unconfirmed",
         "reserved": false
      },
      {
         "txid": "XXXXXX",
         "output": 0,
         "value": nnn,
         "amount_msat": "nnn0000msat",
         "scriptpubkey": "XXXXXXX",
         "address": "bc1qxxxxxx",
         "status": "confirmed",
         "blockheight": nnnnnn,
         "reserved": true,
         "reserved_to_block": mmmmmm
      }
   ],
```
6. Wait for new tx to confirm, then old TXO disappears from `listfunds` output.
```
   "outputs": [
      {
         "txid": "YYYYYY",
         "output": 1,
         "value": nnn,
         "amount_msat": "nnn000msat",
         "scriptpubkey": "YYYYYYY",
         "address": "bc1qyyyyyy",
         "status": "confirmed",
         "blockheight": nnnnnn,
         "reserved": false
      }
   ],
```

### `getinfo` output
```
{
   "id": "XXX",
   "alias": "YYY",
   "color": "rrggbb",
   "num_peers": x,
   "num_pending_channels": y,
   "num_active_channels": z,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "nn.nn.nn.nn",
         "port": 9735
      },
      {
         "type": "torv3",
         "address": "nnnnnnnnnnnnn.onion",
         "port": 9735
      }
   ],
   "binding": [],
   "version": "0.10.2-gentoo-r0",
   "blockheight": nnnnnn,
   "network": "bitcoin",
   "msatoshi_fees_collected": nnnnnn,
   "fees_collected_msat": "nnnnnnmsat",
   "lightning-dir": "/var/lib/lightning/bitcoin"
}
```

**Comment by djpnewton** [comment]
This also happens if you make a non `fundchannel` tx

perhaps a new status is required in between `confirmed` and `spent`

**Comment by ZmnSCPxj** [comment]
I think this is intended to be a feature, not a bug.  Supposedly as long as the tx is unconfirmed, the txout is only "reserved", because in theory you could RBF the tx --- C-Lightning marks every transaction it creates as allowing RBF.  We currently do not have interfaces implemented that *expose* this RBF functionality to end users, but in theory it could be made.

**Comment by kristapsk** [comment]
Problem is that I cannot see that output is spent and unconfirmed for [my walletbalance script](https://github.com/kristapsk/cln-scripts/blob/master/cln-walletbalance.sh).

**Comment by ZmnSCPxj** [comment]
You can see it has a `"reserved"` field, which you can generally use anyway.

**Comment by kristapsk** [comment]
`"reserved"` field solves the issue, closing this as I don't think anything more should be done here. Added PR #5260, which restores description of `"reserved"` field in manpage.

**Comment by djpnewton** [comment]
is this `reserved` field unrelated to the `reserveinputs` rpc etc? As in it is "only" used for in-flight txs?

**Comment by ZmnSCPxj** [comment]
It is related to `reserveinputs` command.  The intent is that you reserve a UTXO, then put it in a PSBT, then potentially negotiate the PSBT with an external network (think dual-funding).  The external network may be slow, because network, so a UTXO may be reserved for a time without actually being in an in-flight TX *yet* (i.e. it is still in a PSBT you are  negotiating, and not a full transaction you can broadcast that just happens to be unconfirmed right now, because the network participant you are talking to may be slow, connection may be intermittent, etc.).

Since the reservation API is exposed as a command, you, or a plugin you use, can reserve UTXOs arbitrarily.  You or a plugin you use SHOULD NOT do so without  some kind of intent to actually get it onto a PSBT that eventually becomes a full Bitcoin tx somehow, but things like bugs and Murphy law exist.
