### ISSUE TITLE
cln-plugin: Required ConfigOption with no default

### ISSUE THREAD

**Issue by justinmoon** [ElementsProject/lightning#5274]
I need to write a c-lightning plugin that takes a command line argument to a config file. This config is required -- the plugin cannot work without it -- and at this point there isn't a default location for it.

Right now I just set a default value to "default-do-not-use" or something like that and panic if that's still the value after initialization. But it might be nice if the library supported this kind of required argument without a default. 

(Or maybe I just need to figure out a default location for my plugin config!)

**Comment by vincenzopalazzo** [comment]
This is exactly how the grpc plugin works, if the option is missed, you can disabled the plugin

https://github.com/ElementsProject/lightning/blob/c7d359baf455e5260dc5d126b05211279e186ef8/plugins/grpc-plugin/src/main.rs#L44-L65

But this can be an idea to have not a library level but a lightningd level, that can avoid running the plugin if there is not enough info to run it! This make also the plugin lifecycle easier!

**Comment by ZmnSCPxj** [comment]
> But this can be an idea to have not a library level but a lightningd level, that can avoid running the plugin if there is not enough info to run it! This make also the plugin lifecycle easier!

If we want plugins to be self-contained, at the minimum `lightningd` has to run `getmanifest` on it so that the plugin can tell it "yeah if this option does not exist just exit me immediately mkay".

Now, the general directive is that all your heavy initialization should occur on the `init` command, so the initial `getmanifest` should really just return an effectively hardcoded constant, and then if your plugin specifies "if this options does not exist just terminate me early" then the `lightningd` can simply close the pipe to the plugin and let it terminate.

**Comment by vincenzopalazzo** [comment]
Oh you have right @ZmnSCPxj I think the actual solution is the more convenient one

**Comment by justinmoon** [comment]
Closed by #5369
