### ISSUE TITLE
There's no way to make an invoice without an amount.

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#534]
Which we should be able to do, for "donations".

**Comment by ZmnSCPxj** [comment]
Will take this, if you do not mind.

Below are rough plan of changes needed:

1.  Make `msatoshi` field a `u64*` rather than `u64` in both `struct payment` and `struct invoice`. Adapt all invoice and payment code appropriately.  Map a database `NULL` to a NULL pointer, non-null to a valid pointer containing the value.  (alternatively allow 0 value for `msatoshi`, treating this as database `NULL`).
2.  Modify JSON RPC `invoice` to accept `null` for `amount`.  Set the invoice and payment `msatoshi` to the database `NULL` if so.  For the bolt11 object, leave the `amount` field `null if the given invoice amount is null.
3.  Write a test creating amountless invoices and paying them a random amount.

**Comment by rustyrussell** [comment]
Sounds great!

1. Sounds good, prefer db null over 0.
2. Don't think lightning-cli will pass through null, you'll need to fix that.

**Comment by ZmnSCPxj** [comment]
Okay, I will also have to add null support to lighyning-cli

**Comment by cdecker** [comment]
Can we make it "any" just to make it explicit that any amount will result in the invoice being marked as paid.

**Comment by ZmnSCPxj** [comment]
"any" would indeed be better I think
