### ISSUE TITLE
CMP Counter Asserted

### ISSUE THREAD

**Issue by nepet** [ElementsProject/lightning#5393]
Scenario: We resolved an invoice and the moment after we got the following error (might not be related to the invoice, or is it? ...).
CLN is version v0.10.2 well connected and running for some time now.
```
...
2022-07-08T15:23:48.314Z INFO    lightningd: Resolved invoice 
...
Assertion failed: a->c->rr_number < b->c->rr_number (lightningd/invoice.c: cmp_rr_number: 623)
lightningd: FATAL SIGNAL 6 (version v0.10.2-modded)
0x5654f1c40061 send_backtrace
        common/daemon.c:33
0x5654f1c400e9 crashdump
        common/daemon.c:46
0x7efd87da6c8a ???
        ???:0
2022-07-08T15:23:48.348Z **BROKEN** lightningd: FATAL SIGNAL 6 (version v0.10.2-modded)
2022-07-08T15:23:48.349Z **BROKEN** lightningd: backtrace: common/daemon.c:38 (send_backtrace) 0x5654f1c400a9
2022-07-08T15:23:48.349Z **BROKEN** lightningd: backtrace: common/daemon.c:46 (crashdump) 0x5654f1c400e9
2022-07-08T15:23:48.349Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7efd87da6c8a
```

**Comment by rustyrussell** [comment]
Annoying that we don't see the full backtrace (or better, a core file!).

This code is called for invoice *generation*, so that's where it crashed.

There are several possible causes for this:
1. We have two channels with the same rr_number. A quick audit shows we always set that rr_number to a unique value (and 64 bits, so wrap is not possible between the release and now!).
2. It's theoretically possible that sort() could compare a value with itself, but that would be really dumb: it doesn't that I've ever seen, but then, we've never seen this assert() hit, either.
3. listincoming has given us the same channel twice.  I don't see how that is possible: we had a race where channels could momentarily vanish, but never be duplicated (emailed crash.log shows no duplicates!).
4. General corruption/freed memory access.  If a channel we've just looked up is gone but still in the hash table, this is possible but would cause lots of random behavior and crashes.
