### ISSUE TITLE
c-lightning should support on-chain fallback for BOLT11 invoices

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#542]
Maybe via an additional arg to the invoice RPC?

**Comment by ZmnSCPxj** [comment]
For this case, should we also add a column to db invoice table?

Then if the specific address assigned to this invoice is paid onchain with sufficient depth (probably configurable), we also mark the invoice as paid (and in particular trigger any `waitinvoice` and `waitanyinvoice`).

So....

1.  Add a `--onchain-fallback-depth` setting (default 6?) for how deep on-chain fallbacks should be.
2.  Add some address derivation path specifically for on-chain invoice fallbacks and teach hsmd how to sign these.  NOTE we need to provide unique addresses for each invoice generated with on-chain fallback so that we can identify which invoice got paid onchain.  Alternatively we can keep the private key in the invoice table database for a freshly random private key and generate the (P2SH-P2WPKH for maximum compatibility? P2WPKH because sipa is so cool? Probably P2WPKH because anything that can parse a BOLT11 invoice has a bech32 parser anyway and should be able to handle paying to P2WPKH anyway) address from there.  Or alternatively alternatively, reuse the r as the private key.  Still need to teach hsmd how to sign these though!
3.  Add a column to the invoice table in the db containing a nullable onchain fallback address (or private key if we decide to generate a freshly random private key independently of the hsmd secret, or even just a boolean flag if we decide to reuse r as the private key for fallback).  Update invoice structure and loading and so on as appropriate.
4.  Monitor invoice fallback addresses (only up to expiration time?) in chain topology (add to txfilter?) and also make sure to recover them on startup (add it to wallet_invoices_load?).  When paid with greater than or equal to msatoshi value (or paid with anything if msatoshi is NULL as per any-amount invoices) and with required on-chain fallback depth, set invoice as paid (triggering waiters, so use `resolve_invoice`), and add to UTXO database (probably need to provide the private key to the UTXO database too? Or derivation path? Need to study the UTXO database...).
5.  Add an optional "?fallback" argument to invoice RPC command, which if the JSON value `true` generates a fallback address in the invoice object, and load the bolt11 object appropriately.

Good? Anything I am missing?

**Comment by ZmnSCPxj** [comment]
Another issue is: if the `pay` command receives an onchain fallback in bolt11 should it perform the fallback itself directly?

**Comment by juscamarena** [comment]
It would be great to have it pay fallback addresses, I have fallback addresses set for bitrefill orders.

**Comment by ZmnSCPxj** [comment]
Fallback addresses will not provide proof-of-payment, so I wonder if it is indeed as good as it can be.
