### ISSUE TITLE
Use lowdown(1), not mrkd, to generate man pages from Markdown

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#5437]
mrkd is pretty bad, complicates dependencies.

We could use lowdown, and also reformat our pages a bit to make them prettier and more consistent.

Command is something like:

    lowdown -s --out-no-smarty -Tman -m "title:LIGHTNINGD-CONFIG" -m "section:5" -m "shiftheadinglevelby:-1"

**Comment by vincenzopalazzo** [comment]
Concept ack.

BTW what is the milestone 22.10? should like a `TODO` :)

**Comment by wtogami** [comment]
I'm hoping this can be done for v0.12 because mrkd is a serious headache obstructing packaging CLN in Fedora and EPEL. I need to package all the deps for offline builds and there are policies against more than one version of a package which makes mrkd dead in the water.

**Comment by grubles** [comment]
Is there a reason for the whitespace changes to be ignored? Seems like the example changes in https://github.com/rustyrussell/lightning/commit/fcf882d1bb63208c3ebb5e6ad1a4e9837a919731 might be harder to read than when using `mrkd`. Or is that something to be fixed later with "also reformat our pages a bit to make them prettier and more consistent"?

**Comment by jb55** [comment]
ACK, switching to lowdown was trivial on my linux distro and it seemed to work ok

**Comment by rustyrussell** [comment]
OTOH, this is not a regression since previous versions; it has long been this way.

**Comment by whitslack** [comment]
Chiming in (a little late to the party)… Mrkd is also an obstruction for Gentoo packaging since it fails to work with the current generation of Mistune. Thus, anyone who wants to build CLN with documentation (`USE="doc"`) is forced to have their Mistune downgraded, which may not even be possible if other installed packages strictly depend on a newer version.

Glad to see there's a resolution in the pipeline. :slightly_smiling_face:
