### ISSUE TITLE
Static channel backup: What does it do?

### ISSUE THREAD

**Issue by SimonVrouwe** [ElementsProject/lightning#5439]
I cannot find any documentation about the `chanbackup` plugin.

What does it do?
When should it be used?
What is the difference with the other backup methods?

Maybe an chapter can be added to  [BACKUP.md](https://github.com/ElementsProject/lightning/blob/master/doc/BACKUP.md) ?

**Comment by adi2011** [comment]
Adding this PR #5361

**Comment by cdecker** [comment]
The goal of the static channel backup (lnd chose this name) is to provide a recovery method of last resort. It contains a subset of the data in the DB for each channel that was active at the time the file was generated. This subset is sufficient for a recovering node to reach out to the peer, despite having lost all the DB data, and ask it nicely to close the channel, and then grab the funds from on-chain.

It is not really a backup because:
 1. Channels have to be closed in case of a recovery, there is no way you can continue using the channels. Real backups in LN-penalty have to be real-time backups, such as the backup.py plugin, which however has a whole slew of issues (backup not reachable? your node can't proceed)
 2. You are relying on the peer to be collaborative and close the channel when you ask it to and not to cheat. It could very well just replay an old state in which they had the majority of funds and you wouldn't be able to retaliate (remember: you lost your DB with the penalty transactions).

It is however a very good last resort option, recovering as many funds as possible, even if your peer might cheat you out of a part of the funds or attempt to blackmail you.

**Comment by ShahanaFarooqui** [comment]
Closing it as no further action is required.
