### ISSUE TITLE
We need to save last_htlc_sigs into DB.

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#553]
`lightningd/peer_htlcs.c:1135:	/* FIXME: Put these straight in the db! */`

These are required for onchaind to handle the case where we unilaterally close with outstanding HTLCs.  They are only needed for the latest commitment transaction, however.

**Comment by cdecker** [comment]
Is there a point in attempting to map them to HTLCs which we already persist, or is creating a new table the way to go?

**Comment by rustyrussell** [comment]
It's almost more hassle to relate them to htlcs and then order them back into commit-tx order, than create a new table and just replace, I think.

**Comment by cdecker** [comment]
Ok, just to make sure, the ordering is important since we have no other way of mapping them to the HTLCs I guess? So I'm thinking of truncating the table, inserting them with an id as the position and then reading them out in batch again. Not sure how good truncate performance is wrt to `delete from htlc_sigs where 1=1`, will find out.
