### ISSUE TITLE
Use own wallets unconfirmed utxos

### ISSUE THREAD

**Issue by djpnewton** [ElementsProject/lightning#5612]
Is it possible to allow the wallet to use its own unconfirmed utxos?

**Comment by cdecker** [comment]
Depends: if the UTXO is in the DB we can use it using the `minconf` parameter in various RPC methods.

If we sent the transaction ourselves, we will most likely have the UTXO in the DB. If the funds are being sent from outside the node, then we will only see them once they are confirmed. This is because we don't require access to the mempool, and process blocks to discover incoming funds instead.

**Comment by djpnewton** [comment]
ok it sounds like it will work.

I guess if the mempool was processed in the future a different strategy would be needed (perhaps extra parameter to `txprepare` for only using self created unconfirmed utxos)

**Comment by cdecker** [comment]
Correct, scanning the mempool would allow us to track unconfirmed incoming payments too, however that'd massively increase the reliance on the Bitcoin backend. Not all backends actually track the mempool, and some are more permissive than Bitcoin Core, and could be tricked into considering unconfirmed UTXOs that may not ever confirmm, hence our reluctance to add it. Notice that you could potentially already use the PSBT based methods to mix in external UTXOs if you know about them, just build the PSBT in whatever tool knows about them, and then use those to fund a channel or send an on-chain TX.

Could be a plugin 🤔
