### ISSUE TITLE
Commando Plugin does not start: ModuleNotFoundError: No module named 'pyln'

### ISSUE THREAD

**Issue by zynos** [ElementsProject/lightning#5711]
```
sudo /home/cln/lightning/lightningd/lightningd --plugin=/data/cl-plugins-available/commando/commando.py
Traceback (most recent call last):
  File "/data/cl-plugins-available/commando/commando.py", line 22, in <module>
    from pyln.client import Plugin, RpcError  # type: ignore
ModuleNotFoundError: No module named 'pyln'
2022-11-12T15:24:05.787Z INFO    plugin-commando.py: Killing plugin: exited before replying to getmanifest
```
I followed the steps from:
https://github.com/lightningd/plugins/blob/master/README.md#pythonpath-and-pyln
so my PYTHONPATH is
`$ echo $PYTHONPATH`
```
/home/cln/lightning/contrib/pyln-client:/home/cln/lightning/contrib/pyln-testing:/home/cln/lightning/contrib/pyln-client/:/home/cln/lightning/contrib/pyln-testing/:
```
CLN: "version": "v0.12.1",

**Comment by jb55** [comment]
you don't need the commando plugin anymore on v0.12, it's built in.

**Comment by vincenzopalazzo** [comment]
This looks like a `pip3 install -r requirements.txt` missing, also make sure that you have the latest version of the plugin.

In addition, as @jb55 pointed out cln supports commando by default now, and I suggest using it because it is much faster

Some docs here https://lightning.readthedocs.io/lightning-commando.7.html
