### ISSUE TITLE
unable to connect to peer, while using fundchannel.

### ISSUE THREAD

**Issue by Harshit933** [ElementsProject/lightning#6059]
# Steps to reproduce

1. Running : `lightning-cli connect <nodeid> <ip> --testnet`

Produces the response: `{
   "id": "02049b60c296ffead3e7c8b124c5730153403a8314c1116c2d1b43cf9ac0de2dxx",
   "features": "08a000080269a2",
   "direction": "out",
   "address": {
      "type": "ipv4",
      "address": "78.46.2xx.4",
      "port": 19735
   }
}`

2. Running: `ightning-cli fundchannel <nodeid> <amount> --testnet`

Produces the response: 
`{
   "code": 400,
   "message": "Unable to connect, no address known for peer",
   "data": {
      "id": "02049b60c296ffead3e7c8b124c5730153403a8314c1116c2d1b43cf9ac0de2dxx",
      "method": "connect"
   }
}`

In both the cases, I have used to same node Id.

cc @vincenzopalazzo

**Comment by vincenzopalazzo** [comment]
This is reproduced also by lnprototest in https://github.com/rustyrussell/lnprototest/issues/54

Looks like this happens with a clean node, and looks like that can fall inside the last case where we do not know the information and we look inside the gossip map.

This should not happen because we are already connected.

Thanks to reporting it

lnprototest issue: https://github.com/rustyrussell/lnprototest/issues/54
