### ISSUE TITLE
Channel not closing

### ISSUE THREAD

**Issue by elderbeans17** [ElementsProject/lightning#6061]
I attempted to close a channel 766086x1295x1 a few days ago, and in RTL it is showing up as CLOSINGD_COMPLETE, we are disconnected, and the channel is inactive/pending. When I look via CLI I see the same thing. However if I look on mempool the channel still appears active, nor is there any sort of closing transaction. Does anyone have any solutions here? I have never encountered this issue before. This is my only channel I have left to close out. Any help would be appreciated thanks!

**Comment by vincenzopalazzo** [comment]
The channel activity it monitored (usually) by the gossip data, so at this point, I guess that mempol has a node and from this node is able to see the activity of the network because the node talking by gossiping information.

The problem is that you close the channel but the mempool node did not see this update, and this results in showing the wrong data in the web page.

This is normal because the propagation of the update through the network can take a while and this is lower for small node like yours

**Comment by elderbeans17** [comment]
Appreciate the help Vincenzo, I was able to resolve the issue overnight by restarting CLN. Must have been some sort of bug. Channel closed and funds returned. Thanks!
