### ISSUE TITLE
Opening negotiation failed: feerate_per_kw 53760 above maximum 1325

### ISSUE THREAD

**Issue by ktorn** [ElementsProject/lightning#609]
I'm failing to open a channel from Eclair on Android to a lightning-c node, and this is the error I keep getting on the log file of lightning-c when I try to create the channel:

`Opening negotiation failed: feerate_per_kw 53760 above maximum 1325`

**Comment by Saibato** [comment]
tryd this also days ago , used overide fees option to overcome , but then the next eclair step  on my build  the funding tx crashed the deamon . When it changed peer state .
Should have reported this ...
So please try with your config if it makes the funding after settting higher fees then it was my config and build.
Otherwise we have a new issue ;-)

**Comment by jb55** [comment]
Yeah what saibato said, I typically have to do:

    $ lightning-cli dev-setfees 53760 53760 53760

I think eclair mobile hardcodes that? I've never seen it report a
different value.

**Comment by ktorn** [comment]
@jb55 `dev-setfees` worked thanks (did require a few tries, but eventually worked).

Where can I find docs this and other commands accepted by the daemon?

**Comment by ktorn** [comment]
Found it: `$ lightning-cli help` returns the list of rpc commands.

Previously I'd tried `$ lightning-cli --help` which only outputs the cli tool usage.
