### ISSUE TITLE
Please update PPA to latest release

### ISSUE THREAD

**Issue by callebtc** [ElementsProject/lightning#6227]
Installing via Ubuntu using the commands in the README

```bash
sudo apt-get install -y software-properties-common
sudo add-apt-repository -u ppa:lightningnetwork/ppa
sudo apt-get install lightningd
```

Installs `lightningd 0.12.1` which was released Sep 23, 2022

**Comment by vincenzopalazzo** [comment]
I think @cdecker is working on a ppa server? looks like tricky the ppa release process, but I never did it

**Comment by cdecker** [comment]
The PPA process is utterly broken, and requires an incredible amount of maintenance for the little usage it is getting. We are looking for alternatives on how to build our own repo, also allowing us to distribute reproducibly built artifacts rather than the dodgy ones launchpad creates.

Shall we remove the PPA from the installation docs?
