### ISSUE TITLE
Track a "mempoolminfee" history locally and use for fee updates

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/lightning#6259]
Bitcoin Core currently forgets mempool min fees, the sat/vbyte rate it will accept a transaction into its mempool, between restarts. Please see:

https://github.com/bitcoin/bitcoin/issues/27555#issuecomment-1538504504

CLN should somehow track this value and not let it drop to 1 sat/vbyte immediately. Inspiration can likely be found from Core's codebase which has it degrade over time if the mempool stops being full: https://github.com/bitcoin/bitcoin/blob/master/src/txmempool.cpp#L1029

**Comment by instagibbs** [comment]
cc @rustyrussell

**Comment by vincenzopalazzo** [comment]
Looks like duplicated https://github.com/ElementsProject/lightning/issues/6380 but this was the first one :)

**Comment by rustyrussell** [comment]
Actually, I looked through our code.  We only use minfee to check the other side for validity, not as a basis for what fees we send.  So fixing this is less important than I thought,and it's ugly (we have to keep some historical fee info in our db, since we're often restarted at the same time as bitcoind).

**Comment by rustyrussell** [comment]
So, I'm ignoring this, since adding more fee restrictions is probably a bad idea!
