### ISSUE TITLE
Temporary Channel Failure in forward

### ISSUE THREAD

**Issue by frbitten** [ElementsProject/lightning#6277]
I receive every day at least 3 forwards with local error of "Temporary Channel Failure". What would this error be and how do I identify the cause of it?

I didn't notice any offline period in the times that the errors happened.

Thanks

**Comment by vincenzopalazzo** [comment]
This is a really good question and I try to summarize it here https://bitcoin.stackexchange.com/questions/118148/analyze-failed-routing-in-core-lightning/118310#118310

There is no easy way to diagnostic a failure because we do not have enough information to do it, but we can do a better job at least trying to guess.
