### ISSUE TITLE
Backups - missing remote storage additional info

### ISSUE THREAD

**Issue by dcrystalj** [ElementsProject/lightning#6289]
### Issue and Steps to Reproduce
Poor documentation about remote backup potential problems.

### What's missing
I want to mount backup folder using sshfs but Im not sure if I need `sshfs_sync` or `no_readahead` option.
Might there be scenario that node will crash exactly during transfer and I would have lost node && have corrupt backup ? Would this broken backup at least serve as static channel backup ?

**Comment by vincenzopalazzo** [comment]
cc @adi2011

**Comment by adi2011** [comment]
Since peer storage contains an encrypted blob. I think if we don't have the whole blob, it'd not be possible to decrypt it. Hence, it's of no use unfortunately.

Possible Remedy:
Encrypt each channel's data separately so that we can decrypt one-by-one.
Issue:
Size occupied by each channel increases and that is not a good thing because we only have 64kb for peer storage.

**Comment by ShahanaFarooqui** [comment]
> ### What's missing
> I want to mount backup folder using sshfs but Im not sure if I need `sshfs_sync` or `no_readahead` option. 

Choosing between these options is out of scope of CLN project and should depend on user's discretion.

Other questions have been already answered by @adi2011, so closing the issue now.
