### ISSUE TITLE
gRPC ListPeers fails due to missing variant SENT_REMOVE_COMMIT

### ISSUE THREAD

**Issue by 2Fast2BCn** [ElementsProject/lightning#6318]
When calling the gRPC we receive the following error:

```
rpc error:
code = Unknown
desc = Error calling method ListPeers:
  RpcError {
    code: None,
    message: "Malformed response from lightningd: unknown variant `SENT_REMOVE_COMMIT`, expected one of `SENT_ADD_HTLC`, `SENT_ADD_COMMIT`, `RCVD_ADD_REVOCATION`, `RCVD_ADD_ACK_COMMIT`, `SENT_ADD_ACK_REVOCATION`, `RCVD_ADD_ACK_REVOCATION`, `RCVD_REMOVE_HTLC`, `RCVD_REMOVE_COMMIT`, `SENT_REMOVE_REVOCATION`, `SENT_REMOVE_ACK_COMMIT`, `RCVD_REMOVE_ACK_REVOCATION`"
 }
```

**Comment by cdecker** [comment]
The schemas appear to have sliced that enum based on where it is being used, which means that when we copied one instance to build the `HtlcState` enum in the Rust library we were missing the states that could not appear in that particular instance, however they may appear in other instances.

I have a version that combines all HTLC states into single enum. Interestingly enough I seem to have stumbled over this before and only the cln-grpc crate was missing some entires, but the error points at cln-rpc. I'll publish my fix, but leave this open because I'm not sure this is the fix we need.
