### ISSUE TITLE
lightning-cli pay is dangerous

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#633]
Right now the `pay` command is pretty dangerous.

On mainnet it's really easy for me to say "hey pay me 10 sats" and then give them a bolt11 that is actually 10,000 bits instead. `pay` will just do exactly that without displaying anything. I have found myself trusting without verifying while paying mainnet invoices (maybe I need one of those shirts).

Perhaps there should be a porcelain command for pay that displays the decoded invoice, and then prompts a confirmation.

**Comment by ZmnSCPxj** [comment]
Well the amount is in the HRP of the invoice, in theory so that human users can confirm the amount there:

1.  `lnbc100n1` = `lnbc100000p` = 10 satoshi
2.  `lnbc10m1` = `lnbc10000u1` = `lnbc10000000n1` = `lnbc10000000000p1` = 10,000 bits = 10mBTC

Of course, all those zeroes are an accident waiting to happen. . . . . . .

**Comment by ZmnSCPxj** [comment]
I suddenly realized that `contrib/lightning-pay` is the porcelain you are asking for.

**Comment by jb55** [comment]
Hmm not quite, it doesn't look like you can give this script a bolt11.
This actually wouldn't be that difficult to put together, I'll take a
stab at a simple script that does this.

**Comment by cdecker** [comment]
That'd be great, it should be a simple matter of calling `decodepay`, showing the output and then reading the `y` or `n` before issuing `pay` :-)

**Comment by jb55** [comment]
I'm still concerned that `pay` might be misused in the future.

Perhaps we could have a warning in the documentation string, or rename
it to something more scary.

**Comment by cdecker** [comment]
Well this is the low level interface, `bitcoind`s `sendtoaddress` and similar are also one-shot instructions. I'm not too worried, as long as the user interfaces make sure to show the details before sending.

**Comment by jb55** [comment]
`sendtoaddress` being a one shot command isn't a problem because you are typing in the amount manually. I didn't even realize that the "human readable" part of the invoice was a thing until I read the spec.

**Comment by rustyrussell** [comment]
So, pay is even more dangerous because it will use the "best" route, even if it's stupidly expensive.  The low-level getroute / sendpay API is designed for more nuanced use, but putting a fee percent limit (default 1%?)  into pay would be a win.

Also, the old contrib/ script should be updated to print the description and amount, and prompt...

**Comment by ZmnSCPxj** [comment]
Default 0.5% instead....

**Comment by ZmnSCPxj** [comment]
I would consider solved in practice. There is risk that people will miscount the number of digits in the hrp of the invoice, but am not certain if the c-lightning `pay` command is the place to put such double-checks in.

**Comment by cdecker** [comment]
Great, closing this as solved, and I agree completely that checking the amount should be better dealt with in a GUI built on top of the raw RPC.
