### ISSUE TITLE
Cannot generate a valid invoice with a private channel having low spendable_msat?

### ISSUE THREAD

**Issue by 21M4TW** [ElementsProject/lightning#6427]
I have CLN configured with a single private channel. When I try generating an invoice, route hints do not get generated within the invoice if spendable_msat is low for the channel, even if receivable_msat is about 60% greater than the invoice. I think it might be the same issue as https://github.com/ElementsProject/lightning/issues/3742 ? This should not happen, correct? Thanks!

lightning-cli returns the following warning, which does not make sense:
"warning_capacity": "Insufficient incoming channel capacity to pay invoice"

**Comment by 21M4TW** [comment]
Here are some findings:
lightningd: routehint: {"jsonrpc":"2.0","id":"cli:invoice#1234567/cln:listincoming#12","result":{"incoming":[]}}
lightningd: needed =123456000msat, avail_capacity = 0msat, private_capacity = 0msat, offline_capacity = 0msat, deadend_capacity = 0msat

Also I have found that this if statement in plugins/topology.c  gets triggered:
if (!ourchan->half[!dir].enabled) 

So it looks like the channel's half is disabled and this is what is preventing routehint from working? I am still digging through the code to see if I can fix it...

**Comment by cdecker** [comment]
The problem here Is that in order to add a route hint we need to know what the peer is asking as fees (they'll be forwarding the incoming HTLCs and leverage the fees on that last hop). In this case we are missing their channel_update, and commenting that statement read uninitialized memory which happened to return a CLTV delta of 0 (I'm guessing it may also have set a zero base and prop fees though that depends on the memory contents in that uninitialized memory.

Any payment with that broken route hint will fail (the peer isn't getting fees and the cltv delta is wrong). The current behavior of not including channels for which the peer has not provided the parameters is correct.
