### ISSUE TITLE
Add unsubscribe method for pyln plugin

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ElementsProject/lightning#6447]
Python decorators, including `@plugin.subscribe`,  are applied when the function is defined, which is typically when the module is imported, and not each time the function is called. 

Adding `unsubscribe` method for pyln-client's plugin will be helpful for error handling, retry attempts if a subscription doesn't work, etc. For example, wildcard subscription("*") is not allowed before v23.08. Core lightning will shutdown if user tries to run clnrest with older versions.

**Comment by cdecker** [comment]
Is it even possible to unsubscribe? We build the list of subscriptions at `getmanifest` time, and cannot modify it at a later point in time. That is on purpose. It would certainly be possible to just drop the notifications in `pyln-client` but what would the advantage of that be over just checking in the handling function itself?

That being said, if you mean to retry a `getmanifest` call after a restart, potentially because you learned that the `lightningd` does not have that topic, I'd suggest not to use the annotations, but use the `Plugin.add_subscription()` method to programmatically add a subscription based on your information.

https://github.com/ElementsProject/lightning/blob/620a61ee096b34ee19b9c4606535eacd4e23a296/contrib/pyln-client/pyln/client/plugin.py#L344-L374

This is by the way also what is being used under the hood for the annotations:

https://github.com/ElementsProject/lightning/blob/620a61ee096b34ee19b9c4606535eacd4e23a296/contrib/pyln-client/pyln/client/plugin.py#L376-L385

So just do something like this:

```python3
plugin = Plugin()

def my_handler_func(*args, **kwargs):
    print("success")

if lightning_version in ['v23.08']:
    plugin.add_subscription("*", my_handler_func)
else:
    print("too bad")
```

**Comment by ShahanaFarooqui** [comment]
Thanks for the suggestion. Using direct method solved my current issue. I would still recommend to add unsubscribe option in future releases (if possible). It might be helpful when we will allow users to add/remove subscriptions dynamically.
