### ISSUE TITLE
Passing negative amount to splice_init fails with unrecognized option

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/lightning#6612]
Running v23.08 with `experimental_splicing` on Ubuntu 23.04, GNU bash, version 5.2.15.

Trying to splice in a positive amount "works" as expected:

```sh
lightning-cli splice_init ... 1sat
{
   "code": 354,
   "message": "splicing not supported"
}
```

Trying to splice out a negative amount doesn't:

```sh
lightning-cli splice_init ... -1sat
lightning-cli: -1sat: unrecognized option
```

I also tried `\-1sat` and `"1sat"`.

It does seem to work with `-k`:

```sh
lightning-cli splice_init -k channel_id=... amount=-1sat
{
   "code": 354,
   "message": "splicing not supported"
}
```

Maybe it's easier to just have `splice_in_init` and `splice_out_init` with only positive amounts? The rest of the RPCs would stay unchanged.

**Comment by ddustin** [comment]
The thinking was since you can only splice whole sat amounts and building signed the input types to use raw numbers was less effort / complication (sats / msats types do not allow negative values) , using raw signed values would work well for this. But perhaps that's worth reconsidering if it's breaking users' expectations.

**Comment by ddustin** [comment]
There was an issue where negative values (ie -100) would be interpreted as a command named "100".

PR #6675 now special cases "-" followed by a digit as a numerical value instead of an unrecognized command.

**Comment by ddustin** [comment]
Adding the `--` technique usage example to the splice_init documentation in PR #6677.
