### ISSUE TITLE
Channel funding RBF

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/lightning#668]
It's quite easy to underpay fees and then have to wait forever for a channel to open. It's inconvenient to have funds stuck in limbo and it's unsafe to just try to open another channel and hope for the transaction to never confirm.

Being able to bump the fee is very useful.  Is it possible to implement @ZmnSCPxj's suggestion from the [mailing list](https://lists.linuxfoundation.org/pipermail/lightning-dev/2018-January/000889.html) (copied below)?

```
1.  Send open_channel for channel #1
2.  Receive accept_channel for channel #1
3.  Create RBF-able funding transaction for low feerate.
4.  Send funding_created for channel #1
5.  Receive funding_signed for channel #1
6.  Wait on blockchain.  Since feerate is low, it does not confirm. So, we decide, we should increase fee rate.
7.  Send open_channel for channel #2 to same party.
8.  Receive accept_channel for channel #2.
9.  Create replacement funding transaction for high feerate.
10.  Send funding_created for channel #2.
11.  Receive funding_signed for channel #2
12.  Wait on blockchain. Because feerate is so high, it confirms quickly.
13.  Send funding_locked for channel #2, receive funding_locked for channel #2
14.  Let counterparty forget channel #1 (which is now impossible to make, as the funding transaction spends an already-spent UTXO).
```

There could still be a 1 _open_ channel per peer rule; just allow multiple _pending_ channels.

Documentation could point out that you shouldn't use this too often.

**Comment by ZmnSCPxj** [comment]
Unfortunately it will not be easy. If multiple pending channels are possible that greatly increases complexity of openingd and channeld, unless we do some magic. In any case we probably want to do myltiple channels per peer anyway, and suffer greater complexity in channeld and openingd.

You may also be interested in #475

**Comment by ZmnSCPxj** [comment]
What we could do would be to implement CPFP+RBF now, and design the rpc carefully so that properly compliant RPC users will still work under the full RBF scheme.

    lightning-cli startfundchannel node amount
     => channelid

    lightning-cli estimateacceleratefund channelid
     => feeincrease

    lightning-cli acceleratefund channelid
     => channelid
    # returns a new channelid.
    # in CPFP+RBF the same channelid is returned.
    # in full RBF a new channelid is returned

**Comment by Sjors** [comment]
That `acceleratefund` interface seems reasonable. I would add a `increase_funding_fee_by` argument to `acceleratefund`, and make it clear in the documentation that this amount is excluding the fee necessary for the CPFP transaction. `estimateacceleratefund` should either take a priority argument or return multiple answers.

**Comment by ZmnSCPxj** [comment]
The intent is to have a "seamless" upgrade from when we use CPFP+RBF to when we have full RBF, so fee increases on the `accceleratefund` interface would include CPFP feeincrease for now, then when we get around to full RBF we can have the first acceleration cheaper.

An issue is that when we do RBF the change is effectively locked since we cannot be sure the latest version is the one mined (a miner might win before the updated tx propagates to it, and this race cannot be removed, only reduced). So we cannot be sure which txout (old or new tx?) to use for withdrawals or other channels.

**Comment by whitslack** [comment]
> An issue is that when we do RBF the change is effectively locked

@ZmnSCPxj: Isn't the change locked anyway? I've never been able to fund a channel in C-Lightning by spending an unconfirmed UTxO.

**Comment by ZmnSCPxj** [comment]
What I refer to is the change output in the funding transaction.  If I understand the wallet code correctly the funding tx change output is added immediately to the set of spendable UTXOs, so it can be spent afterwards.  This is not safe in an RBF situation and we would need to wait for deep confirmation before doing so.

Unless our wallet code has changed since I last looked, in which case my comment might make no sense.

**Comment by whitslack** [comment]
The change output shows up in `listfunds` immediately as "unconfirmed", but it cannot be used to fund another channel until it is confirmed.

**Comment by niftynei** [comment]
The v2 channel establishment [proposal](https://github.com/lightningnetwork/lightning-rfc/pull/524/files) I'm currently working on includes the facility to initiate an RBF for a channel open. I'm hoping to have something working within a few weeks.  Semantically, `acceleratefund` for init'ing an RBF looks very nice!

**Comment by jaonoctus** [comment]
https://github.com/ElementsProject/lightning/issues/475#issuecomment-812950021
