### ISSUE TITLE
docs/changelog: No mentions of clnrest.py docs or anything

### ISSUE THREAD

**Issue by IngwiePhoenix** [ElementsProject/lightning#6693]
Hello!

### Issue and Steps to Reproduce
I updated my CLN installation after experiencing channel connection issues on the previous version - and due to there not being native arm64-musl (Alpine, OpenWrt) packages, I compile from source, on a specified tag.

Upon startup, I discovered log lines about `plugin-clnrest.py` not finding some of the required dependencies, which prompted me to look at the changelog and saw a mention of a Pull Request, which pointed to a closed Pull Request with no further documentation.

Long story short: Whilst the commit history shows updated docs, it isn't immediately apparent, requires through digging from link to link and reading commit messages themselves, possibly the included changes, to even know what this is, what it implements exactly, which plugins it potentially replaces or deprecates and alike.

Sorry if this come across as annoyed or such but this is a great example of how not to document. :) 

Thus, I'd like for the changelog to be updated with a link pointing properly at the new plugin documentations.

### `getinfo` output
```json
{
   "id": "024ff0d07634390efb131904b10a64cf2e3300574b51902d493a360fb522f486fc",
   "alias": "Ingwie Phoenix LN",
   "color": "00ff00",
   "num_peers": 1,
   "num_pending_channels": 0,
   "num_active_channels": 1,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "torv3",
         "address": "75cg3ty67u5j3o2ndbvbldcnknzen2dbukvx6i3axzphaysbtcyxlcad.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "192.168.2.1",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "100.64.0.2",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9734
      },
      {
         "type": "ipv4",
         "address": "192.168.2.1",
         "port": 9734
      },
      {
         "type": "ipv4",
         "address": "100.64.0.2",
         "port": 9734
      }
   ],
   "version": "v23.08.1-modded",
   "blockheight": 808458,
   "network": "bitcoin",
   "fees_collected_msat": 0,
   "lightning-dir": "/usb/c-lightning/bitcoin",
   "our_features": {
      "init": "08a0000a0269a2",
      "node": "88a0000a0269a2",
      "channel": "",
      "invoice": "02000002024100"
   }
}
```

(ps. No idea where `-modded` comes from... I `make distclean`'d before the build, then did the configure/make dance.)

**Comment by ShahanaFarooqui** [comment]
We try to add as much information as possible on our release notes but the last release had so many important features that we were unable to list them all. That is also a main reason to add detailed list of change logs.

Apart from that, we post a detailed release blog on `blog.blockstream.com` for people who want to get more details about the release. However, due to the size of last release, blog has been divided in three parts this time. So `clnrest` was explained in the second part at `https://blog.blockstream.com/core-lightning-v23-08-satoshis-successor-part-ii-developer-experience/`. 

Also, we maintain all documentation related to CLN at `https://docs.corelightning.org/docs`. And you can find `clnrest` related documentation at `https://docs.corelightning.org/docs/rest` and live test it at `https://docs.corelightning.org/reference/post_rpc_method_resource`.

Finally, `clnrest` fails gracefully if a dependency is missing and will not adversely effect the node. 

Hope that these links will help. Closing the issue now. Thanks.
