### ISSUE TITLE
splice: bad commitment signature

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#6803]
From CI
[80.zip](https://github.com/ElementsProject/lightning/files/13068705/80.zip)

**Comment by ddustin** [comment]
Seems related to https://github.com/ElementsProject/lightning/issues/6810#event-10752401849 as these appear to both have to do with post-splice channel confirmation timing.

Relevant log, occurring immediately after state changing to `CHANNELD_AWAITING_SPLICE` to `CHANNELD_NORMAL`:

> FAILED tests/test_splicing.py::test_splice_out - pyln.client.lightning.RpcError: RPC call failed: method: pay, payload: {'bolt11': 'lnbcrt1n1pjnv93nsp5ruhvcutw7lras80x8mhetsa0zzlw7rk6qwdtyr6sty3xnhqnztnqpp5am76ft7tsvla88myg6t443367qguegyzwjxn9jn598al0y2y2dtsdq8deh47vcxqyjw5qcqp99qxpqysgqt7j7hfzu8awk7k87vlyndzg7kxvyf4hzl0juldnt3csgf6wkjk0qqzdh8svxp9nvd8wla5v08uf4zz0hcjrymv60qzyq3ww4ef6hx6qqwn9k4m'}, error: {'code': 210, 'message': '**Destination 022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59 is not reachable directly and all routehints were unusable.**', 'attempts': [{'status': 'failed', 'failreason': 'Destination 022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59 is not reachable directly and all routehints were unusable.', 'partid': 0, 'amount_msat': 100msat}]}

**Comment by ddustin** [comment]
I suspect this test failure will be fixed by this PR https://github.com/ElementsProject/lightning/pull/6815, which fixes an issue where the payment was attempted before the splice had mutually locked.

This raises a larger question though: Are we okay with a short period during `splice_mutual_lock` where payments can fail? If we want 100% uptime, we'll need a way to atomically update the routing system. I would need to study the routing system more to understand how that could be done 👨‍🎓

**Comment by ddustin** [comment]
Note: While titled bad commitment signature, I believe this log is giving us a routing failure. The log in Issue #6810 has a bad `node_signature_1` in the channel announcement.

**Comment by ddustin** [comment]
PR #6815 should fix this log. Thanks for posting it 🙏.
