### ISSUE TITLE
getroute includes route with a peer even though channel with peer is CLOSINGD_COMPLETE

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#682]
Even though I'm CLOSINGD_COMPLETE with a peer, getroute still considers that peer while framing route.
`getroute` considers that peer even when status changes to ONCHAIND_MUTUAL (after mining some blocks)   
Even if my connection with a peer has status "connected":false, getroute still takes that peer in account to form routes

**Comment by ZmnSCPxj** [comment]
Yes, it is a known issue that routing completely ignores the current state of local channels. I have some vague plans for that but have not laid them out conpletely, yet.

Roughly instead of routing from the local node, we first select one local channel to route from, then start routing from the counterparty on that channel (and do not route through local channels). That way the local channel selection can eliminate channels in known unuseable states.

**Comment by jb55** [comment]
I guess this is the same as #635 ?

**Comment by ZmnSCPxj** [comment]
And arguably #611.  In all cases, lightningd is ignoring the state of local channels during routing, when logically to a human being it already should be able to judge this  (it  has to know the local state in order to update it!) and select the best local channel to start routing from.

**Comment by Sgt-Miller** [comment]
How is the "best" channel selected?

**Comment by ZmnSCPxj** [comment]
Currently, it only considers feerates and cltv delta of other nodes, ignoring the current state of the local channel completely.  It should really do something like "do not use a channel that is in some closing state, and has enough msatoshi to cover the payment plus some maximum acceptable fee, and use best-fit/worst-fit/first-fit to select a valid local channel for the payment".
