### ISSUE TITLE
active=False channels

### ISSUE THREAD

**Issue by nstamato** [ElementsProject/lightning#691]
I have a node live on the main net with an open channel to blockstream, and while trying to put some analytics together on the properties of my network topology, I noticed that for two nodes that appear in my `getnodes` output, when I try to `getroute` to them, I get "Could not find a route". I looked into one of the nodes and it seems that both me and node X are connected to the blockstream node, but while X->blockstream channel is active, blockstream->X is not:
```
{'source': '02fe82c6a79afd92b347e593de194fd16c86f0c9fcaab950b51be45e27bb3eb354', 'destination': '02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432', 'short_channel_id': '504817:684:1', 'flags': 1, 'active': True, 'public': True, 'last_update': 1516276839, 'base_fee_millisatoshi': 546000, 'fee_per_millionth': 10, 'delay': 14}
{'source': '02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432', 'destination': '02fe82c6a79afd92b347e593de194fd16c86f0c9fcaab950b51be45e27bb3eb354', 'short_channel_id': '504817:684:1', 'flags': 0, 'active': False, 'public': True, 'last_update': 1516278413, 'base_fee_millisatoshi': 546000, 'fee_per_millionth': 10, 'delay': 14}
```
Is it normal that one direction is active and the other is not? What exactly does it mean for a channel to be active? Is there any way to use `lightning-cli` to get the properties of a channel (e.g total capacity)? I don't see that in the `getchannels` output.

FYI, in case anyone is interested, from my one open channel to blockstream, I have a route to all other 67 nodes with at least one open channel on the network (except the two I mention above), with
```
Median distance = 2.0
Average distance = 2.5625
Max distance = 5
```

**Comment by cdecker** [comment]
`active=true` means that the channel has not been disabled by the `source` endpoint of the channel. It's usually caused by the other endpoint disconnecting/stopping. The `source` endpoint notifies the rest of the network that this channel is not usable for routing temporarily. If the other endpoint doesn't come back at all  then the channel will eventually be closed altogether and disappear from the topology.

Thanks for the metrics @nstamato, wanted to do that myself at some point :wink:
