### ISSUE TITLE
Add documentation for `dev-forget-channel` command too

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ElementsProject/lightning#6923]
Currently, documentation for `dev-forget-channel` command is missing and will be helpful to add for easier user reference.

For the RPC command:

- [ ] Add `*.request.json` in `doc/schemas` with RPC request inputs types, descriptions, etc.
- [ ] Add `*.schema.json` in `doc/schemas`, detailing RPC response, fields descriptions, defaults, etc.
- [ ] Include `lightning-*.7.md` file in `doc`, where `RETURN VALUE` should be generated dynamically using `tools/fromschema.py` script
- [ ] `make doc-all` should auto generate `lightning-*.7` from `lightning-*.7.md`

**Comment by bitkarrot** [comment]
@ecurrencyhodler told me about this issue on stakwork. I am interested. @ShahanaFarooqui

**Comment by cdecker** [comment]
I wonder if we should really be documenting these. We decided against including the `dev-` commands in the help output because they are, well, intended for developers. In addition they are commands that are mostly used to manipulate the internals during tests, and do not have a solid interface, i.e., we'd continually be breaking semantic versioning, or we'd have to start building tiny ad-hoc commands to test things in the tests.

These then would also be documented, exposed to users, and users that do not know the intricacies of the `dev-` commands may end up trying them out and destroying their node.

@rustyrussell what do you think?

**Comment by ShahanaFarooqui** [comment]
Adding some context from where it started:
Reference issue:  https://github.com/Ride-The-Lightning/RTL/issues/1280

A user wanted to forget 3 channels and was unable to execute the command due to missing `short_channel_id`. Finally, @rustyrussell confirmed that `channel_id` can also be used. Then he asked to open an issue to add `dev` documentation with details so that advanced users can refer to the documentation if needed. 

However, we can show these commands under `advanced` category with extra warning, if that helps.

**Comment by bitkarrot** [comment]
I was just about to ask @ShahanaFarooqui to clarify the task. 

Either way I am totally ok what your decision is, to document or not to document. I just got my environment updated and probably won't have time to work on it immediately, so no worries if you guys want to cancel this task. We can also just make a framework and leave it with placeholders if you want.

**Comment by ShahanaFarooqui** [comment]
@cdecker After confirming with @rustyrussell, we decided to only add documentation for `dev-forget-channel`. So updated the issue accordingly.

**Comment by bitkarrot** [comment]
@ShahanaFarooqui ok I'll take a look this weekend and will send questions here if not clear. thanks for the update
