### ISSUE TITLE
semver broken between cln-rpc 1.0.2 and 1.0.7

### ISSUE THREAD

**Issue by dpc** [ElementsProject/lightning#6934]
### Issue and Steps to Reproduce

These re-exports were removed at some point and dependencies that used them can fail after `cargo update`

https://docs.rs/cln-rpc/0.1.2/cln_rpc/model/index.html#reexports

**Comment by cdecker** [comment]
We do not guarantee semantic version behavior until after 0.1.X. This is in order to retain flexibility in evolving the API, and not to limit our ability to improve ergonomics. You'll surely understand that the API needs to evolve, otherwise we'd end up backed in a corner very quickly. Starting from 1.X.Y we will make backwards compatibility guarantees.
