### ISSUE TITLE
cln 23.11: force close tracking is stuck sometimes

### ISSUE THREAD

**Issue by daywalker90** [ElementsProject/lightning#6951]
I never noticed this on previous cln versions but i have a force close right now where in the listpeerchannels' `status` field the tracking of 
`outputs unresolved: in XXX blocks will spend DELAYED_OUTPUT_TO_US` is stuck. A restart gets it unstuck for a while.

The only thing special about this peer is that i had 2 channels to them, (so right now 1 in channeld_normal, 1 onchain).

The blockheight in `getinfo` is always correct and in sync with bitcoind, which is also running fine and cln itself is not hanging in any other part that i noticed.

bitcoind: 25.0
postgresql: 15.5

**Comment by daywalker90** [comment]
On yet another force close i noticed that when the force close tx has just 1 confirmation it shows this:
```
"ONCHAIN:5 outputs unresolved: in 4294967294 blocks will spend OUR_HTLC (aa06420b249392cb6a000e484a5695d88ec14023f18b7093e6fa1b1f36dbebe1:0) using OUR_HTLC_TIMEOUT_TX"
```
After another confirmation it goes back to normal (aslong as it does not get stuck immediately)

**Comment by daywalker90** [comment]
Regarding my 2nd post:

i did a rescan and it fixed the tracking of 471e5985cd0524938d1eca6750fd8d6d37a22232669302e22d3cdc233dd6b5ad:2, now it just wants to wait for another output of a htlc that i dont think can be mined with current fees.

**Comment by btweenthebars** [comment]
I'm running v23.11.1. I have a similar issue of ""ONCHAIN:N outputs unresolved: waiting confirmation that we spent DELAYED_OUTPUT_TO_US (xxxxxxx:y) using OUR_DELAYED_RETURN_TO_WALLET""

Currently I have about 7 channels stuck in this stage. I've checked blockexplorers on the said tx (xxxxxxx:y), browsing thru all the txs following it. I see nothing unconfirmed. What is it waiting for exactly then.

I think they are sitting there even before christmas, so more than a month.

To my feeling, in the previous versions, it could be stuck in this stage, but it never be this long. I don't know if it's a correct behavior and CLN is tracking them or a bug. It it's correct, shouldn't it provide more explanation of what's it's waiting for, which transaction etc, so user won't get frustrated.

Did you say that restarting / rescanning wallet can resolve the issue ?

**Comment by daywalker90** [comment]
That is likely something different @btweenthebars . Probably a regular fee problem where your tx is below min relay fee or cant afford the current fee. You can check the logs by filter for that peer id i think to see whats the problem.

**Comment by btweenthebars** [comment]
I just tried to track down one of the force closes that are stuck in the "ONCHAIN:N outputs unresolved: waiting confirmation that we spent DELAYED_OUTPUT_TO_US (xxxxxxx:y) using OUR_DELAYED_RETURN_TO_WALLET" . I turned on the debug log to see rawtransactions.

As you can see, everything was already swept. 
https://mempool.space/address/bc1qw942d5rw9araw3r98qxgq7c7dghxzv7te7dhy8vyrv20qvt59dqs3rkrn9

and I have "16ac190b9193aecdfc75546f80c97a23d78256376850541a12e837453d6a9297:0" back into my listfunds.

However, in the debug log, seems like it's trying to send the following rawtx

Feerate for target 827053 (+271 blocks) is 253, fee 122sat of 1046626sat

RBF onchain txid 7edc76e3886a35a1a13e298c3c67ff3e8aeafaaccef27b59aeee8a513b06946a (fee 122sat) with txid 7edc76e3886a35a1a13e298c3c67ff3e8aeafaaccef27b59aeee8a513b06946a (fee 122sat)

RBF 02000000000101f1dc8f5658792ce93484e15a0d555eec4b6b720be46e01c38c9d5e7d650a0acb0000000000a401000001e8f70f0000000000160014fffc7a03b7fa29ca9f5b69ec800b7af0e74ed1be03473044022009817783257b276359342f97e218ad6367f09fc7b337c80f4fdae19a28cc46180220441a18350974449973a8d5c8cf8457a0e302b3697ad2d98a3b8391a4fbdba77301004d632102214439ed797bdf6021dc4cf5eee490f16b7e4941ee4523c51bce68cb27c08e516702a401b275210398e964403e66dfce484e47fba7316e1d7e9bed2125679fe8c150565486fddead68ac00000000

Which is invalid, because c8cd75d2b6742d02a231a47fef9fca29fb3aaf1b90916923572962c0610df492:0 was already spent back to my wallet (probably from one of previous attempts)

If CLN is waiting for that, it will never forget the channel.
Doesn't it sound like a bug, or I'm just being confused ?
