### ISSUE TITLE
Feature Requests: Connection failed in CLI, timeout when using lightning-cli pay

### ISSUE THREAD

**Issue by alaniz3** [ElementsProject/lightning#708]
I have recently started testing and exploring c-lightning. I have a few UX suggestions that I think could help improve the overall experience.

- After attempting to connect to several nodes found on https://explorer.acinq.co and elsewhere I noticed that there is no error message or timeout when trying to connect to a node that isn't responding. Unless the issue was caused by something else (although after check the daemon debug log output I think a failed connection was the issue) the CLI tool seemed to hang when attempting to connect to a node that wasn't responding. A timeout and subsequent error message here would be useful.

- When attempting to use the pay command I had a similar issue with the CLI tool "hanging". I am not sure but I think the failure in payment has to do with nodes not responding (or a payment getting stuck at the next hop?). I attempted to pay an invoice, the CLI tool "hanged", when force closing the CLI and re-attempting to pay I receive the message "still in progress", again an error message here or a timeout instead of this "hanging" would improve the overall experience when using the CLI. Also anyone care to elaborate as to why the payment is "still in progress"?

**Comment by ZmnSCPxj** [comment]
Re: "still in progress", it means some node along the route has stalled.  We cannot assume that the payment will fail to go through (the remote node might get around to it at any time until the CLTV timeout, and we cannot really know which remote node is stalling).  This may be due to the node going down after it forwarded the HTLC but before the HTLC is fulfilled, or the load may be overloaded (a node going down before forwarding HTLC should be detectable by the previous node, which is the one which will respond to us with a definitive failure to route).

There is a timeout to `pay`, it is simply the timeout is automatically computed (it is the timeout used in the timelock part of the HTLC, and is the total CLTV-delta along the route up to the advertised CLTV-delta of the payee) and is measured in *days*.  Perhaps a better interface to the payment system can be designed: an `asyncpay` that returns a payment ID immediately, a `querypay` that queries the status of the payment, and a `waitpay` that waits for the entire precomputed timeout or until definite failure or success.

**Comment by alaniz3** [comment]
Thanks! I think your suggestion of a more elaborate set of payment API calls would indeed help the overall user experience. I've started testing c-lightning because I intend to build some apps using it and it would indeed be helpful to have these extra queries. Also maybe a timeout in the pay command with a subsequent "still in progress" output (or something more elaborate) would also be nice! (Although this can be implemented at the app layer itself too).

**Comment by ZmnSCPxj** [comment]
#1218 adds a timeout to `pay` and does a good part of what you wanted for `pay`.  The `connect` timeout is now about 50 seconds as of now, is that ok?

**Comment by alaniz3** [comment]
Awesome! Will check out, cheers!

**Comment by ZmnSCPxj** [comment]
Closing, since the issues have been resolved as far as we know.
