### ISSUE TITLE
Ability to delete all expired invoices at once

### ISSUE THREAD

**Issue by aesedepece** [ElementsProject/lightning#711]
**Motivation**

For many reasons (including legal ones), some merchants may want to keep record of all LN invoices, including expired ones. However, it is to be expected that that's not the case for everyone. In most cases, there's no point on keeping expired invoices stored forever. 

As of today, if one user wants to save disk space and keep her invoice history clean of unnecesary information, she will need to issue `listinvoices` and then go over the potentially huge list of invoices, `grep` the expired ones and issuing `delinvoice` for each of them. 

**Solution**

I'm proposing the ability to manually delete all expired invoices at once.

The API for this feature could be as follows:

```
lightning-cli delexpiredinvoices
```

Another option would be overloading the `delinvoice` method with two different signatures:

```
lightning-cli delinvoice <status> # New "delete all with status X" functionality
lightning-cli delinvoice <stauts> <label> # Existing method
```
Nevertheless, I'm not particularly in favour of this option because (1) reverses the signature of an existing method, and (2) I can't see why would anyone want to bulk delete invoices with a status different to `expired`.

What do you think about this proposal? If you support it but it somehow diverts from your immediate roadmap, I can find the time to work on it.

**Comment by aesedepece** [comment]
P.S.: In addition to this feature, I think it would be nice to have some optional setting to schedule automatic deletion of invoices once they have been expired for some time. If you agree, I can create a separate issue to track that.

**Comment by rustyrussell** [comment]
There's nothing *wrong* with this (and #1107) , but I think it's not what people actually want.

Can we implement 'autocleaninvoices <?seconds> <?minexpiry>' which cleans expired invoices older than <minexpiry) (default 24 hours) every <seconds> (default 1 hour)?  seconds=0 means disable autocleaning.

Important subtleties:

* It's nice to fail a payment with information that the invoice has expired, rather than "IDK WTF?", even though the client should be checking expiry too.
* This post-expiry may be important for onchain payments later: we might want to note that we got paid for an expired invoice somehow.
* I don't know if autocleaninvocies should be on by default: maybe not yet, but plan to?
* It should do a clean before returning, ideally returning the number cleaned, so you can toggle it on and off if you really do want a `delexpiredinvoices`.

Thoughts?

**Comment by ZmnSCPxj** [comment]
@aesedepece mentioned the auto-clean also, so I suppose that is considered desirable also.

I suppose minexpiry is used thusly: `DELETE FROM invoices WHERE state = EXPIRED AND expiry_time < NOW() - minexpiry;`

**Comment by shesek** [comment]
Related (auto-delete implementation in Lightning Charge): https://github.com/ElementsProject/lightning-charge/blob/4ffaa487b380ada0b71efa40e4fcf7a4af645f90/src/model.js#L60-L72
