### ISSUE TITLE
Offers: not getting invoice back after sending invoice request for CLN offer

### ISSUE THREAD

**Issue by orbitalturtle** [ElementsProject/lightning#7110]
### Issue and Steps to Reproduce

I think @thebluematt already reported this issue offline but I wanted to create an issue to keep tabs on it.

It seems in some cases CLN doesn't send an invoice back when it can't find a route to the introduction node of a blinded path provided by an invoice request. CLN might want to just direct connect to the introduction node, which is what LDK does for now while onion messaging support is still low

As for reproducing this issue, personally the setup I had when running into this was... Had a network of test nodes like so:

`LND <-> CLN <-> CLN2`

On top of the LND node I run [LNDK](https://github.com/lndk-org/lndk), in particular [this branch](https://github.com/lndk-org/lndk/pull/91), which in turn uses LDK to manage the offers flow, invoice requests, waiting for an invoice, and all that jazz.

CLN2 creates the offer and we pay with LNDK. We send an invoice request out but don't get the invoice back.

**Comment by rustyrussell** [comment]
Yeah, this is because we figure out the route first (or if we have to direct connect) then create the return route exactly backwards from that, so it always starts at the destination.  I have WIP patch to direct connect in this case, but it is a bit more complex because we don't want someone to be able to DoS us by making us connect to everyone on the network, so we need the concept of "transient" connections, hence it didn't make this release.

**Comment by moneyball** [comment]
There are users hoping to support BOLT 12 running into this problem. Any idea on when it will be fixed?
