### ISSUE TITLE
unable to reopen uncooperative channel close between 2 c-lightning.

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#720]
from one side

```
connect 02cbaa0f40db314ef15ad2b1340e3c5c18b0a5c88551ce2debc1fd76d64e061873 89.44.100.89
"channel ALL: lightning_closingd: Bad closing_signed signature for 02000000014ff11e728c031aa8972670561561b5222136c5b31c2ddcdaee47d8ff764eccac0000000000ffffffff0228ef100000000000160014ba4e09564101294fd74689f18df00e0418bcb7600432e30000000000160014fafde91dda10fd27ba51a9640d1fa2bfae30fc7200000000 (and trimmed version 02000000014ff11e728c031aa8972670561561b5222136c5b31c2ddcdaee47d8ff764eccac0000000000ffffffff010432e30000000000160014fafde91dda10fd27ba51a9640d1fa2bfae30fc7200000000)"

```
and from the other

```
connect 030ea986bd47ad766a8c75b19dc20abac2ff4579c4b50b0bdf7ee89b05ff7ddb6f 172.104.242.219
"channel ALL: lightning_closingd: Bad closing_signed signature for 02000000014ff11e728c031aa8972670561561b5222136c5b31c2ddcdaee47d8ff764eccac0000000000ffffffff0227ef100000000000160014ba4e09564101294fd74689f18df00e0418bcb7602234e30000000000160014fafde91dda10fd27ba51a9640d1fa2bfae30fc7200000000 (and trimmed version 02000000014ff11e728c031aa8972670561561b5222136c5b31c2ddcdaee47d8ff764eccac0000000000ffffffff0127ef100000000000160014ba4e09564101294fd74689f18df00e0418bcb76000000000)"

```

I think i closed the channel from one of them while the other one was offline. I might have tried some connects and fundchannels between them, but i'm not sure.

**Comment by Ulmo** [comment]
Generally speaking, I'd also like to be able to reconnect nodes that have failed before.  Is disconnection permanent?

For instance:

1.  When I got an insufficient fee error (or similar; I can't remember), I tried increasing fee, and suddenly, my node that I did that on had almost all of my peers close my channels.  Now, I can't reopen the channels to those peers, first of all, because I can't even get connected to them (it gives me the prior closing status as a reason not to reopen).
2.  When clearing out the few channels still open on my node in preparation for creating a new node without that sullied history, I moved any remaining channels over to my other node that is still working fine.  Now, I noticed that those few channels I closed on the node I closed them on I cannot even reconnect to, much less fund new channels?  What if I want to increase funding or otherwise reopen channels to those nodes?  Can I increase funds in an existing channel?  Can I add new channels between the same two nodes, to take on new duties (such as increased funding)?  It seems no, but I'd like to be able to.

**Comment by ZmnSCPxj** [comment]
#975 was merged, which includes https://github.com/ElementsProject/lightning/pull/975/commits/ea40ebe6fb8043f81ec9ba60911b0f96903a32d8, and should now be able to reopen once the channel is completely closed.

**Comment by ZmnSCPxj** [comment]
Page @rustyrussell

**Comment by thestick613** [comment]
I'd love to test this, but my other node is kind of dead #772 :/

**Comment by rustyrussell** [comment]
I'm closing this: we should now be reliably broadcasting the unilateral close, so there is no way to reopen that channel.  We can, however, reopen a new one.
