### ISSUE TITLE
Where is the private key located after created by 'newaddr'

### ISSUE THREAD

**Issue by softgear** [ElementsProject/lightning#727]
Thanks

**Comment by Saibato** [comment]
The generatior random bytes are in hsm_secret depending on main or testnet choice at first start the first key ist created by using the seed bitcoin seed and incremented salt until it fits wally. 
This yield to the master_extkey 

Then ext_priv and ext_pub. derive from that
So basicly one can say it is stored in hsm_secret but this is no key ist only a sort of generator but it will allways init your master_ext key note depending on main or testnet the random gerator byte yield to different master keys .
So allways backup  this file.

**Comment by BitBargain** [comment]
Any chance to get a 'dumpprivkey' method? The funds disappeared from lnd despite still being unspent on the chain. Withdraw says not enough funds (the first time it hung, the second time it said not enough funds, but no transactions were created or broadcasted).

**Comment by cdecker** [comment]
> The funds disappeared from lnd despite still being unspent on the chain.

Are you using c-lightning or lnd?

**Comment by cdecker** [comment]
For the general desire to have `dumpprivkey` we have #746. I think the funds that disappeared I'm unclear on where they disappeared from. We have added funds allocated to channels in #964, which should address the confusion that funds disappearing from `listfunds` and being allocated to channels was causing.

I'm closing this since I think both issues are addressed, or tracked somewhere else.
