### ISSUE TITLE
What does this error message mean? : "Funding satoshi must be <= 16777215"

### ISSUE THREAD

**Issue by johnta0** [ElementsProject/lightning#734]
I'm trying to test lightning payment with my VPS. I've already connected 2 nodes with ```cli/lightningcli connect <nodeID>``` commands. 

But when I tried to ```cli/lightning fundchannel <nodeID> <amount>```, I got the error message which says: ""Error packet: channel <nodeID>: feerate_per_kw 254 below minimum 10000". 

So I set the funding amount larger, and I got this next error message:

```
"Funding satoshi must be <= 16777215"
```

What does it mean? What am I supposed to do to resolve this?

I appreciate your help.

**Comment by ZmnSCPxj** [comment]
It means exactly what it says.  Funding amount must be 16777215 satoshi or lower.

Note that the `feerate_per_kw` problem is not about the funding amount being too low.  That issue is with you and the other node not being able to agree on a "near enough" feerate.  This usually happens if your `bitcoind` is new (only a few hours old) and is unable to generate realistic feerates.  IF your `bitcoind` has been running for days already, however, we need to see the logs and in particular check about feerate reports of lightningd that it gets from bitcoind.

**Comment by johnta0** [comment]
@ZmnSCPxj 
Thanks! 
Now I understand very well why I ran into``` feerate_per_kw``` problem. Actually I just set up my bitcoind today. 

So all I should do is to wait for my bitcoinds to agree on a near fee rate, and see what happens, right? 

Thank you very much.

**Comment by johnta0** [comment]
I actually thought ```<= ``` to be an arrow. It led me to my misunderstanding.
