### ISSUE TITLE
How to use SSL with `clnrest` plugin?

### ISSUE THREAD

**Issue by thebrandonlucas** [ElementsProject/lightning#7391]
After following the [clnrest](https://docs.corelightning.org/docs/rest) docs and successfully setting it up, I am having trouble using the autogenerated certs to make HTTPS requests from client apps. If I run:

> curl --insecure -X POST 'https://my-domain:3010/v1/getinfo' -H 'Rune: my-rune'

I get the appropriate response:

> {"id": "02360...", "alias": "IRATENIGHT", "color": "02360d", ... "", "invoice": "02000002024100"}}

However if I run without the `--insecure` flag:

> curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

> curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

So I downloaded the `ca.pem` to my local machine, and ran again with:

> curl --cacert /path/to/cert -X POST 'https://my-domain:3010/v1/getinfo' -H 'Rune: my-rune'

And got the same error as above. What am I doing wrong?

Apologies if this is a naiive question, thanks for any help!

**Comment by cdecker** [comment]
The certificate is a self-signed certificate, which means that there was no certificate authority (CA) trusted by browser makers and other tool makers, that certified that you own the domain `my-domain`. In order to get a valid certified certificate matching your domain you'll have to find a CA, prove ownership of the domain and have it sign your certificate.

As the instructions to do so differ by CA, please refer to their docs. I'd suggest looking into letsencrypt as there is quite a bit of tooling to automate the certificate creation and renewal.

**Comment by thebrandonlucas** [comment]
Thank you!
