### ISSUE TITLE
can't delete offers

### ISSUE THREAD

**Issue by AndySchroder** [ElementsProject/lightning#7710]
There is no RPC command to delete offers, only disable offers. Please add this.

**Comment by vincenzopalazzo** [comment]
Please see https://github.com/ElementsProject/lightning/issues/4744

This was already discussed. So if you would like to delete an offer, just disable it otherwise there are corner cases that you do not want to fall in.

E.g: if you delete an offer, you need to delete all the invoices and payments received, otherwise you have a zombi reference, this is not nice IMHO especially when the user can do it without knowing

**Comment by AndySchroder** [comment]
I'm fine with not being able to delete and only disable if you fix https://github.com/ElementsProject/lightning/issues/7711 .
