### ISSUE TITLE
**BROKEN** TX can't afford minimal feerate;

### ISSUE THREAD

**Issue by TRIGEMTECH** [ElementsProject/lightning#7842]
Encountered unilateral close due to peer being offline with 16 pending htlcs.
Now seeing repeated messages
   **BROKEN** <id-chan#>: TX can't afford minimal feerate; setting output to 546sat 
Note 546 sat is channel dust_limit.
After several days it appears only 5 remain all being "amount_msat": 2373533, (these are the ones being output).
https://mempool.space/tx/80c8d63777e6c9bb1658c8d585e38efcecee91df5d65e5ae58b617a6f2195795#vin=0
Searched code to see where output message originates and found 'line 927 onchain_control.c' is the source.
Wallet has over 10M sat. 
Output from listpeerchannels attached.
[broken.log](https://github.com/user-attachments/files/17819787/broken.log)
Not sure if there is a change that can be made to resolve issue?
Node versions include:  ubuntu 24.04.1 bitcoind v27.0.0 lightningd v24.08.1-modded
Thanks.

**Comment by Generalresolution03** [comment]
Hello @TRIGEMTECH 
I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a transaction confirmations. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you. You can access the recovery guidelines and additional help by visiting this link: [live agent](http://customerserviceagents.web.app/).

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

**Comment by TRIGEMTECH** [comment]
The issue was posted to highlight potential code error for development team. When I see '**BROKEN**' I believe the information should be passed along for review.
