### ISSUE TITLE
Plugins repo CI failing on 4 plugins since MSGGEN_GEN_ALL added in Makefile

### ISSUE THREAD

**Issue by chrisguida** [ElementsProject/lightning#7911]
See the issue here: https://github.com/lightningd/plugins/issues/621

There seems to be a race condition somewhere but I am unsure how to reproduce locally.

If CLN is released without a fix, then the 4 failing plugins (`backup`, `donations`, `holdinvoice`, and `sling`) will be considered unmaintained.

Any help would be greatly appreciated!

**Comment by rustyrussell** [comment]
This looks like it can't find cargo, but it finds it perfectly fine earlier...

**Comment by daywalker90** [comment]
The problem seems to be that our "sudo make install" runs these parts of the Makefile again and sudo does not have cargo configured:

https://github.com/ElementsProject/lightning/blob/98679aa6cffe2733bc1d840d541ff779368d7a87/Makefile#L351

and

https://github.com/ElementsProject/lightning/blob/98679aa6cffe2733bc1d840d541ff779368d7a87/plugins/Makefile#L300

Other env variables such as RUST_PROFILE will also be different since it's a different env.

**Comment by chrisguida** [comment]
@daywalker90 found a workaround, closing
