### ISSUE TITLE
close on non-NORMAL channel causes assert

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#82]
From @cedcker comment in #67 

>  https://gist.github.com/anonymous/251ce28774d9f0c094a5dbe06388b6bb
> 
>  Turns out it was a bit different. calling close on a channel that is neither in STATE_NORMAL nor   STATE_NORMAL_COMMITTING will trigger an assertion and fault our client. But it seems that we are conflating connection state and channel state in a few places.

**Comment by fivepiece** [comment]
Might be related, running two local nodes on regetst, accidentally tried to open a channel with a transaction that's not in the chain (sent the funds to the address in testnet by mistake), now both nodes are staying connected to each other, and the states are both :
 `STATE_OPEN_WAIT_ANCHORDEPTH_AND_THEIRCOMPLETE` (but the anchor tx was never accepted to regtest nodes' mempool).
Trying to connect again returns `Already connected to peer ..`, and trying to close the channel actually results in a `Fatal signal 6. Log dumped in crash.log`.

log files are at: [`logs`](https://gist.github.com/fivepiece/9b8f1aeca07aa9ab2cbd98b7529375eb)
The prefixes mean: oc = open channel, ac = accept channel.
I was thinking at first if there's a way to proceed from that state somehow, but now I think there probably isn't because `anchor_inputs` and `anchors` are set for this specific invalid tx.
