### ISSUE TITLE
Unknown network name 'mainnet'

### ISSUE THREAD

**Issue by kaibakker** [ElementsProject/lightning#848]
### Issue and Steps to Reproduce
I used the following docker image:

    docker run -u `id -u` -v `pwd`/data:/data -p 9112:9112 -p 9735:9735 -p 8333:8333 -e NETWORK=mainnet  -e API_TOKEN=mySecretToken shesek/lightning-charge

After downloading the blockchain and doing a restart of the docker image I get the following error:

    lightningd: --network: Unknown network name 'mainnet'

**Comment by cdecker** [comment]
It's known as `--network=bitcoin`

**Comment by shesek** [comment]
Lightning Charge [aliases](https://github.com/ElementsProject/lightning-charge/blob/b10b684c829c9d4bbc78bfec2cf00123a5d24094/bin/docker-entrypoint.sh#L8) "bitcoin" as "mainnet" since about 5 days ago, so this should've worked if you're using a recent docker image (`docker pull shesek/lightning-charge` to get the latest one). But using "bitcoin" is probably preferable anyway.

Also, note that this is c-lightning's issue tracker, not charge's.

**Comment by shesek** [comment]
And make sure to replace "mySecretToken" with your own secret token.
