### ISSUE TITLE
sendpay with wrong\no arguments causes lightningd to crash

### ISSUE THREAD

**Issue by gdassori** [ElementsProject/lightning#885]
before the sendpay the RPC was ok.
```
$ lightning-cli sendpay 
lightning-cli: reading response: Success

$ lightning-cli getinfo
lightning-cli: Connecting to 'lightning-rpc': Connection refused
```
Log:
```
lightningd(19969): Connected json input
lightningd(19969):jcon fd 14: Failing: Missing 'route' parameter
lightningd(19969): FATAL SIGNAL 11 RECEIVED
[...]
```
Head: 
d1ab2e05f406fe7d98bba93c57a529f83e748803

**Comment by ZmnSCPxj** [comment]
Bug is "double free of `names` variable in case of missing required argument."

Confirmation: https://travis-ci.org/ZmnSCPxj/lightning/jobs/336561970#L6400

Bug point: https://github.com/ElementsProject/lightning/blob/master/lightningd/jsonrpc.c#L688

The `names` variable is allocated with `cmd` as the parent: https://github.com/ElementsProject/lightning/blob/master/lightningd/jsonrpc.c#L657

However. `command_success`, `command_fail`, and `command_fail_detailed` all free the `cmd` that succeeds/fails.  We call `command_fail_detailed` just prior to freeing `names` separately: https://github.com/ElementsProject/lightning/blob/master/lightningd/jsonrpc.c#L687

So `command_fail_detailed` frees `cmd`.  Since `names` is rooted with `cmd` as parent, `names` is also freed within `command_fail_detailed`.  Then on the next line we `tal_free` `names` again... double-freeing it.

Will write up a PR in a little while...

**Comment by gdassori** [comment]
```
$ lightning-cli sendpay
{ "code" : -1, "message" : "Missing 'route' parameter" }
$ lightning-cli sendpay
{ "code" : -1, "message" : "Missing 'route' parameter" }
```

Fix confirmed also here :-)
