### ISSUE TITLE
Using the bitcoind rpc instead of using the data directory path

### ISSUE THREAD

**Issue by RvMp** [ElementsProject/lightning#906]
From a security perspective it is good practice to start a proces under a dedicated user account and store data in a proces specific directory that is restricted to that specific user only. Having said this my `bitcoind` proces is running under the user `bitcoind`. `clightning` is running under the user `clightning` and the software is installed in a directory that only gives `clightning` access to the files. Same with `bitcoind`.

Now, `clightning` requires access to the `bitcoind` data-directory and I'm wondering why its not using the `bitcoind` RPC interface?

From a security perspective this is preferred because that way no additional permissions have to be set on the bitcoind data-directory for the clightning user. Hence more secure and nicely separated.

**Comment by cdecker** [comment]
We are using the RPC interface. The only reason we need access to the `bitcoind` datadir is so that `bitcoin-cli` can read the RPC config. With PR #849 merged, we should no longer need that, since we can specify `rpcconnect`, `rpcuser` and `rpcpassword` on the c-lightning command line, and they'll be passed through to `bitcoin-cli` (haven't tested this yet myself). Notice that cookie auth is not yet supported, but should be easy to add that later.

**Comment by cdecker** [comment]
Am I correct in assuming that using `rpcconnect`, `rpcuser` and `rpcpassword` addresses this? If yes, I'd like to close this issue.

**Comment by RvMp** [comment]
Yes I think so. In that case no access to the directory itself should be needed right?
If so, this one can be closed

**Comment by cdecker** [comment]
Indeed it appears we only ever pass `bitcoind->datadir` to the `bitcoin-cli` call, and don't do anything with it ourselves, so we should not need access to it.
