### ISSUE TITLE
Trying to broadcast spent transactions

### ISSUE THREAD

**Issue by grobelr** [ElementsProject/lightning#936]
### Issue and Steps to Reproduce
Lightningd is trying to broadcast one spent transaction:
lightningd(1): Broadcasting tx 020000000001012f94ddd965758445be2dfac132c5e75c517edf5ea04b745a953d0bc04c32829901000000006aedc98002a8c500000000000022002009246bbe3beb48cf1f6f2954f90d648eb04d68570b797e104fead9e6c3c87fd40544020000000000160014c221cdfc1b867d82f19d761d4e09f3b6216d8a8304004830450221008aaa56e4f0efa1f7b7ed690944ac1b59f046a59306fcd1d09924936bd500046d02202b22e13a2ad7e16a0390d726c56dfc9f07647f7abcfac651e35e5dc9d830fc8a01483045022100e096ad0acdc9e8261d1cdad973f7f234ee84a6ee68e0b89ff0c1370896e63fe102202ec36d7554d1feac8bc297279f89830da98953664b73d38767e81ee0763b9988014752210390134e68561872313ba59e56700732483f4a43c2de24559cb8c7039f25f7faf821039eb59b267a78f1020f27a83dc5e3b1e4157e4a517774040a196e9f43f08ad17d52ae89a3b720: 25 error code: -25
error message:
Missing inputs

If you decode the transaction, you can see that this transaction is already done:
https://blockchain.info/tx/d7dd256f9768f58aeb1706299a5a329dd4356e862dc5d0e0595dfccd13753b5f

### `getinfo` output
{ "id" : "035fc00ae1fc445d3ca6caf6a174f5e0cc55e0d001bc5de451a11d7ca660dee4b5", "port" : 9735, "address" : 
        [ 
                { "type" : "ipv4", "address" : "35.185.35.2", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1726-gfc73b1e", "blockheight" : 507984, "network" : "bitcoin" }

**Comment by cdecker** [comment]
I know that looks scary, but it is intentional. We're just rebroadcasting our transactions periodically and react to some on-chain events by also broadcasting our version of the state. In the case of a rebroadcast the transaction may already be in the mempool or even be confirmed, hence the outputs the transaction is spending are no longer available, which causes the scary warning.

In the case of us reacting to an onchain event, we double-spend the other party's close transaction in the hope of getting our close in instead of their's, before proceeding to retaliate against a cheating counterparty.

So don't worry, this is perfectly ok :wink: 

(we may reduce the verbosity of these messages in the future to avoid confusing users).

**Comment by grobelr** [comment]
I got it, the other node broadcast the transaction to blockchain as soon as the channel closed. Thx @cdecker !!
